Repository TracecatHQ/tracecat, pull requests merged in 2024-09, with the labels that each got.

#374 fix(engine): Missing control flow in workflow import
  playbooks/enrichment/triage-using-llms.yml
  tracecat/workflow/management/management.py
Labels: engine, fix

#373 feat(integration): Add list crowdstrike detections summary
  tracecat/actions/integrations/edr/crowdstrike.py
Labels: enhancement, integration, priority:high

#376 feat(integration): Normalize events to ECS
  docker-compose.dev.yml
  docker-compose.yml
  tracecat/actions/__init__.py
  tracecat/actions/etl/normalization/__init__.py
  tracecat/actions/etl/normalization/ecs.py
  tracecat/actions/integrations/__init__.py
Labels: enhancement, integration

#380 feat(integration): Add mongodb doc find one getter
  pyproject.toml
  tracecat/actions/integrations/__init__.py
  tracecat/actions/integrations/database/__init__.py
  tracecat/actions/integrations/database/mongodb.py
Labels: enhancement, good first issue, integration

#383 ci(infra): Drop EC2 Terraform stack
  deployments/aws/ec2/main.tf
  deployments/aws/ec2/outputs.tf
  deployments/aws/ec2/ssm-start-session.sh
  deployments/aws/ec2/user_data.tpl
  deployments/aws/ec2/variables.tf
  docs/mint.json
  docs/self-hosting/deployment-options/aws-ec2.mdx
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/introduction.mdx
Labels: cicd, internal

#384 feat(ui): Add suggestive action to user invite fail error
  frontend/src/components/workspaces/add-workspace-member.tsx
Labels: enhancement, frontend

#385 feat+refactor(engine): Create service layer for workflow schedules
  tracecat/api/app.py
  tracecat/api/routers/schedules.py
  tracecat/dsl/client.py
  tracecat/dsl/schedules.py
  tracecat/types/api.py
  tracecat/workflow/schedules/__init__.py
  tracecat/workflow/schedules/bridge.py
  tracecat/workflow/schedules/models.py
  tracecat/workflow/schedules/router.py
  tracecat/workflow/schedules/service.py
Labels: enhancement, engine, internal

#382 feat(integration): Add Elastic update alert status action
  tracecat/actions/integrations/siem/__init__.py
  tracecat/actions/integrations/siem/elastic.py
Labels: enhancement, integration

#381 Add jira create issue and update issue actions
  tracecat/actions/integrations/__init__.py
  tracecat/actions/integrations/itsm/__init__.py
  tracecat/actions/integrations/itsm/jira.py
Labels: enhancement, integration, priority:high

#386 chore(ui): Update openapi-ts schema for schedule changes
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
Labels: frontend, internal

#377 feat(engine+ui): Implement runtime environments for secrets
  alembic/versions/c4620fec7efc_add_environment_and_unique_constraint_.py
  docker-compose.dev.yml
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/editor.tsx
  frontend/src/components/jsonschema-table.tsx
  frontend/src/components/workbench/panel/udf-panel.tsx
  frontend/src/components/workbench/panel/workflow/form.tsx
  frontend/src/components/workspaces/add-workspace-secret.tsx
  frontend/src/components/workspaces/edit-workspace-secret.tsx
  frontend/src/components/workspaces/workspace-secrets-table.tsx
  frontend/src/lib/hooks.ts
  frontend/src/types/schemas.ts
  tests/conftest.py
  tests/unit/test_sandbox.py
  tests/unit/test_workflows.py
  tracecat/actions/core/workflow.py
  tracecat/auth/dependencies.py
  tracecat/auth/sandbox.py
  tracecat/cases/router.py
  tracecat/contexts.py
  tracecat/db/dependencies.py
  tracecat/db/schemas.py
  tracecat/dsl/_converter.py
  tracecat/dsl/client.py
  tracecat/dsl/common.py
  tracecat/dsl/enums.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/expressions/eval.py
  tracecat/expressions/parser/validator.py
  tracecat/expressions/validation.py
  tracecat/registry.py
  tracecat/secrets/constants.py
  tracecat/secrets/models.py
  tracecat/secrets/router.py
  tracecat/secrets/service.py
  tracecat/validation.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: enhancement, frontend, engine

#387 feat(engine): Mask secrets
  tests/unit/test_secrets.py
  tests/unit/test_workflows.py
  tracecat/config.py
  tracecat/dsl/workflow.py
  tracecat/secrets/common.py
  tracecat/secrets/constants.py
  tracecat/workflow/executions/service.py
Labels: enhancement, engine

#390 release: Bump version to 0.10.0
  deployments/aws/fargate/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/updating.mdx
  tracecat/__init__.py
Labels: frontend, engine, release

#392 feat(integrations): Capture ReadTimeout exceptions in httpx as "expected" errors
  tracecat/actions/core/http.py
  tracecat/dsl/workflow.py
Labels: enhancement, integration

#378 feat(playbooks): Modular detect and extract playbooks
  .github/workflows/test-python.yml
  playbooks/alert_management/aws-guardduty-to-cases.yml
  playbooks/alert_management/aws-guardduty-to-slack.yml
  playbooks/alert_management/crowdstrike-to-cases-no-slack.yml
  playbooks/alert_management/crowdstrike-to-cases.yml
  playbooks/alert_management/datadog-to-cases.yml
  playbooks/alert_management/sentinel-one-to-slack.yml
  playbooks/alert_management/slack-to-crowdstrike-update.yml
  playbooks/alert_management/slack-to-sentinel-one-update.yml
  playbooks/detect/enrich_iocs/ipv4.yml
  playbooks/detect/enrich_iocs/malware_samples.yml
  playbooks/detect/enrich_iocs/urls.yml
  playbooks/detect/extract_iocs.yml
  playbooks/detect/list_alerts/aws_guardduty.yml
  playbooks/detect/list_alerts/crowdstrike_alerts.yml
  playbooks/detect/list_alerts/crowdstrike_detection_summaries.yml
  playbooks/detect/list_alerts/sentinel_one.yml
  playbooks/detect/webhook_alerts/elastic.yml
  playbooks/detect/webhook_alerts/panther.yml
  playbooks/enrichment/tag-user-in-slack-scheduled.yml
  playbooks/enrichment/tag-user-in-slack.yml
  playbooks/enrichment/triage-using-llms.yml
  playbooks/respond/notify_users/slack.yml
  playbooks/threat_intel/virustotal-to-email.yml
  playbooks/tutorials/virustotal_quickstart.yml
  tests/data/log_samples/aws_cloudtrail/cloudtrail_insights.json
  tests/data/log_samples/aws_cloudtrail/cloudtrail_update_trail_error.json
  tests/data/log_samples/aws_cloudtrail/ec2_create_key_pair.json
  tests/data/log_samples/aws_cloudtrail/ec2_start_instances.json
  tests/data/log_samples/aws_cloudtrail/ec2_stop_instances.json
  tests/data/log_samples/aws_cloudtrail/iam_add_user_to_group.json
  tests/data/log_samples/aws_cloudtrail/iam_create_role.json
  tests/data/log_samples/aws_cloudtrail/iam_create_user.json
  tests/data/log_samples/aws_cloudtrail/kms_rotate_keys.json
  tests/data/log_samples/crowdstrike/alert.json
  tests/data/log_samples/emailrep/email.json
  tests/data/log_samples/project_discovery/results/get_all_results.json
  tests/data/log_samples/sentinel_one/alert.json
  tests/data/log_samples/sublime/webhook.json
  tests/playbooks/test_playbooks.py
  tracecat/actions/integrations/enrichment/__init__.py
  tracecat/actions/integrations/vulnerabilities/wazuh.py
  tracecat/expressions/functions.py
Labels: enhancement, playbooks, breaking

#388 feat+refactor(engine): Pull based workflows for schedules + general schedule improvements
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  tests/unit/test_workflows.py
  tracecat/dsl/common.py
  tracecat/dsl/worker.py
  tracecat/dsl/workflow.py
  tracecat/types/exceptions.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/models.py
  tracecat/workflow/schedules/bridge.py
  tracecat/workflow/schedules/models.py
  tracecat/workflow/schedules/router.py
  tracecat/workflow/schedules/service.py
Labels: enhancement

#394 feat(integration): Add jwt token getter to core http action
  tracecat/actions/core/http.py
Labels: enhancement, integration

#393 refactor(engine): Rename logging module to logger
  tests/conftest.py
  tests/playbooks/test_playbooks.py
  tests/unit/test_error_handling.py
  tests/unit/test_expressions.py
  tests/unit/test_workflows.py
  tracecat/actions/integrations/cdr/amazon_guardduty.py
  tracecat/api/app.py
  tracecat/api/routers/public/callbacks.py
  tracecat/api/routers/public/dependencies.py
  tracecat/api/routers/public/webhooks.py
  tracecat/api/routers/udfs.py
  tracecat/api/routers/users.py
  tracecat/api/routers/validation.py
  tracecat/auth/credentials.py
  tracecat/auth/sandbox.py
  tracecat/auth/users.py
  tracecat/authz/controls.py
  tracecat/authz/service.py
  tracecat/cases/service.py
  tracecat/dsl/client.py
  tracecat/dsl/common.py
  tracecat/dsl/graph.py
  tracecat/dsl/io.py
  tracecat/dsl/validation.py
  tracecat/dsl/worker.py
  tracecat/dsl/workflow.py
  tracecat/expressions/functions.py
  tracecat/expressions/parser/core.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/validator.py
  tracecat/logger/__init__.py
  tracecat/logger/_default.py
  tracecat/logger/_logger.py
  tracecat/logger/config.py
  tracecat/logging/__init__.py
  tracecat/secrets/router.py
  tracecat/secrets/service.py
  tracecat/telemetry/capture.py
  tracecat/telemetry/posthog.py
  tracecat/validation.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/router.py
  tracecat/workflow/schedules/router.py
  tracecat/workflow/schedules/service.py
  tracecat/workspaces/router.py
  tracecat/workspaces/service.py
Labels: engine, internal

#395 feat(playbooks): Limacharlie adversary emulation tutorial
  playbooks/tutorials/limacharlie/list_tags.yml
  playbooks/tutorials/limacharlie/run_investigation.yml
  playbooks/tutorials/limacharlie/run_tests.yml
  tests/playbooks/test_playbooks.py
  tracecat/expressions/functions.py
Labels: enhancement, playbooks

#400 chore(engine): Drop elastic normalization and list alerts playbooks
  docker-compose.yml
  playbooks/detect/list_alerts/aws_guardduty.yml
  playbooks/detect/list_alerts/crowdstrike_alerts.yml
  playbooks/detect/list_alerts/crowdstrike_detection_summaries.yml
  playbooks/detect/list_alerts/sentinel_one.yml
  playbooks/detect/webhook_alerts/elastic.yml
  tests/playbooks/test_playbooks.py
  tracecat/actions/__init__.py
  tracecat/actions/etl/normalization/__init__.py
  tracecat/actions/etl/normalization/ecs.py
Labels: engine, internal

#401 feat(integration): Support OAuth2 flows in http core action
  playbooks/tutorials/limacharlie/list_tags.yml
  playbooks/tutorials/limacharlie/run_investigation.yml
  playbooks/tutorials/limacharlie/run_tests.yml
  tracecat/actions/core/http.py
Labels: enhancement, integration

#399 feat(engine+ui): Update expectation API + add configurable input schema
  alembic/versions/5308ffdd79f3_add_expects_to_workflow.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/dashboard/create-workflow-button.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/panel/workflow/form.tsx
  frontend/src/lib/errors.ts
  frontend/src/lib/hooks.ts
  frontend/src/providers/workspace.tsx
  playbooks/detect/enrich_iocs/ipv4.yml
  playbooks/detect/enrich_iocs/malware_samples.yml
  playbooks/detect/enrich_iocs/urls.yml
  playbooks/detect/extract_iocs.yml
  playbooks/detect/webhook_alerts/elastic.yml
  playbooks/detect/webhook_alerts/panther.yml
  playbooks/respond/notify_users/slack.yml
  playbooks/tutorials/limacharlie/run_investigation.yml
  playbooks/tutorials/limacharlie/run_tests.yml
  tests/data/workflows/integration_send_slack.yml
  tests/data/workflows/unit_child_workflow_child.yml
  tests/data/workflows/unit_validation_trigger.yml
  tests/playbooks/test_playbooks.py
  tests/shared.py
  tests/unit/test_expectation.py
  tests/unit/test_workflows.py
  tracecat/db/schemas.py
  tracecat/dsl/common.py
  tracecat/dsl/validation.py
  tracecat/dsl/worker.py
  tracecat/dsl/workflow.py
  tracecat/expressions/expectations.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: enhancement, frontend, engine

#403 feat(engine): Template actions first version
  Dockerfile
  Dockerfile.dev
  templates/_example_hit_localhost_server.yml
  templates/_example_template_action.yml
  tests/unit/test_template_actions.py
  tracecat/dsl/workflow.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/grammar.py
  tracecat/expressions/shared.py
  tracecat/registry.py
Labels: enhancement, engine

#405 feat(engine): Implement remote UDF registry [1/N]
  .env.example
  Dockerfile
  Dockerfile.dev
  docker-compose.dev.yml
  docker-compose.yml
  pyproject.toml
  tests/conftest.py
  tests/data/workflows/unit_ordering_kite.yml
  tests/data/workflows/unit_ordering_kite2.yml
  tests/integration/test_remote.py
  tests/playbooks/test_playbooks.py
  tests/unit/test_registry.py
  tests/unit/test_template_actions.py
  tests/unit/test_workflows.py
  tracecat/actions/etl/__init__.py
  tracecat/config.py
  tracecat/registry.py
Labels: enhancement, engine

#409 ci(infra): Separate out secrets creation script for Fargate deployment
  deployments/aws/fargate/scripts/create-aws-secrets.sh
  docs/self-hosting/deployment-options/aws-ecs.mdx
Labels: cicd, internal
