Repository TracecatHQ/tracecat, pull requests merged in 2024-08, with the labels that each got.

#288 ci(infra): Add Caddy as reverse proxy
  .env.example
  Caddyfile
  docker-compose.dev.yml
  docker-compose.yml
Labels: enhancement, cicd, internal, priority:high

#289 fix(infra): Add root_path to FastAPI app
  .env.example
  Caddyfile
  docker-compose.dev.yml
  docker-compose.yml
  tracecat/api/app.py
  tracecat/config.py
Labels: fix

#290 chore(infra): Drop fargate stack
  .github/workflows/deploy-to-aws.yml
  aws/app.py
  aws/pyproject.toml
  aws/tracecat_cdk/__init__.py
  aws/tracecat_cdk/alb.py
  aws/tracecat_cdk/config.py
  aws/tracecat_cdk/fargate.py
  aws/tracecat_cdk/rds.py
  aws/tracecat_cdk/route53.py
  aws/tracecat_cdk/vpc.py
Labels: cicd, internal

#296 fix(integration): Require content-type is not None before check
  tracecat/actions/core/http.py
Labels: fix

#297 feat(integration): Add deserialize ndjson function
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, integration

#298 feat(integration): Exclude building block rules from Elastic list alerts
  tracecat/actions/integrations/siem/elastic.py
Labels: enhancement, integration

#294 Synchronous calling of webhooks
  tracecat/api/routers/public/webhooks.py
Labels: enhancement, engine, triage, priority:medium

#301 feat(engine): Improve user facing error when workflow is committed without any actions
  tracecat/dsl/common.py
Labels: enhancement, engine

#295 Enhance SMTP integration for STARTTLS
  .env.example
  docker-compose.yml
  tracecat/actions/core/email.py
  tracecat/config.py
Labels: enhancement, integration

#303 fix(infra): Add "_enabled" to docker-compose.yml smtp envs
  docker-compose.yml
Labels: cicd, fix

#305 ci(infra): Docker network hardening & volume cleanup
  docker-compose.dev.yml
  docker-compose.yml
Labels: enhancement, cicd

#293 feat(integration): Add LDAP/AD find and enable / disable
  .env.example
  docker-compose.yml
  pyproject.toml
  tracecat/actions/integrations/iam/__init__.py
  tracecat/actions/integrations/iam/ldap.py
Labels: enhancement, integration

#309 fix(engine): Allow object/attribute access for jsonpath
  tests/unit/test_expressions.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/grammar.py
  tracecat/expressions/parser/validator.py
Labels: engine, fix

#310 feat(engine): Make ExprEvaluator not strict by default and eval jsonpath return None literal
  tests/unit/test_expressions.py
  tracecat/expressions/functions.py
  tracecat/expressions/parser/evaluator.py
Labels: enhancement, engine

#312 fix(engine): Evaluate expressions on non-loop child workflow path
  tests/unit/test_workflows.py
  tracecat/dsl/workflow.py
Labels: engine, fix

#313 feat(ui): Implement change email and password
  frontend/src/app/workspaces/[workspaceId]/settings/account/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/general/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/loading.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/sidebar-nav.tsx
  frontend/src/app/workspaces/page.tsx
  frontend/src/components/auth/update-email-form.tsx
  frontend/src/components/auth/update-password-form.tsx
  frontend/src/components/auth/user-details-table.tsx
  frontend/src/lib/hooks.ts
  tracecat/auth/schemas.py
Labels: enhancement, frontend

#311 docs: Revamp docs for 0.7.0
  docs/api-reference/introduction.mdx
  docs/concepts/case-management.mdx
  docs/concepts/command-line-interface.mdx
  docs/concepts/expressions.mdx
  docs/concepts/schedules.mdx
  docs/concepts/user-defined-functions.mdx
  docs/concepts/webhooks.mdx
  docs/concepts/workflow-definitions.mdx
  docs/deployment.mdx
  docs/gd_slack_quickstart.mdx
  docs/img/env-script.png
  docs/img/google-oauth-client-secrets.png
  docs/img/google-oauth-consent.png
  docs/img/signin-page.png
  docs/img/slack-to-guardduty.jpeg
  docs/img/welcome-page.png
  docs/installation.mdx
  docs/integrations/introduction.mdx
  docs/introduction.mdx
  docs/mint.json
  docs/quickstart.mdx
  docs/self-hosting/authentication/basic.mdx
  docs/self-hosting/authentication/google.mdx
  docs/self-hosting/authentication/introduction.mdx
  docs/self-hosting/deployment-options/aws-ec2.mdx
  docs/self-hosting/deployment-options/aws-ecs.mdx
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/external-facing-webhooks.mdx
  docs/self-hosting/introduction.mdx
  docs/self-hosting/updating.mdx
  docs/updating.mdx
  docs/using-tracecat.mdx
  env.sh
Labels: documentation, frontend, engine, priority:high

#315 feat: Add env-migration script
  env-migration.sh
Labels: enhancement, frontend, engine

#316 fix(ui): Update webhook missing workspaceId
  frontend/src/components/workbench/panel/trigger-panel.tsx
  frontend/src/lib/hooks.ts
  frontend/src/lib/trigger.ts
Labels: frontend, engine, fix

#317 fix(docs): Bullet point formatting
  docs/quickstart.mdx
Labels: fix

#318 refactor(ui): Disable change role as it's not available yet
  frontend/src/components/workspaces/workspace-members-table.tsx
Labels: frontend, internal

#304 feat(engine+infra): Implement DB migrations with alembic
  .github/workflows/test-migrations.yml
  .github/workflows/test-python.yml
  .pre-commit-config.yaml
  Dockerfile
  alembic.ini
  alembic/README
  alembic/env.py
  alembic/script.py.mako
  alembic/versions/ebf7613506e0_initial_migration.py
  pyproject.toml
  scripts/entrypoint.sh
Labels: enhancement, engine, cicd

#320 fix(infra): Docker compose dev wrong smtp env vars
  docker-compose.dev.yml
Labels: bug, engine, fix

#321 fix(docs): Remove comma
  docs/quickstart.mdx
Labels: fix

#322 fix(ui): Add missing etl namespace
  frontend/src/config/udfs.ts
Labels: frontend, fix

#323 feat(engine+ui): Add export workflow json in workbench
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/nav/workbench-nav.tsx
  tracecat/workflow/management/router.py
Labels: enhancement, frontend, engine

#325 fix(ui): Make find playbooks link to github repo
  frontend/src/app/playbooks/layout.tsx
  frontend/src/app/playbooks/loading.tsx
  frontend/src/app/playbooks/page.tsx
  frontend/src/components/dashboard/workflows-dashboard.tsx
  frontend/src/components/nav/workspace-nav.tsx
  frontend/src/components/playbooks/workflows-dashboard-item.tsx
  frontend/src/components/playbooks/workflows-dashboard.tsx
  frontend/src/config/site.ts
  frontend/src/types/index.d.ts
Labels: frontend, fix

#326 fix+refactor(engine): Implement graph and db actions sync + move crea…
  tests/unit/test_workflows.py
  tracecat/dsl/common.py
  tracecat/dsl/graph.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/router.py
Labels: fix

#327 refactor(ui): Remove redundant data table component
  frontend/src/components/cases/columns.tsx
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/data-table/column-header.tsx
  frontend/src/components/data-table/faceted-filter.tsx
  frontend/src/components/data-table/pagination.tsx
  frontend/src/components/data-table/view-options.tsx
  frontend/src/components/table/column-header.tsx
  frontend/src/components/workspaces/workspace-members-table.tsx
  frontend/src/components/workspaces/workspace-secrets-table.tsx
Labels: frontend, internal

#329 fix(engine): Fixes default workspace and admin creation issues on startup
  tracecat/api/app.py
  tracecat/auth/users.py
Labels: engine, fix

#330 refactor(ui): Cleanup legacy types and hooks that are unused or replaced by openapi-ts client types
  frontend/src/lib/hooks.ts
  frontend/src/lib/utils.ts
  frontend/src/lib/workflow.ts
  frontend/src/types/schemas.ts
Labels: frontend, internal

#328 feat(ui): Update wording and drop actions side panel
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/page.tsx
  frontend/src/components/jsonschema-table.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/canvas/selector-node.tsx
  frontend/src/components/workbench/catalog/catalog.tsx
  frontend/src/components/workbench/catalog/trigger-catalog.tsx
  frontend/src/components/workbench/catalog/udf-catalog.tsx
  frontend/src/components/workbench/panel/udf-panel.tsx
  frontend/src/components/workbench/panel/workflow/form.tsx
  frontend/src/components/workbench/panel/workflow/settings.tsx
  frontend/src/components/workbench/workbench.tsx
Labels: enhancement, frontend

#332 fix(engine): No need to pass session into create default admin user
  tracecat/api/app.py
Labels: engine, fix

#333 release: Bump version to 0.7.2
  deployments/aws/ec2/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/updating.mdx
  tracecat/__init__.py
Labels: frontend, engine, release

#331 feat(engine+ui): Move case management to workspace level
  frontend/src/app/workspaces/[workspaceId]/cases/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/aux-click-menu-config.tsx
  frontend/src/components/cases/columns.tsx
  frontend/src/components/cases/panel-content.tsx
  frontend/src/components/cases/table.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/nav/workspace-nav.tsx
  frontend/src/components/timeline.tsx
  frontend/src/lib/hooks.ts
  frontend/src/providers/case-panel.tsx
  frontend/src/providers/cases.tsx
  tracecat/actions/core/cases.py
  tracecat/api/app.py
  tracecat/api/routers/cases/actions.py
  tracecat/api/routers/cases/contexts.py
  tracecat/api/routers/cases/management.py
  tracecat/cases/__init__.py
  tracecat/cases/models.py
  tracecat/cases/router.py
  tracecat/cases/service.py
  tracecat/db/schemas.py
  tracecat/identifiers/__init__.py
  tracecat/types/api.py
Labels: enhancement, frontend, engine

#335 refactor(ui): Clean up unused legacy schemas
  frontend/src/components/workbench/canvas/trigger-node.tsx
  frontend/src/types/schemas.ts
  frontend/src/types/validators.ts
Labels: frontend, internal

#334 fix(ui): Link to GitHub repo in settings
  frontend/src/components/nav/user-nav.tsx
Labels: frontend, fix

#337 fix(engine): Pass schedule params to trigger_input
  tracecat/api/routers/schedules.py
Labels: engine, fix

#338 docs: Use `google_oauth` over `google` in docs
  docs/self-hosting/authentication/google.mdx
  docs/self-hosting/authentication/introduction.mdx
Labels: documentation, frontend, engine

#339 fix(ui): Fix redirect url after creating workflow from yaml
  frontend/src/components/dashboard/create-workflow-button.tsx
Labels: frontend, fix

#340 refactor(ui): Remove inactive properties in schedules table
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
Labels: frontend, refactor

#341 fix+refactor(ui): Fix canvas layout overflow + rename workbench panel component for clarity
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/page.tsx
  frontend/src/app/workspaces/[workspaceId]/workflows/layout.tsx
  frontend/src/app/workspaces/layout.tsx
  frontend/src/components/workbench/panel/workbench-panel.tsx
  frontend/src/components/workbench/workbench.tsx
Labels: frontend, fix

#343 fix(engine): Hash unhashable types using json dumps during validation
  frontend/src/components/nav/workbench-nav.tsx
  tracecat/types/validation.py
Labels: engine, fix

#345 chore(engine): Run migration for 0.7.3
  Dockerfile.dev
  alembic/versions/9331e7a72410_remove_caseaction_and_casecontext_and_.py
  docker-compose.dev.yml
  docker-compose.yml
  scripts/entrypoint.sh
  tracecat/db/schemas.py
Labels: engine, internal, migration

#346 chore(fix): Proper migration
  alembic/versions/50e22ca490f9_initial_migration.py
  alembic/versions/9331e7a72410_remove_caseaction_and_casecontext_and_.py
  alembic/versions/ebf7613506e0_initial_migration.py
  tracecat/api/app.py
Labels: internal

#347 fix(engine): Redo migration to 0.7.3
  alembic/versions/50e22ca490f9_initial_migration.py
  alembic/versions/db946949e584_remove_caseaction_and_casecontext_and_.py
  docker-compose.dev.yml
Labels: engine, fix

#349 feat(ui): More informative validaiton error toast
  frontend/src/providers/workflow.tsx
Labels: enhancement, frontend

#350 feat(ui): Collapse JSON viewer by default
  frontend/src/components/executions/event-details.tsx
Labels: enhancement, frontend

#348 feat(engine+ui): Import/export from json/yaml
  frontend/src/components/dashboard/create-workflow-button.tsx
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/lib/export.ts
  frontend/src/lib/hooks.ts
  playbooks/alert_management/aws-guardduty-to-cases.yml
  playbooks/alert_management/aws-guardduty-to-slack.yml
  playbooks/alert_management/crowdstrike-to-cases-no-slack.yml
  playbooks/alert_management/crowdstrike-to-cases.yml
  playbooks/alert_management/datadog-to-cases.yml
  playbooks/alert_management/sentinel-one-to-slack.yml
  playbooks/alert_management/slack-to-crowdstrike-update.yml
  playbooks/alert_management/slack-to-sentinel-one-update.yml
  playbooks/enrichment/tag-user-in-slack-scheduled.yml
  playbooks/enrichment/tag-user-in-slack.yml
  playbooks/enrichment/triage-using-llms.yml
  playbooks/threat_intel/virustotal-to-email.yml
  tests/data/workflows/playbook_virustotal_email.yml
  tests/unit/test_cli.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: enhancement, frontend, engine

#352 feat(ui): Implement change user role
  frontend/src/components/auth/user-details-table.tsx
  frontend/src/components/nav/user-nav.tsx
  frontend/src/components/workspaces/workspace-members-table.tsx
  frontend/src/providers/workspace.tsx
Labels: enhancement, frontend

#353 feat(engine+ui): Improve error messages [1/N]
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/page.tsx
  frontend/src/app/workspaces/layout.tsx
  frontend/src/components/executions/event-details.tsx
  tracecat/dsl/workflow.py
  tracecat/types/exceptions.py
Labels: enhancement, frontend, engine

#354 ci(infra): Add persistence to EC2 stack
  deployments/aws/ec2/main.tf
  deployments/aws/ec2/ssm-start-session.sh
  deployments/aws/ec2/user_data.tpl
  deployments/aws/ec2/variables.tf
  docs/self-hosting/deployment-options/aws-ec2.mdx
Labels: enhancement, cicd

#356 fix(engine): Add missed context locator
  tracecat/dsl/workflow.py
Labels: engine, fix

#357 fix(engine): Fix for loop validation
  tracecat/expressions/core.py
  tracecat/expressions/parser/validator.py
Labels: engine, fix

#359 feat(engine): Handle http status code 204
  tracecat/actions/core/http.py
Labels: enhancement, engine

#360 release: Bump to 0.8.2
  deployments/aws/ec2/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/updating.mdx
  tracecat/__init__.py
Labels: frontend, engine, release

#362 fix(engine): Allow admin users to view new workspaces
  tracecat/auth/credentials.py
Labels: engine, fix

#363 release: Bump to 0.8.3
  deployments/aws/ec2/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/updating.mdx
  tracecat/__init__.py
Labels: frontend, engine, release

#364 docs: Fix code style in steps
  docs/self-hosting/updating.mdx
Labels: documentation, frontend, engine, fix

#365 test(engine): Update playbook tests + reorganize
  playbooks/alert_management/datadog-to-cases.yml
  playbooks/alert_management/slack-to-sentinel-one-update.yml
  playbooks/enrichment/triage-using-llms.yml
  playbooks/threat_intel/virustotal-to-email.yml
  tests/conftest.py
  tests/integration/test_playbooks.py
  tests/playbooks/test_playbooks.py
  tests/shared.py
  tests/unit/test_error_handling.py
  tests/unit/test_workflows.py
  tracecat/actions/integrations/chat/slack.py
  tracecat/expressions/core.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/grammar.py
  tracecat/expressions/parser/validator.py
  tracecat/expressions/shared.py
  tracecat/validation.py
Labels: engine, internal

#366 fix(ui): Prevent manual trigger window from showing when button is disabled
  frontend/src/components/nav/workbench-nav.tsx
Labels: frontend, fix

#344 ci(infra): Post 0.7.x Fargate Terraform Stack
  alembic/env.py
  deployments/aws/fargate/.gitignore
  deployments/aws/fargate/acm.tf
  deployments/aws/fargate/alb.tf
  deployments/aws/fargate/cloudwatch.tf
  deployments/aws/fargate/dns.tf
  deployments/aws/fargate/ecs-api.tf
  deployments/aws/fargate/ecs-caddy.tf
  deployments/aws/fargate/ecs-temporal.tf
  deployments/aws/fargate/ecs-ui.tf
  deployments/aws/fargate/ecs-worker.tf
  deployments/aws/fargate/ecs.tf
  deployments/aws/fargate/env.sh
  deployments/aws/fargate/iam.tf
  deployments/aws/fargate/locals.tf
  deployments/aws/fargate/main.tf
  deployments/aws/fargate/network.tf
  deployments/aws/fargate/rds.tf
  deployments/aws/fargate/scripts/create-aws-secrets.sh
  deployments/aws/fargate/secrets.tf
  deployments/aws/fargate/security_groups.tf
  deployments/aws/fargate/variables.tf
  docker-compose.yml
  tracecat/db/engine.py
Labels: cicd, self-hosted, internal

#367 test(engine): Add live playbook testing infra and VT playbook
  playbooks/virustotal-quickstart.yml
  tests/playbooks/test_playbooks.py
  tests/unit/test_sandbox.py
  tracecat/auth/sandbox.py
Labels: engine, internal

#368 ci(engine): Include playbooks in ci tests
  .github/workflows/test-python.yml
Labels: engine, internal

#370 release: Bump version to 0.8.4
  deployments/aws/ec2/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/updating.mdx
  tracecat/__init__.py
Labels: frontend, engine, release

#369 refactor(engine+ui): Remove conditional action
  docs/integrations/udfs/core_condition_compare.mdx
  docs/integrations/udfs/core_condition_membership.mdx
  docs/integrations/udfs/core_condition_regex.mdx
  docs/integrations/udfs/core_http_request.mdx
  docs/integrations/udfs/integrations_chat_slack_post_slack_message.mdx
  docs/mint.json
  frontend/src/components/icons.tsx
  tracecat/actions/__init__.py
  tracecat/actions/core/condition.py
Labels: frontend, engine, internal

#372 fix(engine+ui): Fix unable to update secrets
  frontend/src/components/workspaces/edit-workspace-secret.tsx
  tracecat/auth/sandbox.py
  tracecat/secrets/router.py
  tracecat/secrets/service.py
Labels: frontend, engine, fix
