Repository TracecatHQ/tracecat, pull requests merged in 2024-05, with the labels that each got.

#117 docs: Add linux docker networking fix
  docs/installation.mdx
Labels: documentation, frontend, engine

#120 fix(engine): Get Resource.updated_at working
  tracecat/db.py
Labels: engine, fix

#121 docs: Spelling in installation
  docs/installation.mdx
Labels: documentation, frontend, engine

#125 feat(engine): Add passing username and password to rabbitmq uri
  tracecat/messaging/common.py
Labels: engine, build

#126 feat(engine): Suppress stack traces using catch-all handler
  tracecat/api/app.py
  tracecat/runner/app.py
Labels: engine, fix

#135 feat(engine): Split runner url into private/public env vars
  .env.example
  docker-compose.yaml
  env.sh
  tracecat/config.py
  tracecat/db.py
Labels: engine, fix, build

#112 feat(integration): Implement AWS GuardDuty
  frontend/src/components/icons.tsx
  frontend/src/types/schemas.ts
  pyproject.toml
  tracecat/etl/aws_guardduty.py
  tracecat/integrations/__init__.py
  tracecat/integrations/aws_guardduty.py
  tracecat/types/actions.py
Labels: enhancement, integration

#142 feat(ui): Organize workflow form sections into accordions
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/settings/credentials/page.tsx
  frontend/src/components/badges.tsx
  frontend/src/components/console/control-panel.tsx
  frontend/src/components/dashboard/create-workflow-button.tsx
  frontend/src/components/nav/workflow-nav.tsx
  frontend/src/components/new-credential-dialog.tsx
  frontend/src/components/ui/pagination.tsx
  frontend/src/components/ui/sonner.tsx
  frontend/src/components/workspace/canvas/action-node.tsx
  frontend/src/components/workspace/panel/common.tsx
  frontend/src/components/workspace/panel/workflow/controls.tsx
  frontend/src/components/workspace/panel/workflow/form.tsx
  frontend/src/components/workspace/panel/workflow/runs.tsx
  frontend/src/components/workspace/panel/workflow/settings.tsx
  frontend/src/components/workspace/panel/workspace-panel.tsx
  frontend/src/styles/globals.css
  frontend/src/styles/tailwind.ts
Labels: enhancement, frontend
