Repository TracecatHQ/tracecat, pull requests merged in 2024-10, with the labels that each got.

#410 feat(engine+ui): Prevent users from configuring registry_version for now
  tracecat/dsl/models.py
Labels: enhancement, frontend, engine

#414 feat(engine): Add optional keys for registry secret
  registry/tracecat_registry/_internal/models.py
  tracecat/validation.py
Labels: enhancement, engine

#415 feat(engine): Extend AI action with Ollama
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
  pyproject.toml
  registry/tracecat_registry/base/core/llm.py
  tracecat/api/app.py
  tracecat/config.py
  tracecat/llm.py
  tracecat/registry/client.py
  tracecat/secrets/secrets_manager.py
Labels: enhancement, engine

#416 feat(ui): Add registry action table filters
  frontend/src/components/registry/registry-actions-table.tsx
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/components/table/column-header.tsx
  frontend/src/components/table/faceted-filter.tsx
Labels: enhancement, frontend

#417 feat(engine+ui): Add registry action delete
  frontend/src/components/registry/delete-registry-action.tsx
  frontend/src/components/registry/registry-actions-table.tsx
  frontend/src/lib/hooks.ts
  tracecat/registry/actions/router.py
Labels: enhancement, frontend, engine

#419 feat(engine): Add remote repository support + remove versioning
  .env.example
  alembic/versions/36f47d3628bf_remove_versioning_from_registry_tables.py
  docker-compose.dev.yml
  docker-compose.yml
  frontend/src/app/registry/actions/edit/page.tsx
  frontend/src/app/registry/actions/new/page.tsx
  frontend/src/app/registry/repositories/page.tsx
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/registry/registry-actions-table.tsx
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/components/table/pagination.tsx
  frontend/src/components/workbench/panel/udf-panel.tsx
  frontend/src/lib/hooks.ts
  registry/tracecat_registry/__init__.py
  tests/conftest.py
  tests/playbooks/test_playbooks.py
  tests/unit/test_template_actions.py
  tracecat/api/app.py
  tracecat/config.py
  tracecat/contexts.py
  tracecat/db/schemas.py
  tracecat/dsl/action.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/llm.py
  tracecat/registry/actions/models.py
  tracecat/registry/actions/router.py
  tracecat/registry/actions/service.py
  tracecat/registry/client.py
  tracecat/registry/constants.py
  tracecat/registry/executor.py
  tracecat/registry/loaders.py
  tracecat/registry/manager.py
  tracecat/registry/repositories/models.py
  tracecat/registry/repositories/router.py
  tracecat/registry/repositories/service.py
  tracecat/registry/repository.py
  tracecat/validation.py
  tracecat/workflow/executions/models.py
Labels: enhancement, engine

#421 refactor(engine+ui): Remove cases
  alembic/versions/054e842cb078_remove_cases.py
  frontend/src/app/workspaces/[workspaceId]/cases/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/aux-click-menu-config.tsx
  frontend/src/components/cases/categories.tsx
  frontend/src/components/cases/columns.tsx
  frontend/src/components/cases/panel-content.tsx
  frontend/src/components/cases/table.tsx
  frontend/src/components/nav/workspace-nav.tsx
  frontend/src/components/timeline.tsx
  frontend/src/lib/hooks.ts
  frontend/src/providers/case-panel.tsx
  frontend/src/providers/cases.tsx
  tracecat/api/app.py
  tracecat/cases/__init__.py
  tracecat/cases/models.py
  tracecat/cases/router.py
  tracecat/cases/service.py
  tracecat/db/schemas.py
Labels: frontend, engine, internal

#422 fix(engine): Better HTTP error propagation
  frontend/src/components/workbench/panel/udf-panel.tsx
  tracecat/registry/actions/router.py
  tracecat/registry/client.py
  tracecat/registry/executor.py
Labels: engine, fix

#423 release: 0.11.1
  deployments/aws/fargate/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/updating.mdx
  tracecat/__init__.py
Labels: frontend, engine, release

#425 feat(engine): Improve registry actions service sync diffing logic
  tracecat/registry/actions/service.py
  tracecat/registry/repository.py
Labels: enhancement, engine

#426 feat: Improve error message in new/edit registry action forms
  frontend/src/app/registry/actions/edit/page.tsx
  frontend/src/app/registry/actions/new/page.tsx
  tracecat/registry/actions/router.py
Labels: enhancement, frontend, engine

#427 refactor(engine): Remove sync on start
  tracecat/api/app.py
  tracecat/registry/repositories/service.py
Labels: engine, internal

#428 refactor(engine): Remove legacy runtime tests
  cli/tracecat_cli/workflow.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  playbooks/tutorials/virustotal_quickstart.yml
  tests/data/workflows/unit_runtime_test_adder_tree.yml
  tests/data/workflows/unit_runtime_test_adder_tree_expected.yml
  tests/data/workflows/unit_runtime_test_chain.yml
  tests/data/workflows/unit_runtime_test_chain_data.json
  tests/data/workflows/unit_runtime_test_chain_expected.yml
  tests/unit/test_workflows.py
  tracecat/api/routers/public/webhooks.py
  tracecat/dsl/common.py
  tracecat/dsl/io.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/registry/actions/router.py
  tracecat/registry/executor.py
  tracecat/testing/registry.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
Labels: engine, internal

#430 refactor(engine): Remove legacy callback router
  tracecat/api/app.py
  tracecat/api/routers/public/callbacks.py
  tracecat/api/routers/public/dependencies.py
  tracecat/api/routers/public/webhooks.py
  tracecat/parse.py
  tracecat/types/api.py
Labels: engine, internal

#432 fix(integration): Add missing ApiKey to Authorization header
  registry/tracecat_registry/templates/sentinel_one/get_agents_by_hostname.yml
  registry/tracecat_registry/templates/sentinel_one/get_agents_by_hostname_exact.yml
  registry/tracecat_registry/templates/sentinel_one/get_agents_by_username.yml
  registry/tracecat_registry/templates/sentinel_one/get_agents_by_username_exact.yml
  registry/tracecat_registry/templates/sentinel_one/get_firewall_rule.yml
  registry/tracecat_registry/templates/sentinel_one/isolate_agent.yml
  registry/tracecat_registry/templates/sentinel_one/list_alerts.yml
  registry/tracecat_registry/templates/sentinel_one/unisolate_agent.yml
  registry/tracecat_registry/templates/sentinel_one/update_alert_status.yml
  registry/tracecat_registry/templates/sentinel_one/update_firewall_rule.yml
Labels: integration, fix

#434 fix(engine): Fix repository not syncing in production docker compose builds
  Dockerfile
  tracecat/config.py
  tracecat/registry/actions/service.py
  tracecat/registry/repositories/router.py
  tracecat/registry/repository.py
Labels: engine, fix

#435 fix(integration): GetQueryDetect wrong operation ID and args
  registry/tracecat_registry/templates/crowdstrike/list_detects.yml
Labels: integration, fix

#437 ci(infra): Fix issue with no snapshot terraform apply
  deployments/aws/fargate/rds.tf
Labels: fix, internal, infrastructure

#436 ci(infra): Add missing remote repo vars to Fargate stack
  deployments/aws/fargate/ecs-api.tf
  deployments/aws/fargate/variables.tf
Labels: fix, internal, infrastructure

#433 fix(engine): Add retries to recreate DB engine if test conn raises an exception
  alembic/env.py
  pyproject.toml
  tracecat/db/engine.py
Labels: engine, fix

#438 feat(engine): Sync template actions from remote repository
  tracecat/registry/repository.py
Labels: enhancement, engine

#439 fix(registry): Detects typo
  registry/tracecat_registry/templates/crowdstrike/list_detects.yml
Labels: frontend, engine, fix

#441 fix: Revert changes to migration script
  alembic/env.py
  pyproject.toml
  tracecat/db/engine.py
Labels: frontend, engine, fix

#443 ci(infra): Increase rds scheduled key rotate to 365 days
  deployments/aws/fargate/ecs-temporal.tf
  deployments/aws/fargate/rds.tf
  tracecat/db/engine.py
Labels: internal, infrastructure

#444 ci(infra): Increase rds scheduled key rotate to 365 days (#443)
  deployments/aws/fargate/ecs-temporal.tf
  deployments/aws/fargate/rds.tf
  tracecat/db/engine.py
Labels: infrastructure

#446 fix(integration): Incorrect Jira referencing secret
  registry/tracecat_registry/templates/jira/create_issue.yml
  registry/tracecat_registry/templates/jira/update_issue.yml
Labels: integration, fix

#448 release: 0.11.7 (Jira fixes)
  deployments/aws/fargate/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/self-hosting/updating.mdx
  tracecat/__init__.py
Labels: frontend, engine, release

#451 feat(integration): Add search IP address in Crowdsec template
  registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
Labels: enhancement, integration

#453 refactor: Rename UDFActionInput to RunActionInput
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  tracecat/dsl/action.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/registry/actions/router.py
  tracecat/registry/client.py
  tracecat/registry/executor.py
  tracecat/workflow/executions/models.py
Labels: frontend, engine, internal

#455 fix(engine): Fix action validation
  tracecat/validation.py
Labels: engine, fix

#456 feat: Add configurable action retries
  frontend/next-env.d.ts
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/workbench/panel/udf-panel.tsx
  tracecat/dsl/action.py
  tracecat/dsl/constants.py
  tracecat/dsl/graph.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/types/api.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/management.py
Labels: enhancement, frontend, engine

#459 feat(ui): Smoothstep edges
  frontend/src/components/workbench/canvas/canvas.tsx
Labels: enhancement, frontend

#458 feat: Add action start delay
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/workbench/panel/udf-panel-tooltips.tsx
  frontend/src/components/workbench/panel/udf-panel.tsx
  tracecat/dsl/action.py
  tracecat/dsl/graph.py
  tracecat/dsl/models.py
  tracecat/types/api.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/management/management.py
Labels: enhancement, frontend, engine

#460 fix(engine): Include start delay in total activity timeout
  tracecat/dsl/workflow.py
Labels: engine, fix

#445 feat(engine): Improve logger colors + formatting
  tracecat/logger/_logger.py
Labels: enhancement, engine

#442 refactor: Don't have to reexport udfs
  registry/tracecat_registry/base/__init__.py
  registry/tracecat_registry/base/etl/__init__.py
  registry/tracecat_registry/base/etl/extraction/__init__.py
  registry/tracecat_registry/base/etl/sinks/__init__.py
  registry/tracecat_registry/integrations/__init__.py
Labels: frontend, engine, internal

#462 fix(integration): Incorrect template action format
  registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
Labels: fix

#463 fix: Add defaults for retry_policy and start_delay for EventGroup
  tracecat/workflow/executions/models.py
Labels: frontend, engine, fix

#464 chore(ui): Drop unused integrations link
  frontend/src/components/nav/nav-buttons.tsx
  frontend/src/components/nav/organization-nav.tsx
  frontend/src/components/nav/registry-nav.tsx
  frontend/src/components/nav/workspace-nav.tsx
Labels: frontend, internal

#466 feat: Add default email + pw as fallback
  tracecat/auth/users.py
Labels: enhancement, frontend, engine

#468 refactor: Refactor expression functions to be more docs friendly
  docs/integrations/expressions.mdx
  docs/mint.json
  tracecat/expressions/functions.py
Labels: frontend, engine, internal

#474 fix(integration): Assignment error if jwt is specified but headers none
  registry/tracecat_registry/base/core/http.py
Labels: integration, fix
