Repository TracecatHQ/tracecat, pull requests merged in 2024-03, with the labels that each got.

#6 docs: Add workflows / actions / events / cases basics
  docs/actions/types/ai-actions/overview.mdx
  docs/actions/types/data-transforms.mdx
  docs/actions/types/http-request.mdx
  docs/actions/types/if-conditions/overview.mdx
  docs/actions/types/open-case.mdx
  docs/actions/types/send-email.mdx
  docs/actions/types/webhook.mdx
  docs/core/actions.mdx
  docs/core/ai-features.mdx
  docs/core/case-management.mdx
  docs/core/events-log.mdx
  docs/core/metrics.mdx
  docs/core/workflows.mdx
  docs/introduction.mdx
  docs/mint.json
  docs/tutorials/phishing.mdx
  docs/tutorials/pizza.mdx
Labels: documentation, frontend, engine

#11 feat: Add basic self hosting support
  aws/stack.py
  docker-compose.self-host.yaml
  docker-compose.yaml
  frontend/.dockerignore
  frontend/.env.example
  frontend/Dockerfile
  frontend/package.json
  frontend/src/app/auth/callback/route.ts
  frontend/src/components/auth/forms.tsx
  frontend/src/components/auth/login.tsx
  frontend/src/lib/auth.ts
  supabase/.gitignore
  supabase/config.toml
  supabase/seed.sql
  tracecat/config.py
  tracecat/db.py
Labels: enhancement, frontend, engine

#13 Fix self host .env examples and documentation
  .env.example
  docker-compose.self-host.yaml
  docker-compose.yaml
  docs/installation.mdx
  frontend/.env.example
  supabase/config.toml
  tracecat/config.py
  tracecat/db.py
Labels: documentation, good first issue
