Repository TracecatHQ/tracecat, pull requests merged in 2024-12, with the labels that each got.

#578 docs(fix): Pathing mistake in control flow tutorial
  docs/tutorials/2-control-flow.mdx
Labels: documentation

#577 feat: Add basic intellisense
  frontend/src/app/registry/actions/edit/page.tsx
  frontend/src/app/registry/actions/new/page.tsx
  frontend/src/app/workspaces/layout.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/editor.tsx
  frontend/src/components/editor/editor.tsx
  frontend/src/components/editor/index.tsx
  frontend/src/components/editor/styles.ts
  frontend/src/components/editor/suggestions.ts
  frontend/src/components/editor/yaml-lang.ts
  frontend/src/components/nav/dynamic-nav.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/styles/globals.css
  tracecat/api/app.py
  tracecat/editor/__init__.py
  tracecat/editor/models.py
  tracecat/editor/router.py
Labels: enhancement, frontend, engine

#557 fix(ui): Show action node missing inputs correctly
  frontend/src/components/workbench/canvas/action-node.tsx
Labels: frontend, fix

#580 ci(infra): Security group fixes
  deployments/aws/ecs/security_groups.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
Labels: cicd, infrastructure

#581 fix: Oauth redirect
  frontend/src/app/auth/oauth/callback/route.ts
  tracecat/api/app.py
Labels: frontend, engine, fix

#583 fix(ui): Make all usage of CustomEditor dynamic
  frontend/src/app/registry/actions/edit/page.tsx
  frontend/src/app/registry/actions/new/page.tsx
  frontend/src/components/editor/dynamic.tsx
  frontend/src/components/editor/editor.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
Labels: frontend, fix

#584 fix(ui): Prevent duplicate editor registrations + use yaml extended in all editors
  frontend/src/app/registry/actions/edit/page.tsx
  frontend/src/app/registry/actions/new/page.tsx
  frontend/src/components/editor/editor.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
Labels: frontend, fix

#585 fix(ui): Fix and cleanup related workflow runs
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/executions/nav.tsx
  frontend/src/components/executions/testdecode.ts
  frontend/src/lib/event-history.ts
Labels: frontend, fix

#587 fix(infra): Align network configuration for api and ollama in docker-compose
  docker-compose.dev.yml
  docker-compose.yml
Labels: fix, infrastructure

#586 docs: Update Actions registry tutorial
  docs/img/tutorials/actions-registry/actions-registry.png
  docs/img/tutorials/actions-registry/clone-template.png
  docs/img/tutorials/actions-registry/registry.jpeg
  docs/tutorials/3-actions-registry.mdx
Labels: documentation, frontend, engine

#588 feat: Add session management + user last login
  alembic/versions/307c3bb9fad5_add_user_last_login_at.py
  alembic/versions/b7a3a2146bac_add_accesstoken_id.py
  frontend/src/app/organization/sessions/page.tsx
  frontend/src/app/organization/sidebar-nav.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-members-table.tsx
  frontend/src/components/organization/org-sessions-table.tsx
  frontend/src/lib/hooks.tsx
  tracecat/auth/models.py
  tracecat/auth/users.py
  tracecat/db/schemas.py
  tracecat/identifiers/__init__.py
  tracecat/organization/models.py
  tracecat/organization/router.py
  tracecat/organization/service.py
Labels: enhancement, frontend, engine

#556 feat(engine): Separate registry service
  .github/workflows/test-python.yml
  Caddyfile
  docker-compose.dev.yml
  docker-compose.yml
  tests/conftest.py
  tests/unit/test_workflows.py
  tracecat/api/app.py
  tracecat/api/common.py
  tracecat/api/registry.py
  tracecat/config.py
  tracecat/db/engine.py
  tracecat/dsl/models.py
  tracecat/expressions/eval.py
  tracecat/identifiers/__init__.py
  tracecat/registry/actions/router.py
  tracecat/registry/client.py
  tracecat/registry/constants.py
  tracecat/registry/executor.py
  tracecat/registry/repositories/router.py
Labels: enhancement, engine

#582 feat(integration): Wazuh token exp timout
  registry/tracecat_registry/templates/wazuh/get_auth_token.yml
Labels: enhancement, integration

#590 refactor(engine): Move registry management endpoints into api service + restructure registry as executor service
  .env.example
  .github/workflows/test-python.yml
  Caddyfile
  docker-compose.dev.yml
  docker-compose.yml
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  tests/conftest.py
  tests/unit/test_workflows.py
  tracecat/api/app.py
  tracecat/api/executor.py
  tracecat/config.py
  tracecat/identifiers/__init__.py
  tracecat/registry/actions/router.py
  tracecat/registry/actions/service.py
  tracecat/registry/client.py
  tracecat/registry/constants.py
  tracecat/registry/executor.py
  tracecat/workflow/executions/service.py
Labels: engine, internal

#591 feat(integration)!: Rewrite LDAP UDFs into templates
  registry/tracecat_registry/integrations/ldap3.py
  registry/tracecat_registry/templates/ldap/disable_active_directory_user.yml
  registry/tracecat_registry/templates/ldap/enable_active_directory_user.yml
  registry/tracecat_registry/templates/ldap/expire_active_directory_user.yml
  registry/tracecat_registry/templates/ldap/expire_user.yml
  registry/tracecat_registry/templates/ldap/find_active_directory_users.yml
  registry/tracecat_registry/templates/ldap/find_users.yml
  tracecat/expressions/functions.py
Labels: enhancement, integration, breaking

#573 feat(integration): S3 getter and Ansible playbook runner
  registry/pyproject.toml
  registry/tracecat_registry/integrations/ansible.py
  registry/tracecat_registry/integrations/boto3.py
  registry/tracecat_registry/integrations/s3.py
  registry/tracecat_registry/templates/ansible/run_playbook_from_s3.yml
Labels: enhancement, integration

#598 fix(engine): Use wf execution or schedule id for related wf exec ids
  tracecat/workflow/executions/models.py
Labels: engine, fix

#597 feat(engine): Add temporal workflow task timeout config + propagate t…
  docker-compose.dev.yml
  docker-compose.yml
  tracecat/config.py
  tracecat/dsl/workflow.py
  tracecat/registry/client.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/schedules/bridge.py
Labels: enhancement, engine

#601 fix(integrations): Use correct function name for ansible run playbook
  registry/tracecat_registry/templates/ansible/run_playbook_from_s3.yml
Labels: fix

#603 test: Check that we can list all registry actions
  tests/unit/test_registry.py
Labels: frontend, engine, internal

#604 fix(engine): Pull secrets for template action steps
  tests/data/test_actions/test_executor_functions.py
  tests/unit/test_executor.py
  tracecat/registry/executor.py
Labels: engine, fix

#605 feat(engine): Make executor client timeout configurable with 120s def…
  tracecat/config.py
  tracecat/registry/client.py
Labels: enhancement, engine

#606 feat(engine): Improve process pool event loop management
  tests/unit/test_executor.py
  tracecat/registry/executor.py
Labels: enhancement, engine

#607 fix(engine): Load udf secrets in env correctly
  tracecat/registry/executor.py
Labels: engine, fix

#609 feat(engine): Replace ProcessPoolExecutor with Ray
  docker-compose.dev.yml
  pyproject.toml
  tests/conftest.py
  tests/unit/test_executor.py
  tests/unit/test_template_actions.py
  tests/unit/test_workflows.py
  tracecat/api/executor.py
  tracecat/dsl/workflow.py
  tracecat/executor/__init__.py
  tracecat/executor/engine.py
  tracecat/executor/models.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/registry/actions/models.py
Labels: enhancement, engine

#610 feat(engine): Use ray in executor
  docker-compose.dev.yml
  pyproject.toml
  tests/conftest.py
  tests/unit/test_executor.py
  tests/unit/test_template_actions.py
  tests/unit/test_workflows.py
  tracecat/api/executor.py
  tracecat/dsl/workflow.py
  tracecat/executor/__init__.py
  tracecat/executor/engine.py
  tracecat/executor/models.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/registry/actions/models.py
Labels: enhancement, engine

#611 ci(infra): Add temporal ui variables
  deployments/aws/ecs/ecs-temporal-ui.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
Labels: internal, infrastructure

#613 feat: Improve repo sync lifecycle
  alembic/versions/da03a0dfa2db_add_repo_last_synced_at_and_commit_sha.py
  frontend/src/app/registry/actions/new/page.tsx
  frontend/src/app/registry/repositories/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/lib/hooks.tsx
  tracecat/api/app.py
  tracecat/api/common.py
  tracecat/api/executor.py
  tracecat/db/schemas.py
  tracecat/executor/models.py
  tracecat/executor/router.py
  tracecat/registry/actions/service.py
  tracecat/registry/client.py
  tracecat/registry/repositories/models.py
  tracecat/registry/repositories/router.py
  tracecat/registry/repositories/service.py
  tracecat/registry/repository.py
Labels: enhancement, frontend, engine

#614 fix(engine): Use ALLOW_ALL schedule overlap policy
  tracecat/workflow/schedules/bridge.py
Labels: engine, fix

#615 ci(infra): Add executor client timeout config
  deployments/aws/ecs/locals.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
Labels: internal

#618 feat(integration): Google SecOps list cases and detections
  pyproject.toml
  registry/tracecat_registry/integrations/google_api.py
  registry/tracecat_registry/templates/google_secops/list_cases_by_title.yml
  registry/tracecat_registry/templates/google_secops/list_detections_by_rule_id.yml
Labels: enhancement, integration

#619 feat(integration)!: Support multiple scopes in Microsoft graph
  registry/tracecat_registry/integrations/microsoft_graph.py
Labels: enhancement, integration, breaking

#620 fix(integration): Add cert markers and faster fail parsing to SAML
  deployments/aws/ecs/iam.tf
  deployments/aws/ecs/secrets.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
  docs/mint.json
  docs/self-hosting/authentication/introduction.mdx
  docs/self-hosting/authentication/okta.mdx
  docs/self-hosting/authentication/saml.mdx
  tracecat/auth/saml.py
  tracecat/config.py
Labels: fix, self-hosted

#612 ci(build): Multi-platform runner builds
  .github/workflows/build-push-images.yml
  .github/workflows/test-build-push-ui.yml
Labels: cicd, build, performance

#621 fix(engine): Consider edge components when building graph
  tracecat/dsl/common.py
Labels: engine, fix

#622 feat(engine): Add FN.range
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, engine

#623 feat(engine): Attempt to block less in child workflow loop
  tracecat/dsl/workflow.py
Labels: enhancement, engine

#624 fix(engine): Consdier edge components when building graph
  tracecat/dsl/common.py
Labels: engine, fix

#625 feat(engine): Add FN.range
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, engine

#626 feat(engine): Yield control in hot loop
  tracecat/dsl/workflow.py
Labels: enhancement, engine

#627 ci(infra): Optimize ECS
  deployments/aws/ecs/ecs-api.tf
  deployments/aws/ecs/ecs-caddy.tf
  deployments/aws/ecs/ecs-executor.tf
  deployments/aws/ecs/ecs-temporal-ui.tf
  deployments/aws/ecs/ecs-temporal.tf
  deployments/aws/ecs/ecs-ui.tf
  deployments/aws/ecs/ecs-worker.tf
Labels: cicd, internal, infrastructure

#628 ci(infra): Optimize ECS (#627)
  deployments/aws/ecs/ecs-api.tf
  deployments/aws/ecs/ecs-caddy.tf
  deployments/aws/ecs/ecs-executor.tf
  deployments/aws/ecs/ecs-temporal-ui.tf
  deployments/aws/ecs/ecs-temporal.tf
  deployments/aws/ecs/ecs-ui.tf
  deployments/aws/ecs/ecs-worker.tf
Labels: enhancement, cicd, infrastructure

#645 chore(engine): Delete alpha telemetry module
  tracecat/telemetry/__init__.py
  tracecat/telemetry/capture.py
  tracecat/telemetry/events.py
  tracecat/telemetry/posthog.py
Labels: internal

#644 feat+fix(engine)!: Support enums and defaults in Action Templates
  registry/tracecat_registry/__init__.py
  registry/tracecat_registry/_internal/exceptions.py
  tests/unit/test_expectation.py
  tests/unit/test_registry.py
  tests/unit/test_template_actions.py
  tracecat/executor/service.py
  tracecat/expressions/expectations.py
  tracecat/registry/actions/models.py
  tracecat/registry/repository.py
  tracecat/types/exceptions.py
Labels: engine, breaking

#648 feat(engine): Support Temporal API key and MTLS from AWS SM
  deployments/aws/ecs/ecs-temporal-ui.tf
  deployments/aws/ecs/ecs-temporal.tf
  deployments/aws/ecs/locals.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
  tracecat/config.py
  tracecat/dsl/client.py
Labels: enhancement, engine, infrastructure

#657 fix(integration): Incorrect ldap config kwargs in creating client
  registry/tracecat_registry/integrations/ldap3.py
  registry/tracecat_registry/templates/ldap/find_active_directory_users.yml
  registry/tracecat_registry/templates/ldap/find_users.yml
Labels: integration, fix

#654 feat(engine): Implement workflow tags backend
  alembic/versions/3bc0a0970817_add_tags_and_workflow_tags_tables.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  tests/conftest.py
  tests/unit/test_secrets_service.py
  tests/unit/test_tags_service.py
  tracecat/api/app.py
  tracecat/db/schemas.py
  tracecat/identifiers/__init__.py
  tracecat/tags/__init__.py
  tracecat/tags/models.py
  tracecat/tags/router.py
  tracecat/tags/service.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
  tracecat/workflow/tags/__Init__.py
  tracecat/workflow/tags/models.py
  tracecat/workflow/tags/router.py
  tracecat/workflow/tags/service.py
Labels: enhancement, engine

#663 fix(engine): Use func.now() for sa_column ts + add default factory for created_at and updated_at
  tracecat/db/schemas.py
Labels: internal

#664 refactor: Cleanup workflow management models
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/dashboard/delete-workflow-dialog.tsx
  frontend/src/components/dashboard/workflows-dashboard-item.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
  frontend/src/components/workbench/panel/workbench-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
  frontend/src/lib/hooks.tsx
  frontend/src/providers/workflow.tsx
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: internal

#665 chore(docs): Update API and cheatsheet docs
  docs/api-reference/reference/editor/list-actions.mdx
  docs/api-reference/reference/editor/list-functions.mdx
  docs/api-reference/reference/organization/delete-org-member.mdx
  docs/api-reference/reference/organization/delete-session.mdx
  docs/api-reference/reference/organization/list-org-members.mdx
  docs/api-reference/reference/organization/list-sessions.mdx
  docs/api-reference/reference/organization/update-org-member.mdx
  docs/api-reference/reference/registry-repositories/sync-executor-from-registry-repository.mdx
  docs/api-reference/reference/registry-repositories/sync-registry-repository.mdx
  docs/api-reference/reference/tags/create-tag.mdx
  docs/api-reference/reference/tags/delete-tag.mdx
  docs/api-reference/reference/tags/get-tag.mdx
  docs/api-reference/reference/tags/list-tags.mdx
  docs/api-reference/reference/tags/update-tag.mdx
  docs/api-reference/reference/workflows/add-tag.mdx
  docs/api-reference/reference/workflows/list-tags.mdx
  docs/api-reference/reference/workflows/remove-tag.mdx
  docs/cheatsheets/functions.mdx
  docs/cheatsheets/integrations.mdx
  docs/mint.json
  docs/openapi.yml
  justfile
Labels: documentation

#666 fix(engine): Update ExprContext type hints
  tracecat/dsl/workflow.py
  tracecat/executor/service.py
Labels: internal

#667 fix(engine): Fix workflow type hints
  tracecat/dsl/workflow.py
Labels: internal

#637 feat(integration): SentinelOne list Threats + update Threat status
  registry/tracecat_registry/templates/sentinel_one/list_threats.yml
  registry/tracecat_registry/templates/sentinel_one/update_threat_status.yml
Labels: integration

#668 fix(engine): Fix and simplify dsl type hints
  tracecat/executor/service.py
  tracecat/registry/actions/models.py
  tracecat/registry/loaders.py
  tracecat/registry/repository.py
  tracecat/validation/service.py
Labels: internal

#669 refactor(engine): Tidy up BaseService and workflow definitions service
  tracecat/service.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/schedules/service.py
Labels: internal

#672 build: Improve error handling in `env.sh` #653
  env.sh
Labels: documentation, build

#673 fix(engine): Fix update workflow spelling
  tracecat/workflow/management/management.py
  tracecat/workflow/management/router.py
Labels: internal

#674 refactor(engine): Wrap worker activities
  tests/unit/test_workflows.py
  tracecat/dsl/worker.py
Labels: internal

#671 build+docs: Make ollama optional
  docker-compose.ollama.yml
  docker-compose.yml
  docs/img/self-hosting/ai-action.png
  docs/mint.json
  docs/self-hosting/deployment-options/ollama.mdx
  docs/self-hosting/introduction.mdx
Labels: documentation, build

#676 feat(engine): Implement runtime workflow alias resolution for child workflows
  registry/tracecat_registry/base/core/workflow.py
  tests/unit/test_workflows.py
  tracecat/dsl/common.py
  tracecat/dsl/workflow.py
  tracecat/validation/service.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/management/management.py
Labels: enhancement

#677 feat(ui): Implement workflow alias UI
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
Labels: enhancement, frontend

#679 feat(ui): Add workflow alias to action nodes
  frontend/src/components/workbench/canvas/action-node.tsx
Labels: enhancement, frontend

#678 feat(ui): Add workflow alias to workbench navbar
  frontend/src/components/nav/workbench-nav.tsx
Labels: enhancement, frontend

#680 refactor(engine): Make RoleACL testing friendly
  tracecat/auth/credentials.py
Labels: internal

#681 fix(engine): Propagate executor error messages safely
  tests/unit/test_executor.py
  tests/unit/test_workflows.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/types/exceptions.py
Labels: enhancement, fix

#683 release: 0.19.0
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#684 feat(integration): Add FN.replace string function
  docs/cheatsheets/functions.mdx
  tracecat/expressions/functions.py
Labels: enhancement, function
