Repository TracecatHQ/tracecat, pull requests merged in 2024-11, with the labels that each got.

#471 feat: Add error path + join strategy
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/editor.tsx
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/workbench/canvas/canvas.tsx
  frontend/src/components/workbench/canvas/custom-handle.tsx
  frontend/src/components/workbench/canvas/selector-node.tsx
  frontend/src/components/workbench/canvas/udf-node.tsx
  frontend/src/components/workbench/panel/udf-panel-tooltips.tsx
  frontend/src/components/workbench/panel/udf-panel.tsx
  tests/conftest.py
  tests/data/workflows/unit_conditional_adder_diamond_skip_with_join_weak_dep.yml
  tests/unit/test_view.py
  tests/unit/test_workflows.py
  tracecat/dsl/action.py
  tracecat/dsl/common.py
  tracecat/dsl/constants.py
  tracecat/dsl/enums.py
  tracecat/dsl/models.py
  tracecat/dsl/scheduler.py
  tracecat/dsl/view.py
  tracecat/dsl/workflow.py
  tracecat/expressions/shared.py
  tracecat/registry/actions/service.py
  tracecat/registry/client.py
  tracecat/registry/executor.py
  tracecat/types/api.py
  tracecat/types/exceptions.py
  tracecat/validation.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/management/management.py
Labels: enhancement, frontend, engine

#477 feat(ui): Update target handle to show join strategy
  frontend/src/components/workbench/canvas/custom-handle.tsx
  frontend/src/components/workbench/canvas/udf-node.tsx
Labels: enhancement, frontend

#478 refactor: Cleanup action service and remove save action button
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/canvas/canvas.tsx
  frontend/src/components/workbench/canvas/selector-node.tsx
  frontend/src/components/workbench/panel/action-panel-tooltips.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/workbench-panel.tsx
  frontend/src/lib/hooks.tsx
  tracecat/api/app.py
  tracecat/dsl/common.py
  tracecat/types/api.py
  tracecat/workflow/actions/__init__.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/actions/router.py
  tracecat/workflow/actions/service.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: frontend, engine, internal

#479 fix: Separate out source and target handles for different node types
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/canvas/custom-handle.tsx
  frontend/src/components/workbench/canvas/trigger-node.tsx
Labels: frontend, engine, fix

#480 feat(ui): Sort schema by required then alphabet
  frontend/src/components/jsonschema-table.tsx
Labels: enhancement, frontend

#481 fix(ui): Delete selector node when pressing esc even when focused
  frontend/src/components/workbench/canvas/selector-node.tsx
Labels: frontend, fix

#482 feat: Update action validation to work with aggressive autosave
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
  frontend/src/components/workbench/panel/workbench-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
  frontend/src/components/workbench/panel/workflow/form.tsx
  frontend/src/lib/hooks.tsx
  frontend/src/providers/workflow.tsx
  tracecat/registry/actions/models.py
  tracecat/types/validation.py
  tracecat/validation.py
Labels: enhancement, frontend, engine

#473 feat(integration): Crowdsec add block and unblock file
  registry/tracecat_registry/templates/crowdsec/block_ip_address.yml
  registry/tracecat_registry/templates/crowdsec/unblock_ip_address.yml
Labels: enhancement, integration

#483 feat(ui): Allow independent scrolling of workflow runs columns
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/page.tsx
Labels: enhancement, frontend

#476 feat(integrations)!: Drop jwt and oauth support in http action
  registry/tracecat_registry/base/core/http.py
  registry/tracecat_registry/integrations/checkpoint.py
  registry/tracecat_registry/integrations/limacharlie.py
  registry/tracecat_registry/integrations/microsoft_graph.py
  registry/tracecat_registry/integrations/wiz.py
  registry/tracecat_registry/templates/microsoft_defender/list_alerts.yml
  registry/tracecat_registry/templates/wiz/list_issues.yml
Labels: enhancement, breaking

#484 feat(ui): Add action panel tabs + cleanup action panel description section
  frontend/src/components/workbench/panel/action-panel.tsx
Labels: enhancement, frontend

#485 refactor(engine): Remove unused /validate-workflow endpoint
  tracecat/api/app.py
  tracecat/api/routers/validation.py
Labels: engine, internal

#486 feat+refactor(ui): Improve copy button + some cleanup
  frontend/src/components/copy-button.tsx
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/canvas/trigger-node.tsx
Labels: enhancement

#487 feat(ui): Add workflow panel tabs
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
Labels: enhancement, frontend

#488 refactor(ui): Move retry policy into its own tab
  frontend/src/components/workbench/panel/action-panel-tooltips.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
Labels: frontend, internal

#489 feat+refactor(engine): Cleanup and improve webhooks
  tests/unit/test_expressions.py
  tracecat/api/app.py
  tracecat/dsl/common.py
  tracecat/dsl/models.py
  tracecat/dsl/validation.py
  tracecat/dsl/workflow.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/grammar.py
  tracecat/webhooks/__init__.py
  tracecat/webhooks/dependencies.py
  tracecat/webhooks/models.py
  tracecat/webhooks/router.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: enhancement

#490 fix(integrations): Add missing display groups
  registry/tracecat_registry/integrations/checkpoint.py
  registry/tracecat_registry/integrations/limacharlie.py
  registry/tracecat_registry/integrations/microsoft_graph.py
  registry/tracecat_registry/integrations/wiz.py
Labels: fix

#492 chore+fix: Fix lint issues + remove unnecessary generics
  .pre-commit-config.yaml
  docker-compose.dev.yml
  pyproject.toml
  tracecat/dsl/action.py
  tracecat/dsl/client.py
  tracecat/dsl/common.py
  tracecat/dsl/io.py
  tracecat/dsl/models.py
  tracecat/dsl/scheduler.py
  tracecat/dsl/validation.py
  tracecat/dsl/view.py
  tracecat/dsl/workflow.py
  tracecat/expressions/core.py
  tracecat/expressions/parser/validator.py
  tracecat/registry/actions/models.py
  tracecat/registry/client.py
  tracecat/registry/executor.py
  tracecat/secrets/models.py
  tracecat/secrets/service.py
  tracecat/types/generics.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: internal

#493 fix: Add missing TemplateValidator to dynamic expectation models
  playbooks/tutorials/limacharlie/run_investigation.yml
  playbooks/tutorials/limacharlie/run_tests.yml
  tracecat/validation/common.py
Labels: frontend, engine, fix

#494 feat: Allow deletion of remote repository
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/registry/registry-repos-table.tsx
  tracecat/registry/repositories/router.py
  tracecat/registry/repositories/service.py
Labels: enhancement, frontend, engine

#440 feat(ui): Fuzzy selector node search
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/workbench/canvas/selector-node.tsx
Labels: enhancement, frontend

#495 refactor: Remove trigger inputs from schedules UI
  frontend/src/components/workbench/panel/trigger-panel.tsx
  tracecat/workflow/schedules/models.py
Labels: frontend, engine, internal

#499 feat(engine): Add traceback info and error kind to error messages
  tests/unit/test_workflows.py
  tracecat/expressions/core.py
  tracecat/expressions/parser/evaluator.py
  tracecat/registry/actions/models.py
  tracecat/registry/actions/router.py
  tracecat/registry/client.py
Labels: enhancement, engine

#501 fix(integrations): Incorrect `secrets` API usage in get token actions
  registry/tracecat_registry/integrations/checkpoint.py
  registry/tracecat_registry/integrations/limacharlie.py
  registry/tracecat_registry/integrations/microsoft_graph.py
  registry/tracecat_registry/integrations/wiz.py
Labels: integration, fix

#500 feat(integration): Support custom HTTP certs
  registry/tracecat_registry/base/core/http.py
Labels: enhancement, integration

#502 feat(ui): Improve action panel save
  frontend/src/components/workbench/panel/action-panel.tsx
Labels: enhancement, frontend

#508 feat+fix: Optional secrets
  docker-compose.prod.override.yml
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  registry/tracecat_registry/_internal/models.py
  registry/tracecat_registry/base/core/http.py
  tests/unit/test_sandbox.py
  tracecat/auth/sandbox.py
  tracecat/registry/executor.py
  tracecat/secrets/secrets_manager.py
  tracecat/validation/service.py
Labels: enhancement

#510 fix(ui): Properly handle registry action loading state in action panel
  frontend/src/components/workbench/panel/action-panel.tsx
Labels: frontend, fix

#504 feat+fix(integration): Check Point integration
  registry/tracecat_registry/integrations/checkpoint.py
  registry/tracecat_registry/templates/checkpoint/get_xdr_incidents.yml
  registry/tracecat_registry/templates/checkpoint/update_xdr_incident.yml
Labels: enhancement, integration, fix

#511 feat(ui): Break long words in schema table
  frontend/src/components/jsonschema-table.tsx
Labels: enhancement, frontend

#512 fix: Allow sourceHandle to be null for trigger
  tracecat/dsl/view.py
Labels: frontend, engine, fix

#509 feat: Enable multiple workflow entrypoints
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
  tests/unit/test_export.py
  tests/unit/test_workflows.py
  tracecat/dsl/common.py
  tracecat/dsl/scheduler.py
  tracecat/dsl/view.py
  tracecat/workflow/management/management.py
Labels: enhancement, frontend, engine

#514 fix(integration): Add sentinel value for LDAP connection attribute
  registry/tracecat_registry/integrations/ldap3.py
Labels: integration, fix

#513 ci(infra): Add SSO variables to terraform and increase API instance size
  deployments/aws/fargate/locals.tf
  deployments/aws/fargate/secrets.tf
  deployments/aws/fargate/variables.tf
  docs/img/self-hosting/env-script.png
  docs/img/self-hosting/sign-in.png
  docs/self-hosting/authentication/basic.mdx
  docs/self-hosting/authentication/introduction.mdx
  docs/self-hosting/authentication/okta.mdx
  docs/self-hosting/deployment-options/aws-ecs.mdx
  docs/self-hosting/deployment-options/docker-compose.mdx
  env.sh
Labels: internal, infrastructure, coderabbit

#517 feat: Add go to child workflow execution
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/[executionId]/page.tsx
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/executions/nav.tsx
  frontend/src/components/executions/section.tsx
  frontend/src/components/nav/workbench-nav.tsx
  registry/tracecat_registry/integrations/checkpoint.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
Labels: enhancement, frontend, engine

#519 feat+fix: Remove reliance on graph object data + improve node loading states
  frontend/src/components/ui/skeleton.tsx
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/canvas/canvas.tsx
  frontend/src/components/workbench/canvas/selector-node.tsx
  frontend/src/components/workbench/canvas/trigger-node.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
  frontend/src/components/workbench/panel/workbench-panel.tsx
  frontend/src/lib/hooks.tsx
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
  tracecat/dsl/common.py
  tracecat/dsl/view.py
Labels: enhancement

#516 feat(integration): Rename Secret Key for CrowdSec Integration
  registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
  registry/tracecat_registry/templates/wazuh/update_agents.yml
Labels: enhancement, integration, breaking

#520 feat(ui): Use skeleton for selector loading state
  frontend/src/components/workbench/canvas/selector-node.tsx
Labels: enhancement, frontend

#521 feat(ui): Add link to open child workflow from builder node
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/lib/workflow.ts
Labels: enhancement, frontend

#522 feat: Add go to parent workflow run
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
Labels: enhancement, frontend, engine

#526 feat(integration): Support basic auth in HTTP action
  registry/tracecat_registry/base/core/http.py
Labels: enhancement, integration

#530 feat(engine): Enable full jsonpath_ng syntax + remove jsonpath function expr
  pyproject.toml
  tests/unit/test_expressions.py
  tracecat/dsl/workflow.py
  tracecat/expressions/functions.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/grammar.py
  tracecat/expressions/parser/validator.py
Labels: enhancement, engine

#531 feat(engine): Update filter functions + delete build reference table
  registry/tracecat_registry/base/core/transform.py
  tests/data/workflows/unit_transform_filter_dict.yml
  tests/data/workflows/unit_transform_filter_function.yml
  tests/unit/test_expressions.py
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, engine

#532 feat: Promote first user to admin superuser + remove default admin user
  .env.example
  .github/workflows/test-python.yml
  docker-compose.dev.yml
  docker-compose.yml
  env.sh
  frontend/src/components/auth/sign-up.tsx
  pyproject.toml
  tests/conftest.py
  tracecat/api/app.py
  tracecat/auth/users.py
  tracecat/config.py
  tracecat/registry/client.py
Labels: enhancement, frontend, engine, coderabbit

#533 feat(ui): Update create secret tooltip
  frontend/src/components/organization/org-secret-create.tsx
  frontend/src/components/secrets/create-secret-tooltip.tsx
  frontend/src/components/workspaces/add-workspace-secret.tsx
Labels: enhancement, frontend

#525 fix(integration): Use unpadded base64url in VirusTotal integrations
  .github/workflows/test-python.yml
  docs/img/tutorials/actions-registry/registry.jpeg
  playbooks/tutorials/caldera/execute_operations.yml
  playbooks/tutorials/quickstart.yml
  playbooks/tutorials/virustotal_quickstart.yml
  registry/tracecat_registry/templates/virustotal/list_comments.yml
  registry/tracecat_registry/templates/virustotal/search_url.yml
  tests/playbooks/test_playbooks.py
  tracecat/expressions/functions.py
Labels: enhancement, fix

#523 fix(integration): Clashing crowdsec secret names and keys
  registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
Labels: fix

#498 feat(integration): Add update Wazuh agents action
  registry/tracecat_registry/templates/wazuh/update_agents.yml
Labels: enhancement, integration

#529 feat(integration): Crowdstrike incidents + combined Get Detects/Incident templates
  registry/tracecat_registry/templates/crowdstrike/get_detections.yml
  registry/tracecat_registry/templates/crowdstrike/get_incident_summaries.yml
  registry/tracecat_registry/templates/crowdstrike/get_incidents.yml
  registry/tracecat_registry/templates/crowdstrike/list_incidents.yml
Labels: enhancement

#534 feat(integration): Velociraptor integration
  registry/pyproject.toml
  registry/tracecat_registry/integrations/velociraptor.py
Labels: enhancement, integration

#536 feat(engine): Add json decode error handling
  tests/unit/test_expressions.py
  tracecat/registry/client.py
  tracecat/workflow/executions/service.py
Labels: enhancement, engine

#537 fix: Schedule run history issues
  frontend/src/components/executions/nav.tsx
  tracecat/workflow/executions/dependencies.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
Labels: frontend, engine, fix

#538 fix(integration): Incorrect key name in crowdsec and wazuh
  registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
  registry/tracecat_registry/templates/wazuh/update_agents.yml
Labels: fix

#524 feat(integration): Wazuh auth token getter
  registry/tracecat_registry/templates/wazuh/get_auth_token.yml
Labels: enhancement, integration

#535 feat(integrations): Add new string functions
  tracecat/expressions/functions.py
Labels: enhancement, integration

#540 refactor(engine): Reorganize functions
  tracecat/expressions/functions.py
Labels: engine, internal, refactor

#541 feat(integrations)!: Use MSAL for microsoft graph token flow
  pyproject.toml
  registry/tracecat_registry/integrations/microsoft_graph.py
Labels: enhancement, integration, breaking, coderabbit

#544 feat+ci(infra): Add temporal variables and logging patches from staging
  deployments/aws/fargate/locals.tf
  deployments/aws/fargate/variables.tf
  tracecat/config.py
  tracecat/workflow/executions/service.py
Labels: enhancement

#547 feat(engine): Lower log level and catch http timeout
  tracecat/auth/sandbox.py
  tracecat/registry/client.py
  tracecat/registry/executor.py
  tracecat/registry/loaders.py
Labels: enhancement, engine

#549 feat(engine): Replace jsonpath with lambda in intersect function
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, engine

#552 fix(ui): Add missing workflow states
  frontend/src/components/executions/nav.tsx
Labels: frontend, fix

#555 test: Replace pytest-asyncio with pytest-anyio
  pyproject.toml
  tests/conftest.py
  tests/playbooks/test_playbooks.py
  tests/registry/test_templates.py
  tests/unit/test_auth.py
  tests/unit/test_concurrency.py
  tests/unit/test_error_handling.py
  tests/unit/test_export.py
  tests/unit/test_expressions.py
  tests/unit/test_registry.py
  tests/unit/test_sandbox.py
  tests/unit/test_template_actions.py
  tests/unit/test_workflows.py
Labels: frontend, engine, internal

#554 feat(ui): Add polling for workflow runs history
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/layout.tsx
  frontend/src/lib/hooks.tsx
Labels: enhancement, frontend

#564 refactor(integration): Consistent naming in VirusTotal list_comments template
  registry/tracecat_registry/templates/virustotal/list_comments.yml
Labels: integration, internal, refactor

#561 feat(integration): Add Datadog list alerts and aggregate events
  registry/tracecat_registry/templates/datadog/aggregate_events.yml
  registry/tracecat_registry/templates/datadog/list_alerts.yml
Labels: enhancement, integration

#560 feat(integration): Support HTML content type in SMTP email action
  registry/pyproject.toml
  registry/tracecat_registry/base/core/email.py
Labels: enhancement, integration, coderabbit

#570 feat!(engine): Stronger ACLs
  tracecat/api/routers/users.py
  tracecat/auth/credentials.py
  tracecat/auth/dependencies.py
  tracecat/registry/actions/router.py
  tracecat/registry/repositories/router.py
  tracecat/secrets/router.py
  tracecat/workspaces/router.py
Labels: enhancement

#571 fix(engine): Add additional optionality for workspace id in role acl …
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  tracecat/api/routers/users.py
  tracecat/auth/credentials.py
  tracecat/registry/actions/router.py
  tracecat/registry/repositories/router.py
  tracecat/secrets/router.py
  tracecat/workspaces/router.py
Labels: engine, fix

#572 refactor(engine): Consolidate and cleanup role acl dependencies
  tracecat/auth/credentials.py
  tracecat/auth/dependencies.py
  tracecat/testing/registry.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/management/router.py
Labels: engine, internal

#569 feat(integration): rootcheck wazuh
  registry/tracecat_registry/templates/wazuh/clear_rootcheck.yml
  registry/tracecat_registry/templates/wazuh/get_last_scan_rootcheck.yml
  registry/tracecat_registry/templates/wazuh/run_rootcheck.yml
Labels: enhancement, integration

#575 feat: Organization users management
  frontend/src/app/organization/members/page.tsx
  frontend/src/app/organization/sidebar-nav.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-members-table.tsx
  frontend/src/components/table/table.tsx
  frontend/src/lib/auth.ts
  frontend/src/lib/hooks.tsx
  tracecat/api/app.py
  tracecat/auth/router.py
  tracecat/organization/__init__.py
  tracecat/organization/models.py
  tracecat/organization/router.py
  tracecat/organization/service.py
  tracecat/service.py
Labels: enhancement, frontend, engine, coderabbit
