Repository TracecatHQ/tracecat, pull requests merged in 2024-06, with the labels that each got.

#148 feat: Implement server side schema validation and JSON editor
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/jsonschema-table.tsx
  frontend/src/components/notifications.tsx
  frontend/src/components/workspace/canvas/action-node.tsx
  frontend/src/components/workspace/canvas/canvas.tsx
  frontend/src/components/workspace/canvas/udf-node.tsx
  frontend/src/components/workspace/catalog/action-catalog.tsx
  frontend/src/components/workspace/panel/action/form.tsx
  frontend/src/components/workspace/panel/action/schemas.tsx
  frontend/src/components/workspace/panel/action/udf-form.tsx
  frontend/src/components/workspace/panel/common.tsx
  frontend/src/components/workspace/panel/udf-form.tsx
  frontend/src/components/workspace/panel/workflow/controls.tsx
  frontend/src/components/workspace/panel/workspace-panel.tsx
  frontend/src/components/workspace/workspace.tsx
  frontend/src/lib/flow.ts
  frontend/src/lib/hooks.ts
  frontend/src/lib/jsonschema.ts
  frontend/src/lib/udf.ts
  frontend/src/providers/builder.tsx
  frontend/tests/jsonschema.test.ts
  frontend/tests/udf.test.ts
  tests/unit/test_registry.py
  tests/unit/test_template_expressions.py
  tracecat/actions/core/http.py
  tracecat/api/app.py
  tracecat/cli/workflow.py
  tracecat/registry.py
  tracecat/templates/__init__.py
  tracecat/templates/expressions.py
  tracecat/templates/patterns.py
  tracecat/templates/validators.py
  tracecat/types/api.py
  tracecat/types/exceptions.py
Labels: enhancement

#149 feat: Implement commit changes to workflow
  frontend/src/components/console/event-feed.tsx
  frontend/src/components/dashboard/create-workflow-button.tsx
  frontend/src/components/dashboard/workflows-dashboard.tsx
  frontend/src/components/nav/workflow-nav.tsx
  frontend/src/components/playbooks/workflows-dashboard.tsx
  frontend/src/components/workspace/canvas/canvas.tsx
  frontend/src/components/workspace/catalog/action-catalog.tsx
  frontend/src/components/workspace/panel/workflow/controls.tsx
  frontend/src/components/workspace/panel/workflow/form.tsx
  frontend/src/components/workspace/panel/workflow/runs.tsx
  frontend/src/components/workspace/panel/workflow/settings.tsx
  frontend/src/lib/hooks.ts
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
  frontend/src/providers/workflow.tsx
  tracecat/api/app.py
  tracecat/dsl/graph.py
  tracecat/dsl/workflow.py
Labels: enhancement, frontend, engine

#150 feat(ui): Consolidate action catalog
  frontend/src/components/icons.tsx
  frontend/src/components/workspace/canvas/canvas.tsx
  frontend/src/components/workspace/canvas/udf-node.tsx
  frontend/src/components/workspace/catalog/action-catalog.tsx
  frontend/src/components/workspace/catalog/action-tiles-schema.ts
  frontend/src/components/workspace/catalog/udfs-catalog.tsx
  frontend/src/components/workspace/panel/action/udf-form.tsx
  frontend/src/components/workspace/workspace.tsx
  frontend/src/lib/udf.ts
  tracecat/actions/__init__.py
  tracecat/actions/core/cases.py
  tracecat/actions/core/condition.py
  tracecat/actions/core/email.py
  tracecat/actions/core/http.py
  tracecat/actions/core/llm.py
  tracecat/api/app.py
Labels: enhancement, frontend, engine

#151 feat: Add and improve triggers UI
  frontend/src/components/console/control-panel.tsx
  frontend/src/components/icons.tsx
  frontend/src/components/nav/workflow-nav.tsx
  frontend/src/components/workspace/canvas/canvas.tsx
  frontend/src/components/workspace/canvas/custom-handle.tsx
  frontend/src/components/workspace/canvas/trigger-node.tsx
  frontend/src/components/workspace/catalog/catalog.tsx
  frontend/src/components/workspace/catalog/trigger-catalog.tsx
  frontend/src/components/workspace/panel/trigger-panel.tsx
  frontend/src/components/workspace/panel/workflow/controls.tsx
  frontend/src/components/workspace/panel/workflow/form.tsx
  frontend/src/components/workspace/panel/workspace-panel.tsx
  frontend/src/components/workspace/workspace.tsx
  frontend/src/lib/hooks.ts
  frontend/src/lib/trigger.ts
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
  frontend/src/providers/cases.tsx
  frontend/src/providers/event-feed-stream.tsx
  frontend/src/providers/workflow.tsx
  frontend/src/types/schemas.ts
  pyproject.toml
  tracecat/api/app.py
  tracecat/db/converters.py
  tracecat/db/schemas.py
  tracecat/dsl/graph.py
  tracecat/logging/__init__.py
  tracecat/logging/_logger.py
  tracecat/logging/config.py
  tracecat/types/api.py
  tracecat/types/exceptions.py
Labels: enhancement

#154 feat(engine): Implement template expression functions
  tests/unit/test_template_expressions.py
  tracecat/templates/expressions.py
  tracecat/templates/patterns.py
Labels: enhancement, engine

#159 docs: Update installation section
  docs/installation.mdx
Labels: documentation, frontend, engine

#161 docs: Updated VT quickstart
  docs/quickstart.mdx
Labels: documentation

#162 docs: Update docs concepts [1/N]
  docs/concepts/actions.mdx
  docs/concepts/case-management.mdx
  docs/concepts/expressions.mdx
  docs/concepts/schedules.mdx
  docs/concepts/secrets.mdx
  docs/concepts/user-defined-functions.mdx
  docs/concepts/user-interface.mdx
  docs/concepts/webhooks.mdx
  docs/concepts/workflow-definitions.mdx
  docs/concepts/workflows.mdx
  docs/core/ai-features.mdx
  docs/gd_slack_quickstart.mdx
  docs/mint.json
  docs/tutorials/actions-tutorial.mdx
  docs/tutorials/phishing.mdx
  docs/tutorials/workflows-tutorial.mdx
Labels: documentation, frontend, engine

#165 feat(engine): Add data transform forward action
  tracecat/actions/__init__.py
  tracecat/actions/core/transform.py
Labels: enhancement, engine

#168 feat(engine): Implement action-local `var` context + iterable `for_each` clause
  tests/data/workflows/unit_transform_forwarder_loop.yml
  tests/data/workflows/unit_transform_forwarder_loop_expected.yml
  tests/unit/test_expressions.py
  tests/unit/test_workflows.py
  tracecat/dsl/workflow.py
  tracecat/expressions/__init__.py
  tracecat/expressions/engine.py
  tracecat/expressions/eval.py
  tracecat/registry.py
Labels: enhancement, engine

#171 feat(engine): Implement for_each zip expression
  tests/data/workflows/unit_transform_forwarder_zip.yml
  tests/data/workflows/unit_transform_forwarder_zip_expected.yml
  tests/unit/test_workflows.py
  tracecat/dsl/common.py
  tracecat/dsl/workflow.py
  tracecat/expressions/engine.py
Labels: enhancement, engine

#176 feat(engine): Dynamically register UDFs in DSLActivities
  tests/unit/test_workflows.py
  tracecat/dsl/worker.py
  tracecat/dsl/workflow.py
Labels: enhancement, engine

#175 build: Make docker compose prod and add dev extension
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/Dockerfile.prod
  frontend/next.config.mjs
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/layout.tsx
  frontend/src/app/playbooks/layout.tsx
  frontend/src/app/playbooks/page.tsx
  frontend/src/app/workflows/page.tsx
  frontend/src/components/auth-disabled.tsx
  frontend/src/components/aux-click-menu.tsx
  frontend/src/components/badges.tsx
  frontend/src/components/cases/data/cases.json
  frontend/src/components/cases/table.tsx
  frontend/src/components/dashboard/workflows-dashboard.tsx
  frontend/src/components/decorated-header.tsx
  frontend/src/components/error.tsx
  frontend/src/components/events/data/schema.ts
  frontend/src/components/icons.tsx
  frontend/src/components/jsonschema-table.tsx
  frontend/src/components/nav/dynamic-nav.tsx
  frontend/src/components/nav/navbar.tsx
  frontend/src/components/nav/user-nav.tsx
  frontend/src/components/new-credential-dialog.tsx
  frontend/src/components/no-ssr.tsx
  frontend/src/components/playbooks/workflows-dashboard.tsx
  frontend/src/components/table/table.tsx
  frontend/src/components/ui/alert-dialog.tsx
  frontend/src/components/ui/command.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/scroll-area.tsx
  frontend/src/components/workspace/canvas/canvas.tsx
  frontend/src/components/workspace/canvas/custom-handle.tsx
  frontend/src/components/workspace/canvas/trigger-node.tsx
  frontend/src/components/workspace/catalog/udf-catalog.tsx
  frontend/src/components/workspace/panel/trigger-panel.tsx
  frontend/src/components/workspace/panel/udf-panel.tsx
  frontend/src/components/workspace/panel/workspace-panel.tsx
  frontend/src/lib/api.ts
  frontend/src/lib/hooks.ts
  frontend/src/lib/jsonschema.ts
  frontend/src/lib/onboarding.ts
  frontend/src/lib/utils.ts
  frontend/src/lib/workflow.ts
  frontend/src/providers/case-panel.tsx
  frontend/src/providers/posthog.tsx
  frontend/src/providers/workflow.tsx
  frontend/src/styles/globals.css
  frontend/tests/utils.test.ts
  frontend/tsconfig.json
  tracecat/db/engine.py
Labels: frontend, engine, build

#179 feat(engine): Implement server-side UDF args validation on commit
  docs/openapi.yml
  tracecat/api/app.py
  tracecat/cli/workflow.py
  tracecat/dsl/common.py
  tracecat/registry.py
  tracecat/types/api.py
Labels: enhancement, engine

#170 feat(playbook): Tag Slack users in Datadog security signal
  playbooks/datadog/tag-slack-users.yml
Labels: enhancement, playbooks

#177 ci: Add python tests suite
  .github/workflows/build-push-images.yml
  .github/workflows/tests.yml
  README.md
  docker-compose.dev.yml
  docker-compose.yml
  env.sh
  tests/data/actions.csv
  tests/data/trigger_payloads.ndjson
  tests/data/webhooks.csv
  tests/data/workflows.csv
Labels: tests, cicd

#180 ci: Add draft GH workflow to test all playbooks
  .github/release-drafter.yml
  .github/workflows/playbooks.yml
  .github/workflows/tests.yml
  playbooks/alert_management/aws-guardduty-to-slack.yml
  playbooks/alert_management/datadog-siem-to-slack.yml
  tests/integration/test_playbooks.py
  tracecat/cli/_config.py
Labels: frontend, engine, tests, cicd, internal

#181 feat(cli): Enable webhook trigger without ingress tunnel
  tracecat/cli/workflow.py
Labels: enhancement, internal

#185 docs: update README.md
  README.md
Labels: documentation, frontend, engine

#184 build: Add Temporal to docker-compose.yml and fix host.docker.internal
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
  temporal/config/tracecat-sql.yaml
  tests/conftest.py
Labels: frontend, engine, build

#186 ci: Add ui to ghcr and entrypoint to cli
  .env.example
  .github/workflows/build-push-images.yml
  .github/workflows/tests.yml
  Dockerfile
  tests/unit/test_cli.py
  tracecat/cli/_config.py
Labels: frontend, engine, cicd, internal

#188 refactor(engine): Move Role class to types
  tests/conftest.py
  tests/unit/test_auth.py
  tests/unit/test_sandbox.py
  tracecat/api/app.py
  tracecat/auth/clients.py
  tracecat/auth/credentials.py
  tracecat/auth/sandbox.py
  tracecat/cli/_config.py
  tracecat/contexts.py
  tracecat/db/helpers.py
  tracecat/dsl/workflow.py
  tracecat/types/auth.py
Labels: engine, internal

#189 feat(engine): Create default user in headless mode on db start
  .github/workflows/tests.yml
  tests/unit/test_cli.py
  tracecat/cli/workflow.py
  tracecat/db/engine.py
Labels: enhancement, engine

#190 revert: Build ui image locally in docker compose
  .github/workflows/build-push-images.yml
  .github/workflows/test-pnpm-build.yml
  .github/workflows/test-python.yml
  docker-compose.yml
  frontend/Dockerfile.prod
  frontend/src/app/playbooks/page.tsx
  frontend/src/components/dashboard/workflows-dashboard.tsx
  frontend/src/components/playbooks/workflows-dashboard.tsx
  frontend/src/components/skeletons.tsx
  frontend/src/lib/hooks.ts
  frontend/src/lib/workflow.ts
Labels: cicd, fix, internal

#192 feat(integration): Add email and ipv4 extractors
  tests/unit/integrations/test_extraction.py
  tracecat/actions/integrations/extraction/__init__.py
  tracecat/actions/integrations/extraction/email.py
  tracecat/actions/integrations/extraction/ip_address.py
Labels: enhancement, integration

#193 feat(integration): Add database writer
  pyproject.toml
  tests/unit/integrations/test_sinks.py
  tracecat/actions/integrations/sinks/__init__.py
  tracecat/actions/integrations/sinks/database.py
Labels: enhancement, integration

#195 feat(integration)!: Categorize by tooling and register secrets
  tests/unit/integrations/test_extraction.py
  tracecat/actions/etl/extraction/__init__.py
  tracecat/actions/etl/extraction/email.py
  tracecat/actions/etl/extraction/ip_address.py
  tracecat/actions/integrations/__init__.py
  tracecat/actions/integrations/cdr/__init__.py
  tracecat/actions/integrations/cdr/amazon_guardduty.py
  tracecat/actions/integrations/cdr/microsoft_defender.py
  tracecat/actions/integrations/cdr/wiz.py
  tracecat/actions/integrations/edr/__init__.py
  tracecat/actions/integrations/edr/crowdstrike.py
  tracecat/actions/integrations/edr/microsoft_defender.py
  tracecat/actions/integrations/edr/sentinel_one.py
  tracecat/actions/integrations/enrichment/abuseipdb.py
  tracecat/actions/integrations/enrichment/alienvault.py
  tracecat/actions/integrations/enrichment/emailrep.py
  tracecat/actions/integrations/enrichment/hybrid_analysis.py
  tracecat/actions/integrations/enrichment/malwarebazaar.py
  tracecat/actions/integrations/enrichment/pulsedive.py
  tracecat/actions/integrations/enrichment/urlscan.py
  tracecat/actions/integrations/enrichment/virustotal.py
  tracecat/actions/integrations/siem/datadog.py
  tracecat/actions/integrations/siem/elastic.py
Labels: enhancement, integration, breaking

#197 feat(engine): Use TracecatDSLError in DSL validation
  tracecat/dsl/common.py
  tracecat/types/exceptions.py
Labels: enhancement, engine

#196 feat+docs: Generate udf integration docs
  docs/integrations/introduction.mdx
  docs/integrations/udfs/core_ai_extract.mdx
  docs/integrations/udfs/core_ai_label.mdx
  docs/integrations/udfs/core_ai_summarize.mdx
  docs/integrations/udfs/core_ai_translate.mdx
  docs/integrations/udfs/core_condition_compare.mdx
  docs/integrations/udfs/core_condition_membership.mdx
  docs/integrations/udfs/core_condition_regex.mdx
  docs/integrations/udfs/core_extraction_extract_emails.mdx
  docs/integrations/udfs/core_http_request.mdx
  docs/integrations/udfs/core_open_case.mdx
  docs/integrations/udfs/core_send_email.mdx
  docs/integrations/udfs/core_transform_forward.mdx
  docs/integrations/udfs/integrations_aws_guardduty_list_guardduty_alerts.mdx
  docs/integrations/udfs/integrations_chat_slack_list_slack_users.mdx
  docs/integrations/udfs/integrations_chat_slack_post_slack_message.mdx
  docs/integrations/udfs/integrations_crowdstrike_list_crowdstrike_alerts.mdx
  docs/integrations/udfs/integrations_crowdstrike_list_crowdstrike_detects.mdx
  docs/integrations/udfs/integrations_crowdstrike_update_crowdstrike_alert_status.mdx
  docs/integrations/udfs/integrations_crowdstrike_update_crowdstrike_detect_status.mdx
  docs/integrations/udfs/integrations_datadog_list_datadog_alerts.mdx
  docs/integrations/udfs/integrations_elastic_list_elastic_alerts.mdx
  docs/integrations/udfs/integrations_extraction_extract_ipv4_addresses.mdx
  docs/integrations/udfs/integrations_microsoft_defender_list_defender_cloud_alerts.mdx
  docs/integrations/udfs/integrations_microsoft_defender_list_defender_endpoint_alerts.mdx
  docs/integrations/udfs/integrations_sentinel_one_list_sentinelone_alerts.mdx
  docs/integrations/udfs/integrations_sentinel_one_update_sentinelone_alert_status.mdx
  docs/integrations/udfs/integrations_sinks_write_to_database.mdx
  docs/integrations/udfs/integrations_virustotal_analyze_ip_address.mdx
  docs/integrations/udfs/integrations_virustotal_analyze_malware_sample.mdx
  docs/integrations/udfs/integrations_virustotal_analyze_url.mdx
  docs/integrations/udfs/integrations_wiz_list_wiz_alerts.mdx
  docs/mint.json
  tracecat/actions/core/example.py
  tracecat/actions/integrations/chat/slack.py
  tracecat/cli/dev.py
Labels: documentation, enhancement

#199 feat(playbook): Crowdstrike distributed alerting in Slack
  playbooks/alert_management/crowdstrike-to-cases.yml
  playbooks/alert_management/slack-to-crowdstrike-update.yml
  tracecat/actions/integrations/edr/__init__.py
Labels: enhancement, playbooks

#198 feat(playbook): Sentinel One distributed alerting in Slack
  playbooks/alert_management/sentinel-one-to-slack.yml
  playbooks/alert_management/slack-to-sentinel-one-update.yml
Labels: enhancement, playbooks

#200 ci: Configure logger verbosity
  .github/workflows/playbooks.yml
  .github/workflows/test-python.yml
  tracecat/logging/_logger.py
Labels: frontend, engine, internal

#201 feat(cli): Add --commit flag in tracecat workflow create
  tests/unit/test_cli.py
  tracecat/cli/workflow.py
Labels: enhancement

#202 feat(udf): Update AI action
  frontend/src/components/icons.tsx
  tracecat/actions/core/llm.py
  tracecat/api/completions.py
  tracecat/llm.py
Labels: enhancement

#204 feat(engine): Trigger context handling + webhook integration test
  tests/data/workflows/integration_webhook_concat.yml
  tests/integration/test_webhook.py
  tests/unit/test_expressions.py
  tracecat/expressions/engine.py
  tracecat/expressions/patterns.py
Labels: enhancement, engine

#205 fix+test: Add integration test for AI action
  tests/data/workflows/integration_core_ai_action.yml
  tracecat/actions/core/llm.py
Labels: tests, fix

#207 feat(integration): Shodan analyze URL / ip address
  pyproject.toml
  tracecat/actions/integrations/enrichment/shodan.py
Labels: enhancement, integration

#203 wip(playbook): Fix playbook tests in GH workflows
  .github/workflows/test-python.yml
  .github/workflows/test.yml
  playbooks/alert_management/aws-guardduty-to-slack.yml
  playbooks/alert_management/datadog-extract-email-to-slack.yml
  playbooks/alert_management/datadog-to-cases.yml
  playbooks/threat_intel/virustotal-to-email.yml
  tests/integration/test_playbooks.py
  tracecat/actions/etl/extraction/ip_address.py
  tracecat/actions/integrations/siem/datadog.py
Labels: cicd, playbooks, internal

#211 feat: CS-slack sync working
  playbooks/alert_management/crowdstrike-to-cases.yml
  playbooks/alert_management/slack-to-crowdstrike-update.yml
  tests/data/log_samples/crowdstrike/alert.json
  tracecat/api/app.py
  tracecat/dsl/common.py
  tracecat/expressions/functions.py
  tracecat/parse.py
  tracecat/types/api.py
Labels: enhancement, frontend, engine

#213 test: Fix flaky `workflow_id` parse in playbooks test
  .github/workflows/test.yml
  playbooks/alert_management/aws-guardduty-to-cases.yml
  tests/integration/test_playbooks.py
Labels: frontend, engine, tests, internal

#215 build: Remove elasticsearch
  .github/workflows/test.yml
  docker-compose.yml
Labels: frontend, engine, build

#214 feat(engine): Implement schedules
  frontend/src/components/workspace/canvas/trigger-node.tsx
  frontend/src/components/workspace/panel/trigger-panel.tsx
  frontend/src/types/schemas.ts
  playbooks/alert_management/aws-guardduty-to-slack.yml
  tracecat/api/app.py
  tracecat/auth/credentials.py
  tracecat/cli/_utils.py
  tracecat/cli/dev.py
  tracecat/cli/main.py
  tracecat/cli/schedule.py
  tracecat/cli/workflow.py
  tracecat/config.py
  tracecat/contexts.py
  tracecat/db/schemas.py
  tracecat/dsl/dispatcher.py
  tracecat/dsl/schedules.py
  tracecat/dsl/workflow.py
  tracecat/identifiers/__init__.py
  tracecat/identifiers/schedules.py
  tracecat/identifiers/workflow.py
  tracecat/types/api.py
Labels: enhancement, engine

#217 feat(engine): Improve missing secrets visibility in AuthSandbox
  tests/unit/test_sandbox.py
  tracecat/auth/sandbox.py
  tracecat/concurrency.py
Labels: enhancement, engine

#219 feat(udf): Improve registry secrets api
  tracecat/actions/core/email.py
  tracecat/actions/core/llm.py
  tracecat/actions/integrations/cdr/amazon_guardduty.py
  tracecat/actions/integrations/cdr/microsoft_defender.py
  tracecat/actions/integrations/cdr/wiz.py
  tracecat/actions/integrations/chat/slack.py
  tracecat/actions/integrations/edr/crowdstrike.py
  tracecat/actions/integrations/edr/microsoft_defender.py
  tracecat/actions/integrations/edr/sentinel_one.py
  tracecat/actions/integrations/enrichment/abuseipdb.py
  tracecat/actions/integrations/enrichment/alienvault.py
  tracecat/actions/integrations/enrichment/censys.py
  tracecat/actions/integrations/enrichment/emailrep.py
  tracecat/actions/integrations/enrichment/hybrid_analysis.py
  tracecat/actions/integrations/enrichment/malwarebazaar.py
  tracecat/actions/integrations/enrichment/pulsedive.py
  tracecat/actions/integrations/enrichment/shodan.py
  tracecat/actions/integrations/enrichment/urlscan.py
  tracecat/actions/integrations/enrichment/virustotal.py
  tracecat/actions/integrations/siem/datadog.py
  tracecat/actions/integrations/siem/elastic.py
  tracecat/registry.py
  tracecat/types/secrets.py
Labels: enhancement

#221 feat(engine): Make registry metadata a TypedDict
  tracecat/registry.py
Labels: enhancement, engine
