Repository TracecatHQ/tracecat, pull requests merged in 2025-10, with the labels that each got.

#1480 feat(ui): Add Microsoft / github / slackbot icons
  docs/cheatsheets/integrations.mdx
  frontend/src/components/icons.tsx
Labels: ui

#1483 fix(integrations): Deserialize bjson objects in pymongo returns
  packages/tracecat-registry/tracecat_registry/integrations/pymongo.py
Labels: enhancement, integrations

#1485 chore: Improve OpenAPI client generation for CI
  .pre-commit-config.yaml
  frontend/package.json
  frontend/src/client/schemas.gen.ts
  justfile
  scripts/generate-openapi.py
Labels: cicd, build

#1486 fix(api): Non-atomic case creation logic
  tests/registry/test_core_cases.py
  tests/unit/test_case_fields_integration.py
  tests/unit/test_cases_service.py
  tests/unit/test_tables_service.py
  tracecat/cases/models.py
  tracecat/cases/records/service.py
  tracecat/cases/service.py
  tracecat/tables/common.py
Labels: fix, api

#1488 feat(functions): Add new Markdown formatting functions
  docs/cheatsheets/functions.mdx
  tracecat/expressions/formatters.py
  tracecat/expressions/functions.py
Labels: enhancement, functions

#1492 feat(ui): Bulk case actions
  frontend/pnpm-lock.yaml
  frontend/src/app/workspaces/layout.tsx
  frontend/src/components/cases/case-selection-context.tsx
  frontend/src/components/cases/case-table-filters.tsx
  frontend/src/components/cases/case-table.tsx
  frontend/src/components/nav/controls-header.tsx
  frontend/src/components/ui/button-group.tsx
Labels: ui

#1497 feat(ui): Add multi-select case tags view
  frontend/src/app/workspaces/[workspaceId]/cases/page.tsx
  frontend/src/components/cases/case-table.tsx
  frontend/src/components/cases/case-tags-sidebar.tsx
  frontend/src/components/cases/cases-view-toggle.tsx
  frontend/src/components/nav/controls-header.tsx
Labels: ui

#1498 fix: Use OrganizationUserRole for agent model/provider endpoints
  tracecat/agent/router.py
Labels: fix, refactor

#1501 fix(agent): Regression bug in non-str output type
  packages/tracecat-registry/tracecat_registry/core/agent.py
  tests/conftest.py
  tests/registry/test_agent.py
  tracecat/agent/parsers.py
  tracecat/agent/runtime.py
Labels: fix, agents

#1502 feat(integrations): Add verify_ssl to elastic integrations
  packages/tracecat-registry/tracecat_registry/templates/tools/elastic_security/list_detection_signals.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/elasticsearch/get_index_template.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/elasticsearch/get_mapping.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/elasticsearch/list_aliases.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/elasticsearch/list_indices.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/elasticsearch/search_events.yml
Labels: enhancement, integrations
