Repository TracecatHQ/tracecat, pull requests merged in 2025-03, with the labels that each got.

#905 fix(engine): Use stable ssh key file name
  tests/unit/test_executor_service.py
  tracecat/executor/service.py
  tracecat/ssh.py
Labels: engine, fix

#921 feat(functions)!: Add defanged and fanged IoC extractors
  pyproject.toml
  registry/tracecat_registry/base/core/http.py
  registry/tracecat_registry/base/etl/email.py
  registry/tracecat_registry/base/etl/ip_address.py
  registry/tracecat_registry/base/etl/url.py
  tests/data/iocs/asn.yml
  tests/data/iocs/cve.yml
  tests/data/iocs/defanged/domain.yml
  tests/data/iocs/defanged/ipv4.yml
  tests/data/iocs/defanged/ipv6.yml
  tests/data/iocs/defanged/url.yml
  tests/data/iocs/domain.yml
  tests/data/iocs/email.yml
  tests/data/iocs/ipv4.yml
  tests/data/iocs/ipv6.yml
  tests/data/iocs/mac.yml
  tests/data/iocs/md5.yml
  tests/data/iocs/sha1.yml
  tests/data/iocs/sha256.yml
  tests/data/iocs/sha512.yml
  tests/data/iocs/url_any.yml
  tests/data/iocs/url_http.yml
  tests/registry/test_extraction.py
  tests/unit/test_functions.py
  tests/unit/test_ioc_extractors.py
  tracecat/expressions/ioc_extractors/__init__.py
  tracecat/expressions/ioc_extractors/asn.py
  tracecat/expressions/ioc_extractors/cve.py
  tracecat/expressions/ioc_extractors/domain.py
  tracecat/expressions/ioc_extractors/email.py
  tracecat/expressions/ioc_extractors/hash.py
  tracecat/expressions/ioc_extractors/ip.py
  tracecat/expressions/ioc_extractors/mac.py
  tracecat/expressions/ioc_extractors/url.py
Labels: enhancement, functions

#911 feat(integrations): Wazuh update agents and active response
  registry/tracecat_registry/integrations/wazuh.py
  registry/tracecat_registry/templates/harden/update_agents/wazuh.yml
  registry/tracecat_registry/templates/tools/wazuh/active_response.yml
Labels: enhancement, integrations

#924 fix(ui): Prevent trackpad overscroll on macos
  frontend/src/styles/globals.css
Labels: frontend, fix

#926 feat(ui): Add icon for `core.http_poll`
  frontend/src/components/icons.tsx
Labels: frontend

#927 build: Frontend dockerfile cmd json args
  frontend/Dockerfile.prod
Labels: build

#928 feat(ui): Add icon for `core.require`
  frontend/src/components/icons.tsx
Labels: frontend

#925 feat(integrations)!: Break LLM calls into individual providers
  .env.example
  .github/workflows/test-python.yml
  docs/quickstart/core-actions.mdx
  docs/tutorials/custom-integrations.mdx
  pyproject.toml
  registry/tracecat_registry/base/__init__.py
  registry/tracecat_registry/base/core/llm.py
  registry/tracecat_registry/core/email.py
  registry/tracecat_registry/core/http.py
  registry/tracecat_registry/core/require.py
  registry/tracecat_registry/core/table.py
  registry/tracecat_registry/core/transform.py
  registry/tracecat_registry/core/workflow.py
  registry/tracecat_registry/llm/ollama.py
  registry/tracecat_registry/llm/openai.py
  tests/registry/test_core_http.py
  tests/registry/test_core_require.py
  tests/registry/test_core_transform.py
  tests/unit/test_llms.py
  tracecat/llm.py
  tracecat/llm/__init__.py
  tracecat/llm/ollama.py
  tracecat/llm/openai.py
Labels: integrations, breaking

#930 test: Add more skip logic for local testing and disable failing llm tests
  tests/unit/test_llms.py
Labels: tests, fix

#923 feat(core): Add lookup multiple rows action
  registry/tracecat_registry/core/table.py
  tests/unit/test_tables_service.py
  tests/unit/test_workflows.py
  tracecat/tables/service.py
Labels: enhancement

#934 feat(app): Clean up webhooks module
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/workbench/canvas/trigger-node.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
  frontend/src/lib/hooks.tsx
  tracecat/webhooks/dependencies.py
  tracecat/webhooks/models.py
  tracecat/webhooks/router.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: engine

#932 feat(integrations+ee): Enterprise `podman run` action
  .env.example
  .github/workflows/test-python.yml
  Dockerfile
  Dockerfile.dev
  docker-compose.dev.yml
  docker-compose.yml
  podman/Dockerfile
  pyproject.toml
  registry/tracecat_registry/ee/podman.py
  scripts/install-packages.sh
  tests/conftest.py
  tests/unit/test_podman.py
  tracecat/config.py
  tracecat/sandbox/podman.py
Labels: enhancement, integrations

#940 feat(integrations): Split logs in podman runner to stdout and stderr
  registry/tracecat_registry/ee/podman.py
  tests/unit/test_podman.py
  tracecat/ee/sandbox/podman.py
Labels: enhancement, integrations

#935 feat(app): Allow editing of existing keys
  frontend/src/components/organization/org-secret-update.tsx
  frontend/src/components/workspaces/edit-workspace-secret.tsx
  tests/unit/test_secrets_service.py
  tracecat/secrets/service.py
Labels: enhancement, fix, api

#942 deps(ui): Drop unused frontend deps + bump pnpm to 10.6.3
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/jsonschema-table.tsx
  frontend/src/components/ui/drawer.tsx
Labels: dependencies

#943 deps(ui): Upgrade React Flow to 12.4.4
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/workspaces/layout.tsx
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/canvas/canvas.tsx
  frontend/src/components/workbench/canvas/custom-handle.tsx
  frontend/src/components/workbench/canvas/selector-node.tsx
  frontend/src/components/workbench/canvas/trigger-node.tsx
  frontend/src/components/workbench/panel/workbench-panel.tsx
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
Labels: dependencies

#941 build: Standardize handling of Temporal server image
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
Labels: build

#946 test: Add podman pytest mark
  .github/workflows/test-python.yml
  pyproject.toml
  tests/unit/test_podman.py
Labels: tests

#933 feat(engine+ui): Implement basic interactions
  alembic/versions/9039a443701d_add_interactivity_to_action.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/executions/event-history.tsx
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/events/events-sidebar-interactions.tsx
  frontend/src/components/workbench/events/events-sidebar.tsx
  frontend/src/components/workbench/events/events-workflow.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/lib/event-history.ts
  registry/tracecat_registry/templates/notify/post_notification/slack.yml
  tests/unit/test_interactions.py
  tracecat/contexts.py
  tracecat/db/schemas.py
  tracecat/dsl/common.py
  tracecat/dsl/enums.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/ee/__init__.py
  tracecat/ee/enums.py
  tracecat/ee/interactions/__init__.py
  tracecat/ee/interactions/connectors.py
  tracecat/ee/interactions/decorators.py
  tracecat/ee/interactions/enums.py
  tracecat/ee/interactions/models.py
  tracecat/ee/interactions/service.py
  tracecat/executor/service.py
  tracecat/expressions/functions.py
  tracecat/validation/service.py
  tracecat/webhooks/dependencies.py
  tracecat/webhooks/router.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/actions/router.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/enums.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
Labels: enhancement, engine

#949 feat(engine): Support expressions in dictionary keys
  tests/unit/test_expressions.py
  tracecat/expressions/eval.py
Labels: enhancement, engine

#950 feat(integrations): Add LLM `extract_one`, `extract_many`, and `summarize`
  .env.example
  .github/workflows/test-python.yml
  pyproject.toml
  registry/tracecat_registry/llm/ollama.py
  registry/tracecat_registry/llm/openai.py
  registry/tracecat_registry/templates/llm/extract_data/ollama.yml
  registry/tracecat_registry/templates/llm/extract_data/openai.yml
  registry/tracecat_registry/templates/llm/extract_many/ollama.yml
  registry/tracecat_registry/templates/llm/extract_many/openai.yml
  registry/tracecat_registry/templates/llm/extract_one/ollama.yml
  registry/tracecat_registry/templates/llm/extract_one/openai.yml
  registry/tracecat_registry/templates/llm/summarize/ollama.yml
  registry/tracecat_registry/templates/llm/summarize/openai.yml
  registry/tracecat_registry/templates/llm/title/ollama.yml
  registry/tracecat_registry/templates/llm/title/openai.yml
  tests/conftest.py
  tests/llm/test_providers.py
  tests/llm/test_template_actions.py
  tests/shared.py
  tests/unit/test_formatters.py
  tests/unit/test_functions.py
  tracecat/api/common.py
  tracecat/expressions/formatters.py
  tracecat/expressions/functions.py
  tracecat/llm/__init__.py
  tracecat/llm/ollama.py
  tracecat/llm/openai.py
Labels: enhancement, integrations

#947 feat(ui): Add future interactions
  frontend/src/components/workbench/panel/action-panel.tsx
Labels: frontend

#954 feat(engine): Add serialize/deserialize yaml functions
  tracecat/expressions/functions.py
Labels: enhancement, engine

#955 feat(engine): Add extract ipv4 and emails
  tracecat/expressions/functions.py
Labels: enhancement, engine

#929 feat(ui): Update some icons + default icon
  frontend/src/components/icons.tsx
  frontend/src/components/workbench/canvas/canvas.tsx
Labels: frontend

#953 feat(ui): Edit node title on node + floating node options
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/events/events-sidebar.tsx
Labels: enhancement, frontend

#958 feat(engine): Add unescape string for `FN.join()` separator
  tests/unit/test_parse.py
  tracecat/expressions/functions.py
  tracecat/parse.py
Labels: engine

#959 feat(ui): Toolbar stays visible when moving mouse back over node
  frontend/src/components/workbench/canvas/action-node.tsx
Labels: frontend

#960 feat(integrations): Use markdown section for slack.post_notification prompt
  registry/tracecat_registry/templates/notify/post_notification/slack.yml
Labels: integrations

#963 feat(integrations): Add experimental openai guardduty agent
  registry/tracecat_registry/templates/llm/experimental/alert_contextualizer.yml
  registry/tracecat_registry/templates/llm/experimental/ioc_extractor.yml
  registry/tracecat_registry/templates/llm/experimental/remediation_generator.yml
Labels: integrations

#964 fix(app): Exclude registry cli files during sync + expire registry repo before updating
  tracecat/registry/repositories/router.py
  tracecat/registry/repository.py
Labels: fix

#951 fix(integrations): Fix Okta user lookup query + result parsing
  registry/tracecat_registry/templates/detect/lookup_user_by_email/okta.yml
Labels: integrations

#967 fix(app): Remove default graph edge source handle value
  tracecat/dsl/common.py
  tracecat/dsl/view.py
Labels: fix

#937 feat(ui): allow JSONB insert and adding the collapsable JSON
  frontend/src/components/data-table/table.tsx
  frontend/src/components/json-viewer.tsx
  frontend/src/components/tables/table-insert-row-dialog.tsx
  frontend/src/components/tables/table-view.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/styles/globals.css
Labels: enhancement, fix

#971 fix(engine): Use temporal's workflow.uuid4() if we're inside the workflow sandbox
  tracecat/identifiers/common.py
Labels: engine, fix

#972 chore(app): Small cleanup
  frontend/src/components/json-viewer.tsx
  frontend/src/components/tables/table-insert-row-dialog.tsx
  frontend/src/components/tables/table-view.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/lib/hooks.tsx
  tracecat/dsl/action.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/ee/interactions/decorators.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/expressions/parser/validator.py
  tracecat/workflow/actions/router.py
Labels: refactor

#978 feat(ui): Add workflow executions query limit setting
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-settings-app.tsx
  tracecat/settings/models.py
  tracecat/workflow/executions/router.py
Labels: enhancement, frontend

#979 ci: Sync base registry actions on API reload
  tracecat/registry/common.py
Labels: cicd

#980 feat(ui): Make interactions toggleable
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-settings-app.tsx
  frontend/src/components/workbench/events/events-sidebar.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  tracecat/settings/models.py
  tracecat/workflow/executions/router.py
Labels: enhancement

#981 ci: Add prom metrics to fargate
  deployments/aws/ecs/ecs-caddy.tf
  deployments/aws/ecs/ecs-worker.tf
  deployments/aws/ecs/ecs.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
Labels: cicd, infrastructure

#982 fix: Fix deadlock issue when unexpected keyword in error info + add more metrics
  deployments/aws/ecs/ecs-caddy.tf
  deployments/aws/ecs/ecs-worker.tf
  deployments/aws/ecs/ecs.tf
  deployments/aws/ecs/security_groups.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
  tracecat/dsl/client.py
  tracecat/dsl/scheduler.py
Labels: fix

#983 feat(integrations)!: Update notification and create case schemas
  docs/cheatsheets/functions.mdx
  docs/cheatsheets/integrations.mdx
  registry/tracecat_registry/integrations/slack_sdk.py
  registry/tracecat_registry/schemas/notify/ask_choices.yml
  registry/tracecat_registry/schemas/notify/ask_text_input.yml
  registry/tracecat_registry/schemas/notify/create_case.yml
  registry/tracecat_registry/schemas/notify/post_notification.yml
  registry/tracecat_registry/schemas/notify/post_todo.yml
  registry/tracecat_registry/schemas/notify/post_update.yml
  registry/tracecat_registry/schemas/notify/update_case_severity.yml
  registry/tracecat_registry/schemas/notify/update_case_status.yml
  registry/tracecat_registry/schemas/notify/update_notification.yml
  registry/tracecat_registry/schemas/notify/verify_mfa_push.yml
  registry/tracecat_registry/templates/notify/add_comment/jira.yml
  registry/tracecat_registry/templates/notify/create_case/jira.yml
  registry/tracecat_registry/templates/notify/post_notification/slack.yml
  registry/tracecat_registry/templates/notify/post_todo/slack.yml
  registry/tracecat_registry/templates/notify/post_update/slack.yml
  registry/tracecat_registry/templates/notify/update_case/description/jira.yml
  registry/tracecat_registry/templates/notify/update_case/fields/jira.yml
  registry/tracecat_registry/templates/notify/update_case/status/jira.yml
  registry/tracecat_registry/templates/tools/jira/get_fields.yml
  registry/tracecat_registry/templates/tools/jira/get_priorities.yml
  registry/tracecat_registry/templates/tools/jira/get_priority_schemes.yml
  registry/tracecat_registry/templates/tools/jira/get_projects.yml
  registry/tracecat_registry/templates/tools/jira/get_transitions.yml
Labels: integrations, breaking

#984 feat(engine): Add sentry
  deployments/aws/ecs/locals.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
  docker-compose.dev.yml
  docker-compose.yml
  pyproject.toml
  tracecat/dsl/action.py
  tracecat/dsl/interceptor.py
  tracecat/dsl/scheduler.py
  tracecat/dsl/worker.py
  tracecat/dsl/workflow.py
  tracecat/executor/client.py
Labels: enhancement, engine, infrastructure

#986 feat(engine): Update sentry fingerprinting, add more tags, alert on webhook events
  tracecat/dsl/interceptor.py
Labels: enhancement
