Repository TracecatHQ/tracecat, pull requests merged in 2025-08, with the labels that each got.

#1318 fix: Prevent empty run_if and for_each statements in action forms
  frontend/src/components/builder/panel/action-panel.tsx
Labels: frontend, fix

#1321 feat(ui): Streamline case UI
  CLAUDE.md
  frontend/src/app/workspaces/[workspaceId]/cases/[caseId]/layout.tsx
  frontend/src/app/workspaces/layout.tsx
  frontend/src/components/cases/case-chat.tsx
  frontend/src/components/cases/case-comments-section.tsx
  frontend/src/components/cases/case-description-editor.tsx
  frontend/src/components/cases/case-panel-common.tsx
  frontend/src/components/cases/case-panel-view.tsx
  frontend/src/components/cases/case-workflow-trigger.tsx
  frontend/src/components/chat/action-multiselect.tsx
  frontend/src/components/chat/chat-input.tsx
  frontend/src/components/chat/chat-interface.tsx
  frontend/src/components/chat/chat-tools-dialog.tsx
  frontend/src/components/dashboard/folder-view-toggle.tsx
  frontend/src/components/drag-divider.tsx
  frontend/src/components/nav/controls-header.tsx
  frontend/src/components/sidebar/app-menu.tsx
  frontend/src/components/ui/resizable-sidebar.tsx
  frontend/src/components/ui/sidebar.tsx
Labels: frontend

#1322 feat(engine): Improve custom repo dependency conflict handling through `uv add` + add integration test for custom repo install, sync, and execute
  .github/workflows/run-integration-tests.yml
  Dockerfile
  Dockerfile.dev
  docker-compose.local.yml
  justfile
  pyproject.toml
  tests/integration/test_install_and_run_custom_remote_registry_flow.py
  tests/unit/test_dependency_parsing.py
  tracecat/registry/dependencies.py
  tracecat/registry/repository.py
  uv.lock
Labels: enhancement, engine

#1325 feat(api): Case tags
  alembic/versions/fbc309cb247f_add_tag_ref_and_case_tags.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/case-actions.tsx
  frontend/src/components/cases/case-panel-view.tsx
  frontend/src/components/cases/case-table-columns.tsx
  frontend/src/components/cases/case-table.tsx
  frontend/src/components/cases/delete-case-dialog.tsx
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/dashboard/workflow-folders-table.tsx
  frontend/src/components/tag-badge.tsx
  frontend/src/components/tags-input.tsx
  frontend/src/lib/hooks.tsx
  packages/tracecat-registry/tracecat_registry/core/cases.py
  tests/registry/test_core_cases.py
  tests/unit/test_case_tags_service.py
  tests/unit/test_tags_service.py
  tracecat/api/app.py
  tracecat/cases/models.py
  tracecat/cases/router.py
  tracecat/cases/service.py
  tracecat/cases/tags/__init__.py
  tracecat/cases/tags/models.py
  tracecat/cases/tags/router.py
  tracecat/cases/tags/service.py
  tracecat/db/schemas.py
  tracecat/tags/models.py
  tracecat/tags/service.py
Labels: enhancement, api

#1327 fix(app): Fix action-level environment override
  tests/unit/test_validation_service_environment_override.py
  tracecat/validation/service.py
Labels: enhancement, engine

#1332 refactor: Split EE into standalone package
  .github/workflows/run-integration-tests.yml
  .github/workflows/test-python.yml
  CLAUDE.md
  Dockerfile
  Dockerfile.dev
  packages/tracecat-ee/README.md
  packages/tracecat-ee/pyproject.toml
  packages/tracecat-ee/tracecat_ee/LICENSE.md
  packages/tracecat-ee/tracecat_ee/__init__.py
  packages/tracecat-ee/tracecat_ee/interactions/__init__.py
  packages/tracecat-ee/tracecat_ee/interactions/connectors.py
  packages/tracecat-ee/tracecat_ee/interactions/decorators.py
  packages/tracecat-ee/tracecat_ee/interactions/service.py
  pyproject.toml
  tracecat/contexts.py
  tracecat/db/schemas.py
  tracecat/dsl/common.py
  tracecat/dsl/models.py
  tracecat/ee/interactions/connectors.py
  tracecat/ee/interactions/decorators.py
  tracecat/ee/interactions/enums.py
  tracecat/ee/interactions/models.py
  tracecat/ee/interactions/service.py
  tracecat/expressions/functions.py
  tracecat/interactions/__init__.py
  tracecat/interactions/enums.py
  tracecat/interactions/models.py
  tracecat/validation/service.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/actions/router.py
  uv.lock
Labels: refactor

#1334 refactor: restructure pydantic-ai integration and fix registry type handling
  packages/tracecat-registry/tracecat_registry/integrations/agents/builder.py
  packages/tracecat-registry/tracecat_registry/integrations/pydantic_ai.py
  tests/unit/test_agent_builder.py
  tracecat/dsl/action.py
  tracecat/expressions/expectations.py
  tracecat/prompt/service.py
  tracecat/registry/actions/service.py
  tracecat/registry/repository.py
Labels: refactor

#1339 fix(app): Fix chat session id + DI
  tracecat/agent/executor/deps.py
  tracecat/api/app.py
  tracecat/chat/router.py
  tracecat/utils.py
Labels: fix, api

#1344 fix(ui): Missing boolean input in lookup table row insert
  frontend/src/components/form/options-field.tsx
  frontend/src/components/tables/table-edit-dialog.tsx
  frontend/src/components/tables/table-insert-row-dialog.tsx
  frontend/src/components/tables/tables-side-nav.tsx
Labels: frontend, fix

#1345 refactor: Clean up init and logging
  alembic/versions/db3c91261770_add_temporal_search_attributes.py
  alembic/versions/f92c80ef8c9d_use_uuids_for_workflows.py
  tracecat/settings/service.py
Labels: refactor

#1348 feat: Add org-level case chat agent prompt setting
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-settings-agent.tsx
  packages/tracecat-registry/tracecat_registry/integrations/agents/builder.py
  tracecat/agent/executor/aio.py
  tracecat/chat/router.py
  tracecat/settings/models.py
Labels: enhancement, frontend, engine

#1351 feat: Add toggle for injecting case content into chat agent prompts
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-settings-agent.tsx
  tracecat/chat/router.py
  tracecat/chat/service.py
  tracecat/settings/models.py
Labels: enhancement, frontend, engine

#1350 feat(case): Execute runbook in case chat
  frontend/src/components/cases/case-table.tsx
  frontend/src/components/cases/runbook-dropdown.tsx
  frontend/src/components/cases/runbook-execute-dialog.tsx
  frontend/src/components/cases/runbook-selection-dialog.tsx
  frontend/src/components/chat/chat-interface.tsx
  frontend/src/components/organization/org-settings-agent.tsx
  frontend/src/hooks/use-prompt.tsx
Labels: enhancement

#1352 perf(prompt): Parallelize AI calls in prompt generation
  tracecat/prompt/service.py
Labels: performance

#1353 fix: Rename ProviderRead.schema to config_schema to resolve field shadowing warning
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/provider-config-form.tsx
  tracecat/integrations/models.py
  tracecat/integrations/router.py
Labels: integrations, fix

#1357 feat(integrations): Implement git port
  frontend/src/components/organization/org-settings-git.tsx
  tests/unit/test_git.py
  tracecat/git/utils.py
Labels: enhancement, integrations

#1358 fix: Relax git ssh url regex + restructure
  tests/unit/test_organization_settings.py
  tests/unit/test_repositories.py
  tracecat/api/app.py
  tracecat/git/constants.py
  tracecat/git/utils.py
  tracecat/registry/common.py
  tracecat/registry/repositories/models.py
  tracecat/settings/models.py
Labels: fix

#1343 feat: AlertMedia Update Trip
  packages/tracecat-registry/tracecat_registry/templates/tools/alertmedia/update_trip.yml
Labels: integrations

#1333 feat(integrations): add PhishLabs integration
  docs/cheatsheets/integrations.mdx
  packages/tracecat-registry/tracecat_registry/templates/tools/phishlabs/get_case_data.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/phishlabs/get_feed_data.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/phishlabs/get_threat_data.yml
Labels: enhancement, integrations

#1360 fix(integrations): Fix pagerduty resolve event validation error
  packages/tracecat-registry/tracecat_registry/templates/tools/pagerduty/resolve_event.yml
Labels: integrations

#1362 fix(alertmedia): Lat & Long can be zero
  packages/tracecat-registry/tracecat_registry/templates/tools/alertmedia/update_trip.yml
Labels: integrations, fix

#1370 perf(app): Don't selectin load User relationships
  tracecat/db/schemas.py
Labels: performance

#1371 perf(apop): Only load id and name on Workspace in list methods
  tracecat/workspaces/service.py
Labels: performance

#1373 fix(ui): Fix usage of useWorkspaceId in org workspace settings
  frontend/src/app/organization/settings/workspaces/[workspaceId]/page.tsx
  frontend/src/components/workspaces/add-workspace-member.tsx
  frontend/src/components/workspaces/workspace-members-table.tsx
  frontend/src/hooks/use-workspace.ts
Labels: fix

#1375 fix: Correct type casting for typename in BaseExprValidator
  tracecat/expressions/validator/base.py
Labels: fix

#1377 feat(ee): Custom entities and fields
  alembic/versions/584c872028d2_add_entities_and_entity_fields.py
  docker-compose.local.yml
  tests/unit/test_entities_service.py
  tracecat/api/app.py
  tracecat/db/schemas.py
  tracecat/entities/enums.py
  tracecat/entities/models.py
  tracecat/entities/router.py
  tracecat/entities/service.py
Labels: enhancement, api, enterprise

#1381 feat(integrations): Core HTTP request action now only raises for HTTP ≥ 400
  packages/tracecat-registry/tracecat_registry/core/http.py
Labels: enhancement, core-actions

#1386 fix(app): Workspace admins can delete cases
  tracecat/cases/router.py
Labels: fix, api

#1384 feat: Enable unlimited workflow timeouts by default
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-workspace-settings.tsx
  tracecat/workspaces/models.py
Labels: enhancement, engine

#1387 fix(app): Make workflow unlimited timeout opt-in
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-workspace-settings.tsx
  tracecat/db/schemas.py
  tracecat/workspaces/models.py
Labels: fix

#1388 fix(core): Create columns in create_table service
  tests/registry/test_core_table.py
  tests/unit/test_tables_service.py
  tracecat/tables/router.py
  tracecat/tables/service.py
Labels: fix, core-actions

#1390 feat(app): Implement after-commit callbacks for Temporal schedule management
  tracecat/db/engine.py
  tracecat/db/session_events.py
  tracecat/workflow/schedules/service.py
Labels: enhancement, engine, refactor

#1385 feat: Enhance workflow import service with cross-workflow validation and git sync improvements
  frontend/src/app/organization/vcs/page.tsx
  frontend/src/app/registry/repositories/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/organization/org-vcs-github-manual-form.tsx
  frontend/src/components/organization/org-workspace-settings.tsx
  frontend/src/components/organization/workflow-pull-dialog.tsx
  frontend/src/components/registry/commit-selector.tsx
  frontend/src/components/registry/dialogs/repository-commit-dialog.tsx
  frontend/src/components/registry/dialogs/repository-delete-dialog.tsx
  frontend/src/components/registry/dialogs/repository-sync-dialog.tsx
  frontend/src/components/registry/registry-common.tsx
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/components/registry/table-actions.tsx
  frontend/src/components/sidebar/registry-sidebar.tsx
  frontend/src/hooks/use-feature-flags.ts
  frontend/src/hooks/use-workspace-sync.ts
  frontend/src/lib/hooks.tsx
  tests/unit/test_git.py
  tests/unit/test_workflow_import_service.py
  tests/unit/test_workflow_import_simple.py
  tests/unit/test_workflow_sync_service.py
  tracecat/git/utils.py
  tracecat/registry/actions/service.py
  tracecat/registry/repositories/models.py
  tracecat/registry/repositories/router.py
  tracecat/sync.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/management/management.py
  tracecat/workflow/schedules/bridge.py
  tracecat/workflow/schedules/service.py
  tracecat/workflow/store/import_service.py
  tracecat/workflow/store/models.py
  tracecat/workflow/store/router.py
  tracecat/workflow/store/service.py
  tracecat/workflow/store/sync.py
Labels: enhancement, ui, engine, refactor
