Repository TracecatHQ/tracecat, pull requests merged in 2025-09, with the labels that each got.

#1394 chore: Improve startup sequence with service conditions and health checks
  docker-compose.local.yml
  docker-compose.yml
  tracecat/api/app.py
Labels: build, performance

#1392 build: Enable host port overrides and flexible container names
  docker-compose.dev.yml
Labels: build

#1403 deps(ui): Update nextjs to 15.5.2
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: dependencies

#1389 feat(ui+api): Make file attachment extensions configurable
  alembic/versions/baa5fe7dc011_increase_file_content_type_max_length.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/case-attachments-section.tsx
  frontend/src/components/organization/org-settings-app.tsx
  frontend/src/components/organization/org-workspace-settings.tsx
  frontend/src/lib/hooks.tsx
  packages/tracecat-registry/tracecat_registry/core/cases.py
  packages/tracecat-registry/tracecat_registry/integrations/agents/tools.py
  tests/unit/test_agent_tools.py
  tests/unit/test_attachment_events_detailed.py
  tests/unit/test_blob_storage.py
  tests/unit/test_case_attachments_integration.py
  tests/unit/test_case_attachments_service.py
  tests/unit/test_storage_blob.py
  tests/unit/test_storage_validation.py
  tracecat/api/app.py
  tracecat/cases/attachments/__init__.py
  tracecat/cases/attachments/models.py
  tracecat/cases/attachments/router.py
  tracecat/cases/attachments/service.py
  tracecat/cases/models.py
  tracecat/cases/router.py
  tracecat/cases/service.py
  tracecat/config.py
  tracecat/db/schemas.py
  tracecat/storage.py
  tracecat/storage/blob.py
  tracecat/storage/exceptions.py
  tracecat/storage/validation.py
  tracecat/workspaces/models.py
Labels: enhancement

#1404 feat: Upgrade pydantic-ai to 0.8.1 and update dependencies
  packages/tracecat-registry/pyproject.toml
  packages/tracecat-registry/tracecat_registry/integrations/agents/builder.py
  pyproject.toml
  tests/data/iocs/domain.yml
  tests/unit/test_agent_builder.py
  uv.lock
Labels: build, dependencies

#1398 feat: Add database connection pool health check endpoint
  tracecat/executor/router.py
Labels: enhancement, engine

#1417 feat(integrations): HTTP pagination action
  docs/quickstart/core-actions.mdx
  packages/tracecat-registry/tracecat_registry/core/http.py
  tests/registry/test_core_http.py
Labels: enhancement

#1420 feat(ui): Case records
  frontend/src/components/cases/case-panel-view.tsx
  frontend/src/components/cases/case-records-section.tsx
  frontend/src/components/cases/case-records-table.tsx
  frontend/src/components/cases/delete-case-record-dialog.tsx
  frontend/src/components/cases/edit-case-record-dialog.tsx
  frontend/src/components/entities/entity-selector-popover.tsx
  frontend/src/components/nav/controls-header.tsx
  frontend/src/lib/hooks.tsx
Labels: enhancement, ui

#1432 feat(integrations): Add Exa templates
  packages/tracecat-registry/tracecat_registry/templates/tools/exa/answer.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/exa/get_contents.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/exa/search.yml
Labels: integrations

#1438 feat: Add runbook alias support and improve chat interface integration
  docker-compose.dev.yml
  frontend/src/app/workspaces/[workspaceId]/runbooks/[runbookId]/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/chat/chat-input.tsx
  frontend/src/components/chat/chat-interface.tsx
  frontend/src/components/chat/messages.tsx
  frontend/src/components/runbooks/runbook-alias-editor.tsx
  frontend/src/components/runbooks/runbook-card.tsx
  frontend/src/components/runbooks/runbook-inline-alias-editor.tsx
  frontend/src/lib/hooks.tsx
  packages/tracecat-registry/tracecat_registry/core/runbooks.py
  packages/tracecat-registry/tracecat_registry/integrations/agents/builder.py
  tests/unit/test_runbook_service.py
  tracecat/agent/config.py
  tracecat/chat/router.py
  tracecat/runbook/models.py
  tracecat/runbook/router.py
  tracecat/runbook/service.py
Labels: enhancement, ui, api

#1440 fix: enhance runbook execution and table metadata functionality
  packages/tracecat-registry/tracecat_registry/core/runbooks.py
  packages/tracecat-registry/tracecat_registry/core/table.py
  tracecat/middleware/auth.py
  tracecat/runbook/router.py
  tracecat/runbook/service.py
Labels: enhancement, fix

#1442 feat(integrations): langfuse integration
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  packages/tracecat-registry/pyproject.toml
  packages/tracecat-registry/tracecat_registry/integrations/agents/builder.py
  packages/tracecat-registry/tracecat_registry/integrations/pydantic_ai.py
  uv.lock
Labels: integrations, agents

#1448 feat(ui): Implement bulk delete functionality in case table
  frontend/src/components/cases/case-table-filters.tsx
  frontend/src/components/cases/case-table.tsx
  frontend/src/components/data-table/table.tsx
  frontend/src/components/data-table/toolbar.tsx
Labels: ui

#1447 feat(integrations): MCP OAuth providers
  frontend/src/app/workspaces/[workspaceId]/integrations/[providerId]/page.tsx
  frontend/src/components/icons.tsx
  frontend/src/components/provider-config-form.tsx
  frontend/src/lib/providers.ts
  tracecat/integrations/models.py
  tracecat/integrations/providers/__init__.py
  tracecat/integrations/providers/base.py
  tracecat/integrations/providers/github/mcp.py
  tracecat/integrations/providers/linear/mcp.py
  tracecat/integrations/providers/notion/mcp.py
  tracecat/integrations/providers/runreveal/mcp.py
  tracecat/integrations/providers/sentry/mcp.py
  tracecat/integrations/router.py
  tracecat/integrations/service.py
Labels: enhancement, ui, api

#1449 feat(agents)!: Single AI agent action
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  packages/tracecat-registry/tracecat_registry/integrations/agents/builder.py
  packages/tracecat-registry/tracecat_registry/integrations/ollama.py
  packages/tracecat-registry/tracecat_registry/templates/tools/anthropic/call.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/bedrock/call.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/gemini/call.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/gemini/call_vertex.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/openai/chat_completion.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/openai/responses.yml
  tests/unit/test_agent_builder.py
Labels: breaking

#1452 refactor(agents): Move agent code from integrations into main pkg
  packages/tracecat-registry/pyproject.toml
  packages/tracecat-registry/tracecat_registry/core/agent.py
  packages/tracecat-registry/tracecat_registry/core/runbooks.py
  packages/tracecat-registry/tracecat_registry/integrations/agents/builder.py
  packages/tracecat-registry/tracecat_registry/integrations/pydantic_ai.py
  pyproject.toml
  tests/registry/test_pydantic_ai.py
  tests/unit/test_agent_builder.py
  tracecat/agent/__init__.py
  tracecat/agent/exceptions.py
  tracecat/agent/executor/aio.py
  tracecat/agent/parsers.py
  tracecat/agent/providers.py
  tracecat/agent/runtime.py
  tracecat/agent/tokens.py
  tracecat/agent/tools.py
  tracecat/chat/router.py
  tracecat/chat/service.py
  tracecat/runbook/flows.py
  tracecat/runbook/router.py
  tracecat/runbook/service.py
  tracecat/workflow/executions/router.py
  uv.lock
Labels: refactor

#1463 feat(agents): Introduce max limits for tool calls and requests in age…
  packages/tracecat-registry/tracecat_registry/core/agent.py
  tracecat/agent/runtime.py
  tracecat/config.py
Labels: enhancement, agents

#1466 feat(agents): Add response emoji reactions
  packages/tracecat-registry/tracecat_registry/integrations/agents/slack.py
Labels: enhancement, agents

#1468 feat: Add runbooks feature flag
  frontend/src/app/workspaces/[workspaceId]/runbooks/[runbookId]/page.tsx
  frontend/src/app/workspaces/[workspaceId]/runbooks/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/runbook-dropdown.tsx
  frontend/src/components/chat/chat-interface.tsx
  frontend/src/components/nav/controls-header.tsx
  frontend/src/components/sidebar/app-sidebar.tsx
  frontend/src/hooks/use-runbook.tsx
  tracecat/api/app.py
  tracecat/feature_flags/enums.py
Labels: enhancement, ui, api

#1455 feat(integrations): Add domain and email leaks research (leakcheck)
  docs/cheatsheets/integrations.mdx
  packages/tracecat-registry/tracecat_registry/templates/tools/leakcheck/search_domain_leak.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/leakcheck/search_email_leak.yml
Labels: integrations

#1472 revert: Add LLM templates
  packages/tracecat-registry/tracecat_registry/templates/tools/anthropic/call.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/bedrock/call.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/gemini/call.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/gemini/call_vertex.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/ollama/call.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/openai/chat_completion.yml
  packages/tracecat-registry/tracecat_registry/templates/tools/openai/responses.yml
Labels: integrations

#1474 feat(core): Add wait UDF
  packages/tracecat-registry/tracecat_registry/core/transform.py
Labels: core-actions

#1475 feat(integrations): Add MinIO actions
  packages/tracecat-registry/tracecat_registry/integrations/amazon_s3.py
  packages/tracecat-registry/tracecat_registry/integrations/aws_boto3.py
  packages/tracecat-registry/tracecat_registry/integrations/minio.py
  pyproject.toml
  requirements.txt
  uv.lock
Labels: enhancement, integrations

#1478 feat(engine): Add scatter interval for rate-limited task execution
  packages/tracecat-registry/tracecat_registry/core/transform.py
  tests/unit/test_scatter_interval.py
  tests/unit/test_scatter_interval_models.py
  tracecat/dsl/models.py
  tracecat/dsl/scheduler.py
Labels: enhancement, engine, tests
