Repository TracecatHQ/tracecat, pull requests merged in 2025-06, with the labels that each got.

#1168 feat(integrations): Run Python script action
  .github/workflows/test-python.yml
  Dockerfile
  Dockerfile.dev
  docs/docs.json
  docs/introduction.mdx
  docs/quickstart/core-actions.mdx
  docs/quickstart/script-actions.mdx
  registry/tracecat_registry/core/python.py
  scripts/install-packages.sh
  tests/registry/test_core_python.py
  tracecat/config.py
Labels: enhancement, integrations

#1165 feat(integrations): Support multi-part file uploads in http
  docs/quickstart/core-actions.mdx
  registry/tracecat_registry/core/http.py
  registry/tracecat_registry/integrations/amazon_s3.py
  tests/registry/test_core_http.py
  tracecat/config.py
Labels: enhancement, integrations

#1171 fix(api): prevent over-aggressive character masking
  tests/unit/test_secrets.py
  tracecat/executor/service.py
  tracecat/secrets/common.py
Labels: fix, security

#1157 feat(agents): Tool calling agent-as-an-action
  registry/pyproject.toml
  registry/tracecat_registry/integrations/agents/builder.py
  registry/tracecat_registry/integrations/pydantic_ai.py
  tests/conftest.py
  tests/registry/mcp/test_slackbot.py
  tests/registry/test_pydantic_ai.py
  tests/unit/test_agent_builder.py
  tests/unit/test_auth_middleware.py
Labels: enhancement, agents

#1172 feat(agent): Add retries and model_settings to agent builder
  .cursor/rules/python.mdc
  registry/tracecat_registry/integrations/agents/builder.py
  tests/registry/test_pydantic_ai.py
  tests/unit/test_agent_builder.py
Labels: fix, agents

#1175 fix(integrations): Run python script node permissions in prod
  Dockerfile
  registry/tracecat_registry/core/python.py
  scripts/install-packages.sh
Labels: fix, infrastructure

#1176 fix(integrations): Support AWS RoleArn in pydantic AI bedrock
  registry/tracecat_registry/integrations/amazon_s3.py
  registry/tracecat_registry/integrations/aws_boto3.py
  registry/tracecat_registry/integrations/pydantic_ai.py
Labels: fix, agents

#1170 feat(integrations): SentinelOne Integrations
  registry/tracecat_registry/templates/tools/sentinel_one/abort_scan.yml
  registry/tracecat_registry/templates/tools/sentinel_one/disable_agent.yml
  registry/tracecat_registry/templates/tools/sentinel_one/enable_agent.yml
  registry/tracecat_registry/templates/tools/sentinel_one/initiate_scan.yml
  registry/tracecat_registry/templates/tools/sentinel_one/isolate_endpoint.yml
  registry/tracecat_registry/templates/tools/sentinel_one/list_agent_ids.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_account_id.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_email.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_groupid.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_hash.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_hostname.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_ip.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_mac_addr.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_machinetype.yml
  registry/tracecat_registry/templates/tools/sentinel_one/lookup_agent_os.yml
  registry/tracecat_registry/templates/tools/sentinel_one/unisolate_endpoint.yml
Labels: integrations

#1180 feat(integrations): Extend S3 actions with endpoint url
  registry/tracecat_registry/integrations/amazon_s3.py
  registry/tracecat_registry/integrations/aws_boto3.py
  registry/tracecat_registry/integrations/ee/grep.py
Labels: enhancement, integrations

#1179 feat(app): Format agent output
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/builder/events/events-selected-action.tsx
  frontend/src/components/builder/events/events-sidebar-interactions.tsx
  frontend/src/components/builder/events/events-workflow.tsx
  frontend/src/components/json-viewer.tsx
  frontend/src/lib/event-history.ts
  frontend/src/lib/hooks.tsx
  frontend/src/lib/utils.ts
  registry/tracecat_registry/integrations/agents/builder.py
  tests/unit/test_agent_builder.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
Labels: enhancement, frontend

#1181 feat(ui): Improve agent output scroll behavior
  frontend/src/components/builder/events/events-selected-action.tsx
  frontend/src/components/builder/events/events-sidebar.tsx
Labels: enhancement, frontend

#1185 build(fix): apiuser permissions in app and uv cache
  Dockerfile
Labels: integrations, fix, build, api

#1186 feat(ui): Expose action ref in ActionRead
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  tests/shared.py
  tracecat/dsl/workflow.py
  tracecat/workflow/actions/models.py
Labels: enhancement, frontend

#1187 feat(engine): Webhook event batching
  tracecat/webhooks/dependencies.py
  tracecat/webhooks/models.py
  tracecat/webhooks/router.py
Labels: enhancement, engine

#1188 feat(ui): Add icon for core.script
  frontend/src/components/icons.tsx
Labels: frontend

#1203 fix(app): Implement changing roles
  tracecat/auth/users.py
Labels: fix

#1204 feat(ui): Conversations and action profile nits
  frontend/next-env.d.ts
  frontend/src/components/builder/events/events-selected-action.tsx
  frontend/src/components/builder/panel/action-panel.tsx
  frontend/src/components/registry/icons.tsx
Labels: frontend

#1206 feat(ui): Add error boundaries in builder UI
  frontend/src/components/builder/builder.tsx
  frontend/src/components/builder/panel/action-panel.tsx
  frontend/src/components/editor/codemirror/common.tsx
  frontend/src/components/editor/expression-input.tsx
  frontend/src/components/error-boundaries.tsx
  frontend/src/components/error-boundary.tsx
Labels: frontend

#1207 fix(app): Force DSLInput to always serialize as JSON
  tests/unit/test_workflow_definitions_service.py
  tracecat/dsl/common.py
Labels: fix

#1209 fix: SAML_ACCEPTED_TIME_DIFF not in env.example
  .env.example
Labels: fix

#1211 perf(engine): Skip validate trigger inputs earlier
  tracecat/dsl/workflow.py
Labels: engine, performance

#1215 perf(engine): Replace Earley parser + grammar with LALR
  scripts/benchmark/benchmark_parser.py
  tests/unit/test_workflows.py
  tracecat/expressions/parser/core.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/grammar.py
Labels: performance

#1221 perf(engine): Add compression payload codec
  .github/workflows/test-python.yml
  pyproject.toml
  tests/conftest.py
  tests/unit/test_workflow_timers.py
  tracecat/config.py
  tracecat/dsl/_converter.py
  tracecat/dsl/client.py
  tracecat/dsl/compression.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
Labels: performance

#1226 fix: Properly handle datetime args in jsonschema validation
  tests/unit/test_json_schema_validation.py
  tracecat/validation/common.py
Labels: fix

#1227 perf(ui): Cache workflows page using nextjs Link
  frontend/src/app/workspaces/[workspaceId]/integrations/[providerId]/page.tsx
  frontend/src/app/workspaces/[workspaceId]/tables/[tableId]/page.tsx
  frontend/src/components/nav/builder-nav.tsx
Labels: performance

#1231 feat(app): Implement API pagination for tables and cases
  alembic/versions/13022d1ff78d_add_case_cursor_pagination_index.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/case-table.tsx
  frontend/src/components/data-table/index.tsx
  frontend/src/components/data-table/pagination.tsx
  frontend/src/components/data-table/table.tsx
  frontend/src/components/tables/table-view.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/pagination/index.ts
  frontend/src/hooks/pagination/use-cases-pagination.tsx
  frontend/src/hooks/pagination/use-cursor-pagination.tsx
  frontend/src/hooks/pagination/use-tables-pagination.tsx
  frontend/src/lib/hooks.tsx
  tests/unit/test_pagination.py
  tracecat/cases/router.py
  tracecat/cases/service.py
  tracecat/db/schemas.py
  tracecat/tables/router.py
  tracecat/tables/service.py
  tracecat/types/pagination.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/router.py
Labels: performance

#1232 refactor: Optional provider config
  frontend/src/app/workspaces/[workspaceId]/integrations/[providerId]/page.tsx
  frontend/src/components/provider-config-form.tsx
  frontend/src/lib/hooks.tsx
  tracecat/integrations/base.py
  tracecat/integrations/router.py
Labels: enhancement, refactor

#1225 feat(integrations): Alertmedia integration
  registry/tracecat_registry/templates/tools/alertmedia/create_trip.yml
  registry/tracecat_registry/templates/tools/alertmedia/delete_trip.yml
  registry/tracecat_registry/templates/tools/alertmedia/get_travel_events.yml
  registry/tracecat_registry/templates/tools/alertmedia/get_user_trip_by_id.yml
  registry/tracecat_registry/templates/tools/alertmedia/get_user_trips.yml
  registry/tracecat_registry/templates/tools/alertmedia/search_trips.yml
  registry/tracecat_registry/templates/tools/alertmedia/search_users.yml
Labels: integrations

#1233 feat: Add user customizable scopes
  alembic/versions/67914e68c877_add_requested_scopes_to_oauth_.py
  frontend/src/app/workspaces/[workspaceId]/integrations/[providerId]/page.tsx
  frontend/src/app/workspaces/[workspaceId]/integrations/inspo.tsx
  frontend/src/app/workspaces/[workspaceId]/integrations/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/provider-config-form.tsx
  frontend/src/components/redirect-uri-display.tsx
  frontend/src/components/tags-input.tsx
  frontend/src/components/ui/collapsible-card.tsx
  frontend/src/components/ui/collapsible.tsx
  frontend/src/lib/hooks.tsx
  frontend/tailwind.config.js
  tests/unit/test_integrations_service.py
  tracecat/db/schemas.py
  tracecat/integrations/base.py
  tracecat/integrations/dependencies.py
  tracecat/integrations/models.py
  tracecat/integrations/providers/microsoft.py
  tracecat/integrations/router.py
  tracecat/integrations/service.py
Labels: enhancement
