Repository TracecatHQ/tracecat, pull requests merged in 2025-05, with the labels that each got.

#1099 fix(ui): Fix child workflow icon when using ID
  frontend/src/components/workbench/canvas/action-node.tsx
Labels: frontend, fix

#1100 feat(app): Implement workflow folders
  alembic/versions/61f47f34caa9_add_workflowfolder.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/dashboard/create-workflow-button.tsx
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/dashboard/file-tree-command.tsx
  frontend/src/components/dashboard/folder-delete-dialog.tsx
  frontend/src/components/dashboard/folder-move-dialog.tsx
  frontend/src/components/dashboard/folder-rename-dialog.tsx
  frontend/src/components/dashboard/folder-view-toggle.tsx
  frontend/src/components/dashboard/table-actions.tsx
  frontend/src/components/dashboard/table-common.tsx
  frontend/src/components/dashboard/workflow-folders-sidebar.tsx
  frontend/src/components/dashboard/workflow-folders-table.tsx
  frontend/src/components/dashboard/workflow-move-dialog.tsx
  frontend/src/components/dashboard/workflows-dashboard.tsx
  frontend/src/components/data-table/table.tsx
  frontend/src/components/ui/command.tsx
  frontend/src/lib/hooks.tsx
  tests/unit/test_workflow_folders_service.py
  tracecat/api/app.py
  tracecat/db/schemas.py
  tracecat/workflow/management/folders/__init__.py
  tracecat/workflow/management/folders/models.py
  tracecat/workflow/management/folders/router.py
  tracecat/workflow/management/folders/service.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: enhancement, frontend

#1101 fix(app): Don't allow schedule creation if workflow not saved
  frontend/src/components/workbench/panel/trigger-panel.tsx
  tracecat/workflow/schedules/router.py
Labels: frontend, fix, api

#1102 feat(app): Add manual create case button
  frontend/src/components/cases/case-table-manage-button.tsx
  frontend/src/lib/hooks.tsx
Labels: enhancement, frontend

#1103 feat(app): Add case assignee
  alembic/versions/0b9bf4cd7276_add_case_assignee.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/case-panel-selectors.tsx
  frontend/src/components/cases/case-panel-view.tsx
  frontend/src/components/cases/case-table-columns.tsx
  frontend/src/components/cases/case-table.tsx
  frontend/src/lib/auth.ts
  tests/unit/test_case_fields_integration.py
  tests/unit/test_cases_service.py
  tracecat/cases/models.py
  tracecat/cases/router.py
  tracecat/cases/service.py
  tracecat/db/schemas.py
Labels: enhancement, frontend, api

#1105 fix(app): Don't create workspace on signup by default
  tracecat/settings/models.py
Labels: fix

#1107 fix(integrations): Ansible SSH
  registry/tracecat_registry/integrations/ansible.py
Labels: integrations, fix

#1108 feat(integrations): Add exec and run k8s actions
  .github/workflows/test-python.yml
  registry/tracecat_registry/integrations/ee/kubernetes.py
  registry/tracecat_registry/templates/ee/kubernetes/create_pvc.yml
  registry/tracecat_registry/templates/ee/kubernetes/create_secret.yml
  registry/tracecat_registry/templates/ee/kubernetes/exec.yml
  registry/tracecat_registry/templates/ee/kubernetes/logs.yml
  registry/tracecat_registry/templates/ee/kubernetes/run.yml
  tests/unit/test_kubernetes.py
  tracecat/ee/sandbox/kubernetes.py
Labels: integrations

#1110 feat(ui): Add toggle to group case fields in trigger input
  frontend/src/components/cases/case-workflow-trigger.tsx
Labels: enhancement, frontend

#1111 build(deps): Bump fastapi + uvicorn
  pyproject.toml
Labels: fix, dependencies

#1109 feat(integrations): Add openapi to action template script
  scripts/openapi_to_template.py
  scripts/openapi_to_template_example_config.yaml
Labels: enhancement, integrations

#1114 feat(integrations): Slack ChatOps starter kit
  docs/tutorials/workflow-triggers.mdx
  registry/tracecat_registry/integrations/slack_sdk.py
  registry/tracecat_registry/templates/tools/slack/chat/delete_message.yml
  registry/tracecat_registry/templates/tools/slack/chat/post_message.yml
  registry/tracecat_registry/templates/tools/slack/chat/update_message.yml
  registry/tracecat_registry/templates/tools/slack/conversations/archive_channel.yml
  registry/tracecat_registry/templates/tools/slack/conversations/create_channel.yml
  registry/tracecat_registry/templates/tools/slack/conversations/invite_members.yml
  registry/tracecat_registry/templates/tools/slack/conversations/kick_member.yml
  registry/tracecat_registry/templates/tools/slack/conversations/list_channels.yml
  registry/tracecat_registry/templates/tools/slack/conversations/list_members.yml
  registry/tracecat_registry/templates/tools/slack/conversations/list_messages.yml
  registry/tracecat_registry/templates/tools/slack/conversations/set_channel_description.yml
  registry/tracecat_registry/templates/tools/slack/conversations/set_channel_topic.yml
  registry/tracecat_registry/templates/tools/slack/custom/find_channel.yml
  registry/tracecat_registry/templates/tools/slack/custom/post_notification.yml
  registry/tracecat_registry/templates/tools/slack/custom/post_update.yml
  registry/tracecat_registry/templates/tools/slack/reactions/get_reactions.yml
  registry/tracecat_registry/templates/tools/slack/templates/ask_text_input.yml
  registry/tracecat_registry/templates/tools/slack/users/get_profile.yml
  registry/tracecat_registry/templates/tools/slack/users/lookup_user_by_email.yml
  registry/tracecat_registry/templates/tools/slack/views/open_view.yml
  registry/tracecat_registry/templates/tools/slack/views/update_view.yml
  tracecat/expressions/functions.py
  tracecat/webhooks/router.py
Labels: integrations

#1115 fix(test): Sort pending children by initiated ID
  tests/unit/test_workflows.py
Labels: tests, fix

#1117 feat(integrations): Slack list users and rich text input
  registry/tracecat_registry/core/transform.py
  registry/tracecat_registry/integrations/slack_sdk.py
  registry/tracecat_registry/templates/tools/slack/custom/post_notification.yml
  registry/tracecat_registry/templates/tools/slack/custom/post_update.yml
  registry/tracecat_registry/templates/tools/slack/users/list_users.yml
  tracecat/expressions/functions.py
Labels: integrations

#1118 fix(engine): Ignore action delete if not found
  tracecat/workflow/actions/router.py
Labels: fix

#1116 fix(ui): Add defensive graph pruning on canvas init + layout
  frontend/src/components/workbench/canvas/canvas.tsx
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
  frontend/tests/workflow.test.ts
Labels: frontend, fix

#1113 docs: OpenAPI to template generator
  docs/docs.json
  docs/integrations/openapi-generator.mdx
Labels: documentation

#1121 refactor(ui): `workbench` -> `builder`
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/page.tsx
  frontend/src/components/builder/builder.tsx
  frontend/src/components/builder/canvas/action-node.tsx
  frontend/src/components/builder/canvas/canvas.tsx
  frontend/src/components/builder/canvas/custom-handle.tsx
  frontend/src/components/builder/canvas/delete-node-dialog.tsx
  frontend/src/components/builder/canvas/node-styles.ts
  frontend/src/components/builder/canvas/selector-node.tsx
  frontend/src/components/builder/canvas/trigger-node.tsx
  frontend/src/components/builder/events/events-selected-action.tsx
  frontend/src/components/builder/events/events-sidebar-empty.tsx
  frontend/src/components/builder/events/events-sidebar-interactions.tsx
  frontend/src/components/builder/events/events-sidebar.tsx
  frontend/src/components/builder/events/events-workflow.tsx
  frontend/src/components/builder/panel/action-panel-tooltips.tsx
  frontend/src/components/builder/panel/action-panel.tsx
  frontend/src/components/builder/panel/builder-panel.tsx
  frontend/src/components/builder/panel/trigger-panel.tsx
  frontend/src/components/builder/panel/workflow-panel.tsx
  frontend/src/components/nav/builder-nav.tsx
  frontend/src/components/nav/dynamic-nav.tsx
  frontend/src/lib/hooks.tsx
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
  frontend/tests/workflow.test.ts
Labels: refactor

#1119 fix(ui): Add missing page titles and small nits
  docs/quickstart/expressions.mdx
  docs/quickstart/tutorial.mdx
  frontend/next-env.d.ts
  frontend/src/app/organization/members/layout.tsx
  frontend/src/app/organization/sessions/layout.tsx
  frontend/src/app/organization/settings/app/layout.tsx
  frontend/src/app/organization/settings/app/page.tsx
  frontend/src/app/organization/settings/auth/layout.tsx
  frontend/src/app/organization/settings/git/layout.tsx
  frontend/src/app/organization/settings/oauth/layout.tsx
  frontend/src/app/organization/settings/sso/layout.tsx
  frontend/src/app/organization/ssh-keys/layout.tsx
  frontend/src/app/registry/actions/layout.tsx
  frontend/src/app/registry/repositories/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/cases/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/credentials/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/members/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/profile/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/security/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/tables/[tableId]/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/tables/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/page.tsx
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/page.tsx
  frontend/src/components/builder/canvas/action-node.tsx
  frontend/src/components/builder/canvas/custom-handle.tsx
  frontend/src/components/builder/canvas/delete-node-dialog.tsx
  frontend/src/components/builder/panel/builder-panel.tsx
  frontend/src/components/builder/panel/workflow-panel.tsx
  frontend/src/components/organization/org-settings-app.tsx
  frontend/src/components/tables/table-view.tsx
  frontend/src/lib/hooks.tsx
  registry/tracecat_registry/core/cases.py
  registry/tracecat_registry/core/email.py
  registry/tracecat_registry/core/http.py
  registry/tracecat_registry/core/table.py
  registry/tracecat_registry/core/workflow.py
Labels: frontend, fix

#1125 chore(build): Remove deprecated env vars
  .env.example
  deployments/aws/ecs/locals.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
  docker-compose.dev.yml
  docker-compose.yml
  docs/self-hosting/authentication/basic.mdx
  docs/self-hosting/authentication/google-oauth.mdx
  docs/self-hosting/authentication/saml-sso.mdx
  registry/tracecat_registry/core/email.py
  tests/conftest.py
  tracecat/config.py
  tracecat/git.py
  tracecat/registry/common.py
  tracecat/registry/repository.py
Labels: build, chore

#1128 feat(engine+integrations): Add interaction metadata
  registry/tracecat_registry/templates/tools/slack/chat/post_message.yml
  registry/tracecat_registry/templates/tools/slack/custom/post_notification.yml
  registry/tracecat_registry/templates/tools/slack/custom/post_update.yml
  tracecat/ee/interactions/connectors.py
Labels: enhancement

#1129 feat(engine): Add trigger type to `ENV.workflow`
  tracecat/dsl/workflow.py
Labels: enhancement, engine

#1131 feat(app): Accept GET webhooks
  alembic/versions/ef08aba23d77_support_multiple_webhook_methods.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/builder/panel/action-panel.tsx
  frontend/src/components/builder/panel/trigger-panel.tsx
  tracecat/db/schemas.py
  tracecat/webhooks/dependencies.py
  tracecat/webhooks/models.py
  tracecat/webhooks/router.py
  tracecat/workflow/management/router.py
Labels: enhancement, engine

#1132 feat(app): Improve validation errors
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/builder/canvas/action-node.tsx
  frontend/src/components/builder/panel/action-panel.tsx
  frontend/src/components/nav/builder-nav.tsx
  frontend/src/components/validation-errors.tsx
  frontend/src/providers/workflow.tsx
  tracecat/registry/actions/models.py
  tracecat/validation/common.py
  tracecat/validation/models.py
  tracecat/validation/service.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: enhancement, frontend

#1134 feat(integrations): Add password lifecycle Okta actions
  registry/tracecat_registry/templates/tools/okta/expire_password.yml
  registry/tracecat_registry/templates/tools/okta/expire_password_with_temporary_password.yml
  registry/tracecat_registry/templates/tools/okta/reset_password.yml
  registry/tracecat_registry/templates/tools/okta/suspend_user.yml
Labels: enhancement, integrations

#1137 fix(app): Fix logging in Temproal connection step
  tracecat/dsl/client.py
Labels: enhancement, fix

#1138 build(fix): More conservative retries and depends on
  docker-compose.dev.yml
  docker-compose.yml
  tracecat/dsl/client.py
Labels: fix, build

#1133 feat(app): Move interaction state out of workflow
  alembic/versions/14b4de0bbc0e_add_is_system_and_type_to_registry_repos.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/builder/canvas/action-node-effect.tsx
  frontend/src/components/builder/canvas/action-node.tsx
  frontend/src/components/builder/canvas/custom-handle.tsx
  frontend/src/components/builder/events/events-selected-action.tsx
  frontend/src/components/builder/events/events-sidebar-interactions.tsx
  tests/unit/test_interactions.py
  tracecat/db/schemas.py
  tracecat/dsl/worker.py
  tracecat/dsl/workflow.py
  tracecat/ee/interactions/decorators.py
  tracecat/ee/interactions/enums.py
  tracecat/ee/interactions/models.py
  tracecat/ee/interactions/service.py
  tracecat/service.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
Labels: enhancement, engine, refactor

#1141 feat(app): Implement events toolbar
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/builder/builder.tsx
  frontend/src/components/builder/events/events-sidebar-toolbar.tsx
  frontend/src/components/builder/events/events-sidebar.tsx
  frontend/src/components/builder/events/events-workflow.tsx
  frontend/src/components/executions/event-history.tsx
  frontend/src/lib/hooks.tsx
  tracecat/dsl/common.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
Labels: enhancement, frontend

#1143 feat(app): Limit what actions can use interactions + add validation
  frontend/src/components/builder/panel/action-panel.tsx
  frontend/src/lib/interactions.ts
  tracecat/validation/service.py
Labels: enhancement

#1145 fix(app): Prevent role change
  tracecat/auth/users.py
Labels: fix

#1147 fix(app): Drop role in UserCreate + simplify conftest
  tests/conftest.py
  tracecat/auth/models.py
Labels: fix

#1152 feat(app): Implement case activity
  alembic/versions/fc82d8b66c20_add_case_events.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/cases/case-activity-feed-event.tsx
  frontend/src/components/cases/case-activity-feed.tsx
  frontend/src/components/cases/case-categories.tsx
  frontend/src/components/cases/case-comments-section.tsx
  frontend/src/components/cases/case-panel-common.tsx
  frontend/src/components/cases/case-panel-selectors.tsx
  frontend/src/components/cases/case-panel-view.tsx
  frontend/src/components/cases/case-table-columns.tsx
  frontend/src/components/cases/case-table.tsx
  frontend/src/components/cases/case-timeline-example.tsx
  frontend/src/lib/auth.ts
  frontend/src/lib/event-history.ts
  frontend/src/lib/hooks.tsx
  frontend/src/lib/utils.ts
  tests/unit/test_case_events_service.py
  tracecat/auth/models.py
  tracecat/auth/users.py
  tracecat/cases/enums.py
  tracecat/cases/models.py
  tracecat/cases/router.py
  tracecat/cases/service.py
  tracecat/db/schemas.py
Labels: enhancement, frontend, engine

#1149 feat(integrations): MCPHost and ShortTermMemory ABC
  registry/tracecat_registry/integrations/mcp/agent.py
  registry/tracecat_registry/integrations/mcp/exceptions.py
  registry/tracecat_registry/integrations/mcp/hosts/slack.py
  registry/tracecat_registry/integrations/mcp/memory.py
  registry/tracecat_registry/integrations/pydantic_ai.py
Labels: enhancement

#1162 fix(api): Implement authz middleware to cache requests
  tests/unit/test_auth_middleware.py
  tracecat/api/app.py
  tracecat/auth/credentials.py
  tracecat/authz/service.py
  tracecat/middleware/__init__.py
  tracecat/middleware/auth.py
Labels: fix, performance, api

#1156 fix(engine): Type hints in agents
  registry/tracecat_registry/integrations/mcp/agent.py
  registry/tracecat_registry/integrations/mcp/hosts/slack.py
  registry/tracecat_registry/integrations/mcp/memory.py
  registry/tracecat_registry/integrations/pydantic_ai.py
Labels: fix

#1164 feat(agents): Add ABC that runs if memory cache miss
  registry/tracecat_registry/integrations/mcp/agent.py
  registry/tracecat_registry/integrations/mcp/exceptions.py
  registry/tracecat_registry/integrations/mcp/hosts/slack.py
Labels: enhancement, agents
