Repository TracecatHQ/tracecat, pull requests merged in 2025-01, with the labels that each got.

#689 refactor(engine): Rename RegistryActionErrorInfo to ExecutorActionErrorInfo
  tests/unit/test_executor.py
  tracecat/executor/client.py
  tracecat/executor/models.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/registry/actions/models.py
Labels: internal

#690 feat(engine): Add workflow error handler to schema and API
  alembic/versions/f2e840c9fb2c_add_workflow_error_handler.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  tracecat/db/schemas.py
  tracecat/dsl/common.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
Labels: enhancement

#691 refactor(engine): Rename ActionExecutionError to ExecutorClientError
  tests/unit/test_workflows.py
  tracecat/dsl/action.py
  tracecat/executor/client.py
  tracecat/types/exceptions.py
Labels: refactor

#693 fix(integration): Remove unnecessary DN escaping in LDAP client
  registry/tracecat_registry/integrations/ldap3.py
Labels: integration, fix

#692 feat(integration): Make allowed email attributes configurable via env vars
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
  registry/tracecat_registry/base/core/email.py
  tracecat/config.py
Labels: enhancement, integration

#696 refactor(engine): Rename DSLTaskErrorInfo to ActionErrorInfo
  tracecat/dsl/action.py
  tracecat/dsl/models.py
Labels: internal

#694 feat(engine): Parameterize git host for custom repository
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  tests/unit/test_registry.py
  tracecat/config.py
  tracecat/registry/constants.py
  tracecat/registry/repository.py
Labels: enhancement, engine

#699 fix(security): Microsoft entra nameattribute parsing
  .env.example
  deployments/aws/ecs/ecs-temporal-ui.tf
  deployments/aws/ecs/iam.tf
  deployments/aws/ecs/secrets.tf
  deployments/aws/ecs/variables.tf
  deployments/aws/main.tf
  deployments/aws/variables.tf
  docker-compose.dev.yml
  docker-compose.yml
  docs/self-hosting/authentication/saml.mdx
  docs/self-hosting/deployment-options/aws-ecs.mdx
  tracecat/api/app.py
  tracecat/auth/saml.py
Labels: fix, infrastructure

#688 refactor(engine): Remove croniter validation and dependency
  pyproject.toml
  tracecat/db/schemas.py
Labels: internal

#687 refactor: Remove deprecated action key
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  tracecat/db/schemas.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/actions/router.py
Labels: internal

#700 test: Improve database fixture isolation
  tests/conftest.py
Labels: tests, internal

#701 chore(integration)!: Drop velociraptor integration
  registry/pyproject.toml
  registry/tracecat_registry/integrations/velociraptor.py
Labels: integration, breaking

#704 feat(integration)!: Normalize Okta templates
  registry/tracecat_registry/templates/okta/expire_sessions.yml
  registry/tracecat_registry/templates/okta/get_user.yml
  registry/tracecat_registry/templates/okta/get_user_by_email.yml
  registry/tracecat_registry/templates/okta/list_user_events.yml
  registry/tracecat_registry/templates/okta/reset_password.yml
  registry/tracecat_registry/templates/okta/suspend_user.yml
  registry/tracecat_registry/templates/okta/unsuspend_user.yml
Labels: integration, breaking

#697 feat(engine): Implement error handler workflow functionality in DSLWorkflow
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  tests/unit/test_workflows.py
  tracecat/dsl/common.py
  tracecat/dsl/models.py
  tracecat/dsl/scheduler.py
  tracecat/dsl/workflow.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
Labels: enhancement, engine

#705 feat(ui): Rename commit to save
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/providers/workflow.tsx
  tracecat/workflow/management/management.py
Labels: frontend

#698 feat(ui): Add error handler configuration to workflow panel
  frontend/src/components/workbench/panel/workflow-panel.tsx
  tests/unit/test_workflows.py
Labels: enhancement, frontend

#707 chore(ui): Delete unused elements in workflow trigger and alias
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/canvas/trigger-node.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
Labels: frontend, chore

#711 feat(ui): Add template tab and fix state actions on node click
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
  frontend/src/components/workbench/workbench.tsx
  frontend/src/lib/hooks.tsx
Labels: enhancement, frontend

#710 feat(app): Implement organization settings backend
  alembic/versions/496c162975d7_add_organization_settings_table.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  tests/conftest.py
  tests/unit/test_organization_settings.py
  tests/unit/test_secrets.py
  tracecat/config.py
  tracecat/db/schemas.py
  tracecat/secrets/encryption.py
  tracecat/settings/__init__.py
  tracecat/settings/constants.py
  tracecat/settings/models.py
  tracecat/settings/router.py
  tracecat/settings/service.py
Labels: enhancement

#715 refactor(app): `setup_registry` -> `reload_registry` + move to `registry.common` + add router
  tracecat/api/app.py
  tracecat/api/common.py
  tracecat/registry/common.py
  tracecat/registry/repositories/router.py
Labels: internal, refactor

#722 fix: Show continue with other auth methods if there's no basic auth + small fixes
  frontend/src/components/auth/sign-in.tsx
  tests/unit/test_organization_settings.py
  tracecat/auth/dependencies.py
Labels: fix

#723 refactor+test: Improve testing for auth config dep
  tests/unit/test_dependencies.py
  tracecat/auth/dependencies.py
Labels: tests, refactor

#726 security: Update next js
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: build, security

#727 security(api): Add http security headers to server-side calls
  tracecat/api/app.py
  tracecat/middleware/security.py
Labels: security, api

#728 feat: Tighten input validation
  frontend/src/app/registry/actions/edit/page.tsx
  frontend/src/app/registry/actions/new/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/auth/sign-up.tsx
  frontend/src/components/dashboard/workflow-tags-sidebar.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
  frontend/src/lib/errors.ts
  tracecat/api/app.py
  tracecat/registry/actions/models.py
  tracecat/registry/repositories/models.py
  tracecat/secrets/models.py
  tracecat/tags/models.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
  tracecat/workspaces/models.py
Labels: enhancement, frontend, api

#731 fix: Cleanup and fix lint/format issues
  alembic/versions/0a85ea95e68c_add_schedule_timeout.py
  alembic/versions/307c3bb9fad5_add_user_last_login_at.py
  alembic/versions/3bc0a0970817_add_tags_and_workflow_tags_tables.py
  alembic/versions/496c162975d7_add_organization_settings_table.py
  alembic/versions/8be6393b2ee0_add_workflow_alias.py
  alembic/versions/9194fb66b4ea_add_doc_url_and_author_to_.py
  alembic/versions/b7a3a2146bac_add_accesstoken_id.py
  alembic/versions/da03a0dfa2db_add_repo_last_synced_at_and_commit_sha.py
  alembic/versions/f2e840c9fb2c_add_workflow_error_handler.py
  justfile
  pyproject.toml
  tests/unit/test_executor.py
  tests/unit/test_functions.py
  tests/unit/test_sandbox.py
  tests/unit/test_workflows.py
  tracecat/contexts.py
  tracecat/db/engine.py
  tracecat/dsl/common.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/executor/models.py
  tracecat/expressions/core.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/validator.py
  tracecat/registry/repository.py
  tracecat/secrets/secrets_manager.py
  tracecat/validation/service.py
Labels: internal

#730 fix(app): Add fallback for org settings
  tests/unit/test_organization_settings.py
  tracecat/api/executor.py
  tracecat/auth/dependencies.py
  tracecat/auth/users.py
  tracecat/registry/common.py
  tracecat/registry/repository.py
  tracecat/settings/service.py
Labels: fix, api

#725 feat(app): Get `saml_idp_metadata_url` from settings service
  tracecat/auth/saml.py
Labels: enhancement, api

#729 security: Drop stack trace from failure message
  frontend/next-env.d.ts
  frontend/src/components/executions/event-details.tsx
  tracecat/executor/models.py
  tracecat/workflow/executions/models.py
Labels: security

#732 feat: Add warning in get_setting default path
  tracecat/settings/service.py
Labels: internal

#733 fix(app): Add role in SAML router dependency
  tracecat/auth/saml.py
Labels: fix

#734 feat(ui): Add refetchInterval of 2s to useWorkflowExecutionEventHistory
  frontend/src/components/executions/event-history.tsx
  frontend/src/lib/hooks.tsx
  tracecat/workflow/executions/service.py
Labels: enhancement, frontend

#735 release: Bump 0.20.0
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#736 refactor: Organize git and ssh utils + lint fixes
  tests/unit/test_registry.py
  tracecat/git.py
  tracecat/parse.py
  tracecat/registry/loaders.py
  tracecat/registry/repository.py
  tracecat/secrets/service.py
  tracecat/ssh.py
Labels: internal

#737 refactor(app): Separate org secrets
  frontend/next-env.d.ts
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/lib/hooks.tsx
  tests/unit/test_executor.py
  tests/unit/test_secrets_service.py
  tracecat/api/app.py
  tracecat/secrets/enums.py
  tracecat/secrets/models.py
  tracecat/secrets/router.py
  tracecat/secrets/service.py
  tracecat/validation/service.py
Labels: internal, refactor, security, api

#739 chore: Merge 0.20.1 hotfix into main
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: fix

#740 docs: Fix incorrect for loop
  docs/tutorials/4-child-workflows.mdx
Labels: documentation

#742 release: Bump 0.20.2
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#743 feat(engine): Add set difference function and tests
  docs/cheatsheets/functions.mdx
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, engine

#630 feat(integration): Normalize 'Get CP XDR incidents' template
  registry/tracecat_registry/templates/checkpoint/get_xdr_incidents.yml
Labels: enhancement, integration

#747 fix(app): Catch correct exception in secret validation
  tracecat/secrets/service.py
  tracecat/validation/service.py
Labels: bug, fix

#749 Add nextjs security headers
  frontend/next.config.mjs
Labels: security

#750 feat(integrations)!: Unified integrations model schemas
  registry/tracecat_registry/schemas/detect/analyze_domain.yml
  registry/tracecat_registry/schemas/detect/analyze_file_hash.yml
  registry/tracecat_registry/schemas/detect/analyze_ip_address.yml
  registry/tracecat_registry/schemas/detect/analyze_url.yml
  registry/tracecat_registry/schemas/detect/detect_malware.yml
  registry/tracecat_registry/schemas/detect/list_alerts.yml
  registry/tracecat_registry/schemas/detect/list_incidents.yml
  registry/tracecat_registry/schemas/detect/lookup_domain.yml
  registry/tracecat_registry/schemas/detect/lookup_file_hash.yml
  registry/tracecat_registry/schemas/detect/lookup_ip_address.yml
  registry/tracecat_registry/schemas/detect/lookup_url.yml
  registry/tracecat_registry/schemas/detect/lookup_user_by_email.yml
  registry/tracecat_registry/schemas/detect/lookup_user_by_id.yml
  registry/tracecat_registry/schemas/detect/query_events.yml
  registry/tracecat_registry/schemas/harden/list_agents.yml
  registry/tracecat_registry/schemas/harden/update_agents.yml
  registry/tracecat_registry/schemas/model/list_devices.yml
  registry/tracecat_registry/schemas/notify/add_comment.yml
  registry/tracecat_registry/schemas/notify/create_incident.yml
  registry/tracecat_registry/schemas/notify/post_notification.yml
  registry/tracecat_registry/schemas/notify/update_incident.yml
  registry/tracecat_registry/schemas/response/allow_ip_address.yml
  registry/tracecat_registry/schemas/response/block_ip_address.yml
  registry/tracecat_registry/schemas/response/execute_script.yml
  registry/tracecat_registry/schemas/response/lock_device.yml
  registry/tracecat_registry/schemas/response/revoke_sessions.yml
  registry/tracecat_registry/schemas/response/shutdown_device.yml
  registry/tracecat_registry/templates/crowdsec/block_ip_address.yml
  registry/tracecat_registry/templates/crowdsec/search_ip_address.yml
  registry/tracecat_registry/templates/crowdsec/unblock_ip_address.yml
Labels: enhancement, integration, breaking

#754 feat(engine): Add and update git and ssh modules
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  tests/unit/test_registry.py
  tracecat/api/common.py
  tracecat/dsl/scheduler.py
  tracecat/git.py
  tracecat/identifiers/__init__.py
  tracecat/registry/repository.py
  tracecat/settings/service.py
  tracecat/ssh.py
  tracecat/types/exceptions.py
Labels: enhancement, engine

#751 feat: Add `deprecated` field to RegistryAction
  alembic/versions/849db8d3b59d_add_deprecated_field_to_.py
  registry/tracecat_registry/_internal/registry.py
  tests/unit/test_registry.py
  tracecat/db/schemas.py
  tracecat/registry/actions/models.py
  tracecat/registry/loaders.py
  tracecat/registry/repository.py
Labels: enhancement, api

#758 feat(engine): Basic implementation for pull-based executor and remove internal executor endpoints
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/lib/hooks.tsx
  pyproject.toml
  tests/unit/test_executor_service.py
  tracecat/api/executor.py
  tracecat/dsl/action.py
  tracecat/dsl/models.py
  tracecat/executor/client.py
  tracecat/executor/models.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/git.py
  tracecat/registry/repositories/router.py
  tracecat/registry/repository.py
  tracecat/secrets/service.py
  tracecat/settings/service.py
  tracecat/ssh.py
Labels: enhancement, engine

#761 refactor: Standardize workflow executions models
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/[executionId]/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/executions/event-history.tsx
  frontend/src/components/executions/nav.tsx
  frontend/src/lib/event-history.ts
  frontend/src/lib/hooks.tsx
  tests/unit/test_workflows.py
  tracecat/webhooks/router.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
Labels: internal

#763 feat(engine): Add defaults to register kwargs model
  tracecat/registry/loaders.py
  tracecat/registry/repository.py
Labels: internal

#764 refactor(app): Standardize workflow execution service routes
  docs/mint.json
  docs/openapi.yml
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/[executionId]/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/executions/event-history.tsx
  frontend/src/components/executions/nav.tsx
  frontend/src/lib/event-history.ts
  frontend/src/lib/hooks.tsx
  tests/unit/test_workflows.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
Labels: internal, api

#766 refactor(app): Rename `EventHistoryType` -> `WorkflowEventType`
  docs/openapi.yml
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  tests/unit/test_workflows.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
Labels: internal, api

#767 feat(integrations): Tenable nessus scans
  registry/pyproject.toml
  registry/tracecat_registry/integrations/tenable_nessus.py
  registry/tracecat_registry/templates/tenable_nessus/list_vulnerabilities.yml
Labels: enhancement

#768 release: 0.21.0
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#770 ci: Remove Temporal cli from Python tests
  .github/workflows/test-python.yml
Labels: cicd, internal

#772 fix(integrations): Ensure GOOGLE_API_CREDENTIALS is a mapping object
  registry/tracecat_registry/integrations/google_api.py
Labels: integration, fix

#771 feat(app): Compact workflow runs in builder backend
  docs/api-reference/reference/workflow-executions/get-workflow-execution-compact.mdx
  docs/mint.json
  docs/openapi.yml
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/lib/event-history.ts
  tests/unit/test_workflows.py
  tracecat/auth/enums.py
  tracecat/dsl/common.py
  tracecat/dsl/workflow.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/enums.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
Labels: enhancement, api

#774 fix(engine): Manually manage ssh agent
  tests/unit/test_executor_service.py
  tracecat/executor/service.py
  tracecat/registry/repository.py
  tracecat/ssh.py
Labels: engine, fix

#776 fix(engine): Revert Ray SSH agent changes and fix SSH key formatting
  frontend/src/components/organization/org-ssh-key-create.tsx
  tests/unit/test_executor_service.py
  tests/unit/test_secrets_service.py
  tracecat/executor/service.py
  tracecat/registry/repository.py
  tracecat/secrets/models.py
  tracecat/secrets/service.py
  tracecat/ssh.py
Labels: engine, fix

#777 feat(ui): Preparations for compact builder runs
  alembic/versions/db3c91261770_add_temporal_search_attributes.py
  frontend/src/app/workspaces/layout.tsx
  frontend/src/components/executions/event-history.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/workbench/canvas/canvas.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
  frontend/src/lib/hooks.tsx
  frontend/src/providers/builder.tsx
  tracecat/workflow/executions/service.py
Labels: frontend, internal

#784 feat(app): Preparations to remove search attributes
  tests/unit/test_base62.py
  tests/unit/test_identifiers.py
  tracecat/base62.py
  tracecat/identifiers/common.py
  tracecat/identifiers/workflow.py
Labels: internal

#783 docs(integrations): Clearer descriptions for `payload` and `form_data`
  registry/tracecat_registry/base/core/http.py
Labels: documentation, integrations, api

#778 feat(integrations): Support datetime or string in datetime functions
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, integrations

#788 release: 0.21.7
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#785 feat(engine): Use WorkflowUUID as canonical ID
  frontend/src/app/workspaces/[workspaceId]/workflows/[workflowId]/executions/[executionId]/page.tsx
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/lib/event-history.ts
  registry/tracecat_registry/base/core/workflow.py
  tests/playbooks/test_playbooks.py
  tests/shared.py
  tests/unit/test_error_handling.py
  tests/unit/test_executor.py
  tests/unit/test_executor_service.py
  tests/unit/test_expressions.py
  tests/unit/test_workflows.py
  tracecat/dsl/common.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/editor/router.py
  tracecat/identifiers/common.py
  tracecat/identifiers/workflow.py
  tracecat/webhooks/dependencies.py
  tracecat/webhooks/models.py
  tracecat/webhooks/router.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/actions/router.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/dependencies.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/models.py
  tracecat/workflow/management/router.py
  tracecat/workflow/schedules/bridge.py
  tracecat/workflow/schedules/models.py
  tracecat/workflow/schedules/router.py
  tracecat/workflow/schedules/service.py
  tracecat/workflow/tags/router.py
Labels: internal

#790 release: 0.21.8
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#791 feat(engine): Migrate workflow ID schema
  alembic/versions/f92c80ef8c9d_use_uuids_for_workflows.py
  frontend/next-env.d.ts
  tracecat/db/schemas.py
  tracecat/dsl/common.py
  tracecat/identifiers/workflow.py
  tracecat/webhooks/dependencies.py
  tracecat/workflow/actions/router.py
  tracecat/workflow/executions/router.py
  tracecat/workflow/management/definitions.py
  tracecat/workflow/management/management.py
  tracecat/workflow/management/router.py
  tracecat/workflow/schedules/service.py
Labels: enhancement, engine, migration

#792 refactor: Cleanup __get_pydantic_core_schema__ for TracecatUUID
  tracecat/identifiers/common.py
Labels: internal

#793 feat: Add compact runs UI
  alembic/versions/db3c91261770_add_temporal_search_attributes.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/loading/spinner.tsx
  frontend/src/components/nav/dynamic-nav.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/ui/resizable.tsx
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/events/events-sidebar-empty.tsx
  frontend/src/components/workbench/events/events-sidebar.tsx
  frontend/src/components/workbench/events/events-workflow.tsx
  frontend/src/components/workbench/workbench.tsx
  frontend/src/lib/event-history.ts
  frontend/src/lib/hooks.tsx
  frontend/src/providers/builder.tsx
  tracecat/dsl/common.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/service.py
Labels: enhancement, frontend

#794 refactor: Silence noisy warning logs
  tracecat/dsl/workflow.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
Labels: internal

#796 feat(ui): Right click to drop selector node
  frontend/src/components/workbench/canvas/canvas.tsx
Labels: enhancement, frontend

#797 feat(ui): Replace sidebar toggle button
  frontend/src/components/workbench/workbench.tsx
Labels: enhancement, frontend

#798 fix(ui): Fix overflow and scroll behavior in events sidebar
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/events/events-sidebar.tsx
  frontend/src/components/workbench/workbench.tsx
Labels: enhancement, fix

#786 feat(integrations)!: Update all Python integrations
  .github/workflows/test-python.yml
  registry/pyproject.toml
  registry/tracecat_registry/integrations/ansible.py
  registry/tracecat_registry/integrations/aws_boto3.py
  registry/tracecat_registry/integrations/aws_s3.py
  registry/tracecat_registry/integrations/check_point_infinity.py
  registry/tracecat_registry/integrations/checkpoint.py
  registry/tracecat_registry/integrations/crowdstrike_falconpy.py
  registry/tracecat_registry/integrations/google_api.py
  registry/tracecat_registry/integrations/jamf.py
  registry/tracecat_registry/integrations/ldap3.py
  registry/tracecat_registry/integrations/limacharlie.py
  registry/tracecat_registry/integrations/microsoft_graph.py
  registry/tracecat_registry/integrations/pymongo.py
  registry/tracecat_registry/integrations/slack_sdk.py
  registry/tracecat_registry/integrations/tenable_nessus.py
  registry/tracecat_registry/integrations/wiz.py
  tests/unit/test_registry.py
Labels: integrations, breaking

#800 feat(engine): Pull all dependent secrets outside template action loop
  registry/tracecat_registry/_internal/models.py
  tests/unit/test_templates.py
  tracecat/executor/service.py
  tracecat/registry/actions/models.py
  tracecat/registry/actions/service.py
  tracecat/registry/loaders.py
  tracecat/types/exceptions.py
Labels: enhancement, engine

#802 feat(ui): Add event failure and error message to result
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/code-block.tsx
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
Labels: enhancement, frontend

#805 feat(ui): Show action status in input and result tabs
  frontend/src/components/workbench/events/events-selected-action.tsx
Labels: enhancement, frontend

#807 fix(ui): Scrolling making workflow builder minify
  frontend/src/components/workbench/canvas/selector-node.tsx
Labels: frontend, fix

#806 refactor(app): Change builder action inputs to use string
  alembic/versions/4e07917dc4e8_keep_action_inputs_as_yaml_string.py
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  tracecat/db/schemas.py
  tracecat/dsl/common.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/actions/router.py
  tracecat/workflow/management/management.py
Labels: frontend

#808 feat(ui): Remove braces in copy action ref
  frontend/src/components/workbench/canvas/action-node.tsx
Labels: enhancement, frontend

#810 feat(engine): Add http polling action
  .github/workflows/test-python.yml
  registry/tracecat_registry/base/core/http.py
  tests/registry/test_core_http.py
  tests/stress/server.py
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: engine, integrations

#812 release: 0.22.0
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  tracecat/__init__.py
Labels: release

#814 fix(ui): Fix positioning of workflow status icon in UI
  frontend/src/components/workbench/events/events-workflow.tsx
Labels: frontend, fix

#815 feat(app): Pre-fill action required inputs if empty
  tracecat/workflow/actions/router.py
Labels: enhancement

#817 test: Add more tests for imports
  tests/unit/test_export.py
Labels: tests
