Repository TracecatHQ/tracecat, pull requests merged in 2025-02, with the labels that each got.

#818 feat(app): Improve git url validation
  tests/conftest.py
  tests/unit/test_repositories.py
  tracecat/registry/repositories/models.py
  tracecat/registry/repositories/router.py
Labels: enhancement, security

#819 feat(app): Add support for local repositories
  .env.example
  docker-compose.dev.yml
  docker-compose.yml
  tests/unit/test_local_registry.py
  tracecat/config.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/registry/common.py
  tracecat/registry/constants.py
  tracecat/registry/loaders.py
  tracecat/registry/repositories/models.py
  tracecat/registry/repository.py
Labels: enhancement

#811 feat(ui): Make validation error look less intimidating
  frontend/src/providers/workflow.tsx
Labels: frontend

#821 release: 0.22.1
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#822 fix(ci): Pin working corepack version
  frontend/Dockerfile.prod
Labels: cicd, fix

#823 release: 0.22.1
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
  docker-compose.yml
  docs/self-hosting/deployment-options/docker-compose.mdx
  docs/tutorials/updating.mdx
  tracecat/__init__.py
Labels: release

#816 fix(integrations): Wazuh update rename `id` to `agent`
  registry/tracecat_registry/templates/wazuh/update_agents.yml
Labels: integrations, fix

#801 feat(integrations): Add maintainer and doc url to wazuh templates
  registry/tracecat_registry/templates/wazuh/clear_rootcheck.yml
  registry/tracecat_registry/templates/wazuh/get_auth_token.yml
  registry/tracecat_registry/templates/wazuh/get_last_rootcheck_scan.yml
  registry/tracecat_registry/templates/wazuh/get_results_rootcheck.yml
  registry/tracecat_registry/templates/wazuh/run_rootcheck.yml
  registry/tracecat_registry/templates/wazuh/update_agents.yml
Labels: enhancement, integrations

#820 create an action for VirusTotal domain reputation report.
  registry/tracecat_registry/templates/threat_intel/virustotal/search_domain.yml
Labels: enhancement, integrations

#824 fix(app): Install local repository with third-party dependencies in executor
  pyproject.toml
  tests/unit/test_parse.py
  tracecat/executor/service.py
  tracecat/parse.py
  tracecat/registry/repository.py
Labels: fix

#825 fix(app): Attempt to fix RegisterKwargs validation error
  registry/tracecat_registry/_internal/registry.py
  tracecat/registry/repository.py
Labels: fix

#826 deps: Bump temporalio to 1.9.0
  pyproject.toml
Labels: dependencies

#827 perf(engine): Improved DAG scheduling algorithm
  tracecat/dsl/scheduler.py
Labels: performance

#829 feat(engine): Add `wait_until` and `retry_until`
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/workbench/panel/action-panel-tooltips.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  pyproject.toml
  tests/unit/test_workflow_timers.py
  tracecat/api/app.py
  tracecat/api/common.py
  tracecat/dsl/action.py
  tracecat/dsl/common.py
  tracecat/dsl/models.py
  tracecat/dsl/workflow.py
  tracecat/expressions/validation.py
  tracecat/workflow/actions/models.py
  tracecat/workflow/executions/common.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
  tracecat/workflow/management/management.py
Labels: enhancement

#833 feat(ui): Make json view text smaller
  frontend/src/components/workbench/events/events-selected-action.tsx
Labels: frontend

#834 feat(ui): Add toggle button for action panel and resize tabs
  frontend/src/components/workbench/events/events-sidebar.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/workbench-panel.tsx
  frontend/src/components/workbench/workbench.tsx
  frontend/src/providers/builder.tsx
Labels: frontend

#835 fix(ui): Catch YAML parsing issues and show invalid configuration in the UI
  frontend/src/components/workbench/canvas/action-node.tsx
Labels: frontend, fix

#836 fix(engine): Always return list when using jsonpath wildcard
  tests/unit/test_expressions.py
  tracecat/expressions/functions.py
Labels: engine, fix

#828 feat(integrations): Add Tracecat prefix to email
  registry/tracecat_registry/base/core/email.py
Labels: enhancement

#837 feat(integrations)!: `is_in`, `is_not_in` and `deduplicate` core actions
  registry/tracecat_registry/base/core/http.py
  registry/tracecat_registry/base/core/transform.py
  tests/data/workflows/unit_transform_filter_function.yml
  tests/data/workflows/unit_transform_filter_function_expected.yml
  tests/registry/test_core_transform.py
  tests/unit/test_expressions.py
  tests/unit/test_functions.py
  tests/unit/test_parse.py
  tests/unit/test_workflows.py
  tracecat/expressions/common.py
  tracecat/expressions/functions.py
  tracecat/expressions/parser/evaluator.py
  tracecat/expressions/parser/validator.py
Labels: enhancement, breaking

#838 fix(engine): Improve action loop error display
  tests/data/test_actions/test_executor_functions.py
  tests/unit/test_executor.py
  tests/unit/test_parse.py
  tests/unit/test_workflows.py
  tracecat/dsl/action.py
  tracecat/executor/client.py
  tracecat/executor/models.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/expressions/validation.py
  tracecat/parse.py
  tracecat/registry/actions/models.py
  tracecat/types/exceptions.py
Labels: engine, fix

#841 feat(app): Add structural and args validation for action templates
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/registry/registry-action-validation-error.tsx
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/lib/errors.ts
  frontend/src/lib/hooks.tsx
  tests/unit/test_common.py
  tests/unit/test_expressions.py
  tests/unit/test_validation.py
  tracecat/common.py
  tracecat/executor/service.py
  tracecat/expressions/functions.py
  tracecat/expressions/patterns.py
  tracecat/expressions/validation.py
  tracecat/registry/actions/enums.py
  tracecat/registry/actions/models.py
  tracecat/registry/actions/service.py
  tracecat/registry/loaders.py
  tracecat/registry/repositories/models.py
  tracecat/registry/repositories/router.py
  tracecat/validation/service.py
Labels: enhancement, integrations

#846 build: Force `production` env in prod docker compose
  docker-compose.yml
Labels: build

#843 feat(integrations): Add `url_decode` function
  tests/unit/test_functions.py
  tracecat/expressions/functions.py
Labels: enhancement, integrations

#845 feat(integration): Lookup Domain with VirusTotal
  registry/tracecat_registry/templates/detect/lookup_domain/virustotal.yml
Labels: enhancement, integrations

#856 feat(registry): Add CLI for template validation
  registry/pyproject.toml
  registry/tracecat_registry/__main__.py
  registry/tracecat_registry/cli/entrypoint.py
  registry/tracecat_registry/cli/validate.py
  tracecat/registry/actions/service.py
  tracecat/registry/repository.py
Labels: enhancement, integrations

#849 feat(integration): Lookup threat intel with Anomali ThreatStream
  registry/tracecat_registry/schemas/detect/lookup_email.yml
  registry/tracecat_registry/templates/detect/lookup_domain/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_email/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_file_hash/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_ip_address/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_url/threatstream.yml
Labels: enhancement, integrations

#842 feat(integration): Lookup IP address with Crowdsec #840
  registry/tracecat_registry/templates/detect/lookup_ip_address/crowdsec_cti.yml
Labels: enhancement, integrations

#859 fix(integrations): Steps and API naming in anomali lookups
  registry/tracecat_registry/templates/detect/lookup_domain/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_email/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_file_hash/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_ip_address/threatstream.yml
  registry/tracecat_registry/templates/detect/lookup_url/threatstream.yml
Labels: integrations, fix

#860 test: Add template validation to unit tests
  tests/registry/test_templates.py
Labels: tests

#858 feat(ui): Make copy button in builder view copy jsonpath
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
Labels: enhancement, frontend

#851 feat(integrations): Add lookup_ip_address for IPinfo.io
  registry/tracecat_registry/templates/detect/lookup_ip_address/ipinfoio.yml
Labels: integrations

#863 security: Fix dependabot alerts
  docs/package.json
  docs/pnpm-lock.yaml
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: frontend, build, security

#864 feat(core)!: Add `apply` and `map`
  registry/tracecat_registry/base/core/transform.py
  tests/registry/test_core_transform.py
Labels: enhancement, core-actions

#865 chore: Drop example actions
  registry/tracecat_registry/base/core/example.py
  tests/data/workflows/shared_adder_tree.yml
  tests/data/workflows/shared_kite.yml
  tests/data/workflows/shared_tree.yml
  tests/data/workflows/stress_adder_tree.yml
  tests/data/workflows/unit_conditional_adder_diamond_skip_with_join_strong_dep_fails.yml
  tests/data/workflows/unit_conditional_adder_diamond_skip_with_join_weak_dep.yml
  tests/data/workflows/unit_conditional_adder_tree_continues.yml
  tests/data/workflows/unit_conditional_adder_tree_skip_propagates.yml
  tests/data/workflows/unit_conditional_adder_tree_skips.yml
  tests/data/workflows/unit_error_fatal.yml
Labels: integrations, chore

#861 feat(ui): Merge child workflow compact runs
  frontend/src/client/schemas.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/workbench/events/events-selected-action.tsx
  tracecat/dsl/common.py
  tracecat/dsl/workflow.py
  tracecat/workflow/executions/models.py
  tracecat/workflow/executions/service.py
Labels: enhancement, frontend

#869 fix(app): Try fix first builder run not showing up (again)
  frontend/src/lib/hooks.tsx
  tracecat/workflow/executions/service.py
Labels: frontend, fix

#870 refactor(app): Remove schedule inputs hover card
  frontend/src/components/workbench/panel/trigger-panel.tsx
Labels: frontend

#871 feat(ui): Decouple left sidebar from action panel config
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/events/events-sidebar.tsx
  frontend/src/components/workbench/events/events-workflow.tsx
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
Labels: enhancement, frontend

#875 fix(ui): Further decouple events sidebar from canvas action
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/events/events-workflow.tsx
  frontend/src/lib/workflow.ts
  frontend/src/providers/builder.tsx
Labels: frontend, fix

#876 fix(app): Include secrets in update params
  tracecat/registry/actions/models.py
Labels: fix

#877 docs: Add if-condition examples
  docs/quickstart/tutorial.mdx
  frontend/src/components/workbench/panel/action-panel-tooltips.tsx
Labels: documentation

#878 fix(engine): Address loop recursion error issues
  tests/unit/test_parse.py
  tracecat/auth/sandbox.py
  tracecat/dsl/workflow.py
  tracecat/executor/client.py
  tracecat/executor/models.py
  tracecat/executor/router.py
  tracecat/executor/service.py
  tracecat/parse.py
Labels: engine, fix

#866 feat(core): `require` conditional action
  registry/tracecat_registry/base/core/require.py
  tests/registry/test_core_require.py
  tests/unit/test_expressions.py
  tracecat/expressions/functions.py
  tracecat/expressions/parser/grammar.py
Labels: enhancement, core-actions

#879 tests(refactor): Move template action tests into `test_template_actions.py`
  tests/unit/test_registry.py
  tests/unit/test_template_actions.py
Labels: tests, refactor

#881 ci(infra): Add temporal and ray dashboards to docker prod
  docker-compose.dev.yml
  docker-compose.yml
  pyproject.toml
  tracecat/executor/engine.py
Labels: cicd, infrastructure

#880 feat(app): Implement tables service
  alembic/versions/4aade4315ef9_add_tables_table.py
  tests/unit/test_tables_service.py
  tests/unit/test_tags_service.py
  tracecat/api/app.py
  tracecat/db/schemas.py
  tracecat/identifiers/__init__.py
  tracecat/identifiers/workflow.py
  tracecat/tables/models.py
  tracecat/tables/router.py
  tracecat/tables/service.py
Labels: enhancement

#882 feat(engine): Implement `core.table.lookup` action
  frontend/src/components/icons.tsx
  frontend/src/components/workbench/panel/action-panel-tooltips.tsx
  registry/tracecat_registry/base/core/table.py
  registry/tracecat_registry/base/core/transform.py
  tests/conftest.py
  tests/unit/test_workflows.py
  tracecat/dsl/action.py
  tracecat/dsl/common.py
  tracecat/dsl/constants.py
  tracecat/dsl/enums.py
  tracecat/dsl/workflow.py
  tracecat/tables/router.py
  tracecat/tables/service.py
  tracecat/validation/service.py
  tracecat/workflow/executions/models.py
Labels: enhancement, engine

#883 feat(engine): Implement insert row action
  registry/tracecat_registry/__init__.py
  registry/tracecat_registry/_internal/exceptions.py
  registry/tracecat_registry/base/core/table.py
  registry/tracecat_registry/base/core/workflow.py
  tests/unit/test_workflows.py
  tracecat/dsl/action.py
  tracecat/dsl/common.py
  tracecat/dsl/enums.py
  tracecat/validation/service.py
Labels: enhancement, engine

#884 refactor(ui): Rename table to data-table
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/data-table/column-header.tsx
  frontend/src/components/data-table/faceted-filter.tsx
  frontend/src/components/data-table/index.tsx
  frontend/src/components/data-table/pagination.tsx
  frontend/src/components/data-table/table.tsx
  frontend/src/components/data-table/toolbar.tsx
  frontend/src/components/data-table/view-options.tsx
  frontend/src/components/organization/org-members-table.tsx
  frontend/src/components/organization/org-secrets-table.tsx
  frontend/src/components/organization/org-sessions-table.tsx
  frontend/src/components/registry/registry-actions-table.tsx
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/components/workspaces/workspace-members-table.tsx
  frontend/src/components/workspaces/workspace-secrets-table.tsx
Labels: refactor

#885 docs: CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  docs/integrations/development.mdx
  registry/pyproject.toml
Labels: documentation

#890 feat(ui): Add tables UI
  frontend/src/app/workspaces/[workspaceId]/tables/[tableId]/page.tsx
  frontend/src/app/workspaces/[workspaceId]/tables/layout.tsx
  frontend/src/app/workspaces/[workspaceId]/tables/page.tsx
  frontend/src/components/dashboard/create-workflow-button.tsx
  frontend/src/components/dashboard/workflow-tags-sidebar.tsx
  frontend/src/components/dashboard/workflows-dashboard.tsx
  frontend/src/components/nav/dynamic-nav.tsx
  frontend/src/components/nav/workspace-nav.tsx
  frontend/src/components/tables/table-create-dialog.tsx
  frontend/src/components/tables/table-delete-dialog.tsx
  frontend/src/components/tables/table-edit-dialog.tsx
  frontend/src/components/tables/table-insert-button.tsx
  frontend/src/components/tables/table-insert-column-dialog.tsx
  frontend/src/components/tables/table-insert-row-dialog.tsx
  frontend/src/components/tables/table-view-action-delete-dialog.tsx
  frontend/src/components/tables/table-view-action.tsx
  frontend/src/components/tables/table-view-column-menu.tsx
  frontend/src/components/tables/table-view.tsx
  frontend/src/components/tables/tables-dashboard.tsx
  frontend/src/components/tables/tables-side-nav.tsx
  frontend/src/lib/hooks.tsx
  frontend/src/lib/tables.ts
Labels: enhancement, frontend

#894 chore(infra): Increase defaults for api_cpu to 1024 and api_memory to 2048
  deployments/aws/ecs/variables.tf
  deployments/aws/variables.tf
Labels: performance, infrastructure

#896 feat(app): Add batch insert for rows
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  tests/unit/test_tables_service.py
  tracecat/tables/models.py
  tracecat/tables/router.py
  tracecat/tables/service.py
Labels: enhancement, api

#895 refactor(ui): Remove edit registry action page
  frontend/src/app/registry/actions/edit/page.tsx
  frontend/src/components/registry/registry-actions-table.tsx
Labels: frontend, refactor

#892 refactor(ui): Remove new registry action page
  frontend/src/app/registry/actions/new/page.tsx
  frontend/src/components/registry/registry-actions-table.tsx
Labels: frontend, refactor

#888 feat(integrations)!: Extend Jira create case with labels
  registry/tracecat_registry/schemas/notify/create_case.yml
  registry/tracecat_registry/templates/notify/create_case/jira.yml
  registry/tracecat_registry/templates/notify/post_todo/slack.yml
  registry/tracecat_registry/templates/tools/README.md
  registry/tracecat_registry/templates/tools/jira/get_fields.yml
  registry/tracecat_registry/templates/tools/jira/get_priorities.yml
  registry/tracecat_registry/templates/tools/jira/get_priority_schemes.yml
  registry/tracecat_registry/templates/tools/jira/get_projects.yml
  tests/registry/test_templates.py
  tests/unit/test_functions.py
  tests/unit/test_template_actions.py
  tracecat/expressions/functions.py
Labels: integrations, breaking

#893 feat(ui): Throw UI error if can't fetch AppInfo from backend
  frontend/src/components/auth/sign-in.tsx
  frontend/src/lib/hooks.tsx
Labels: frontend

#897 feat(app+ui): Add csv importer and add csv import UI
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/client/schemas.gen.ts
  frontend/src/client/services.gen.ts
  frontend/src/client/types.gen.ts
  frontend/src/components/tables/table-import-csv-dialog.tsx
  frontend/src/components/tables/table-insert-button.tsx
  frontend/src/lib/hooks.tsx
  frontend/src/lib/tables.ts
  tests/unit/test_table_csv_importer.py
  tests/unit/test_tables_service.py
  tests/unit/test_workflows.py
  tracecat/dsl/action.py
  tracecat/tables/common.py
  tracecat/tables/importer.py
  tracecat/tables/router.py
  tracecat/tables/service.py
  tracecat/types/exceptions.py
  tracecat/workspaces/router.py
Labels: enhancement, frontend, api

#899 feat(integrations): Add URLScan template with polling
  registry/tracecat_registry/templates/detect/lookup_url/urlscan.yml
Labels: good first issue, integrations

#898 feat(ui): Frontend nits and reworked workspace settings
  docs/tutorials/custom-integrations.mdx
  frontend/next-env.d.ts
  frontend/src/app/error.tsx
  frontend/src/app/organization/credentials/page.tsx
  frontend/src/app/organization/members/page.tsx
  frontend/src/app/organization/sessions/page.tsx
  frontend/src/app/organization/settings/app/page.tsx
  frontend/src/app/organization/settings/auth/page.tsx
  frontend/src/app/organization/settings/git/page.tsx
  frontend/src/app/organization/settings/sso/page.tsx
  frontend/src/app/organization/sidebar-nav.tsx
  frontend/src/app/organization/ssh-keys/page.tsx
  frontend/src/app/registry/repositories/page.tsx
  frontend/src/app/registry/sidebar-nav.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/account/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/credentials/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/general/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/members/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/profile/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/security/page.tsx
  frontend/src/app/workspaces/[workspaceId]/settings/sidebar-nav.tsx
  frontend/src/app/workspaces/[workspaceId]/tables/[tableId]/page.tsx
  frontend/src/app/workspaces/[workspaceId]/tables/page.tsx
  frontend/src/components/auth/update-password-form.tsx
  frontend/src/components/dashboard/create-workflow-button.tsx
  frontend/src/components/dashboard/dashboard-table.tsx
  frontend/src/components/dashboard/workflow-tags-sidebar.tsx
  frontend/src/components/data-table/view-options.tsx
  frontend/src/components/executions/event-details.tsx
  frontend/src/components/nav/user-nav.tsx
  frontend/src/components/nav/workbench-nav.tsx
  frontend/src/components/organization/org-members-table.tsx
  frontend/src/components/organization/org-secrets-table.tsx
  frontend/src/components/organization/org-sessions-table.tsx
  frontend/src/components/organization/org-settings-app.tsx
  frontend/src/components/organization/org-settings-auth.tsx
  frontend/src/components/organization/org-settings-git.tsx
  frontend/src/components/organization/org-settings-oauth.tsx
  frontend/src/components/organization/org-settings-sso.tsx
  frontend/src/components/organization/org-ssh-key-create.tsx
  frontend/src/components/registry/registry-actions-table.tsx
  frontend/src/components/registry/registry-repos-table.tsx
  frontend/src/components/tables/table-create-dialog.tsx
  frontend/src/components/tables/table-import-csv-dialog.tsx
  frontend/src/components/tables/table-insert-button.tsx
  frontend/src/components/tables/table-view-action.tsx
  frontend/src/components/tables/table-view-column-menu.tsx
  frontend/src/components/tables/tables-side-nav.tsx
  frontend/src/components/workbench/canvas/action-node.tsx
  frontend/src/components/workbench/events/events-selected-action.tsx
  frontend/src/components/workbench/events/events-workflow.tsx
  frontend/src/components/workbench/panel/action-panel.tsx
  frontend/src/components/workbench/panel/trigger-panel.tsx
  frontend/src/components/workbench/panel/workflow-panel.tsx
  frontend/src/components/workbench/workbench.tsx
  frontend/src/components/workspaces/delete-workspace.tsx
  frontend/src/components/workspaces/workspace-general.tsx
  frontend/src/components/workspaces/workspace-members-table.tsx
  frontend/src/components/workspaces/workspace-secrets-table.tsx
  frontend/src/lib/hooks.tsx
Labels: frontend

#904 chore(functions)!: Drop non-python lambda `core.transform` actions
  docs/cheatsheets/integrations.mdx
  registry/tracecat_registry/base/core/transform.py
  tests/registry/test_core_transform.py
  tracecat/expressions/functions.py
Labels: core-actions, functions

#906 fix(engine): Use UDF for table actions
  registry/tracecat_registry/base/core/table.py
  tests/unit/test_workflows.py
  tracecat/dsl/action.py
  tracecat/dsl/common.py
  tracecat/tables/service.py
  tracecat/validation/service.py
Labels: fix

#907 feat(core)! Rename exprs to conditions in `core.require` node
  registry/tracecat_registry/base/core/require.py
  tests/registry/test_core_require.py
Labels: breaking, core-actions

#908 refactor(ui): Lift up workflowId parsing outside of WorkflowProvider
  frontend/src/app/workspaces/layout.tsx
  frontend/src/providers/workflow.tsx
Labels: refactor

#910 docs: YAML and JSONPath cheatsheets
  docs/cheatsheets/functions.mdx
  docs/cheatsheets/jsonpath.mdx
  docs/cheatsheets/yaml.mdx
  docs/docs.json
  docs/introduction.mdx
  docs/quickstart/expressions.mdx
  docs/quickstart/tutorial.mdx
  docs/snippets/jsonpath-note.mdx
  docs/snippets/yaml-note.mdx
  docs/tutorials/data-transforms.mdx
Labels: documentation

#913 docs: Data transform and add note on trigger context
  docs/cheatsheets/functions.mdx
  docs/docs.json
  docs/img/tutorials/data-transforms/reshape.png
  docs/img/tutorials/triggers/trigger-expression.png
  docs/introduction.mdx
  docs/quickstart/tutorial.mdx
  docs/snippets/jsonpath-note.mdx
  docs/tutorials/custom-integrations.mdx
  docs/tutorials/data-transforms.mdx
  docs/tutorials/workflow-triggers.mdx
  registry/tracecat_registry/base/core/transform.py
  tracecat/expressions/functions.py
Labels: documentation

#909 fix(ui): Add error handling for duplicate workflow alias
  frontend/src/components/workbench/panel/workflow-panel.tsx
  frontend/src/lib/errors.ts
  frontend/src/providers/workflow.tsx
  tracecat/db/common.py
  tracecat/workflow/management/router.py
Labels: frontend, fix

#917 chore: Updated `env.sh` prompt
  docs/self-hosting/deployment-options/docker-compose.mdx
  env.sh
Labels: documentation, build

#916 fix(engine):: Optional secrets not handled correctly
  tests/unit/test_executor_service.py
  tests/unit/test_sandbox.py
  tracecat/auth/sandbox.py
  tracecat/executor/service.py
Labels: engine, fix

#918 feat(core): Improve `core.http_request` error messages
  registry/tracecat_registry/base/core/http.py
  tests/registry/test_core_http.py
  tests/unit/test_workflows.py
  tracecat/executor/client.py
Labels: enhancement, core-actions
